### ISSUE TITLE
Bug: Street View Image Disappears

### ISSUE THREAD

**Issue by ladann** [ProjectSidewalk/SidewalkWebpage#104]
Sometimes, the street view gets disappeared, and the only way to bring it back is to refresh the webpage. 
![image](https://cloud.githubusercontent.com/assets/7192301/15829070/1b173522-2be0-11e6-96f6-874f15c62748.png)

**Comment by kotarohara** [comment]
Thanks for pointing out. I'll look into it. Could be a bug in Street View API.

**Comment by kotarohara** [comment]
The problem happens because:

1. We drop a user to a certain location where there isn't any Street View image.
2. The interface cannot load a Street View image so it shows this gray background.
3. A Street View image do not get loaded **even you walk to a new location where you do have a Street View image** (Google API bug).

I found a point in the program that was not checking the presence Street View image in the step 1 and fixed it.

I'll keep this open until @danZzyy takes care of #8 which is a related issue.

**Comment by kotarohara** [comment]
Done.
