### ISSUE TITLE
Left side buttons moved up causing misalignment of onboarding jump instructions

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1118]
Due to some change due to the turk code, the buttons on the left side of the tool are moved up. This results in the following ui bug:
![image](https://user-images.githubusercontent.com/2873216/31049931-287f927a-a5f3-11e7-9910-fc801642d143.png)

This only happens if we go via turk referrer. When I visit localhost:9000/audit, the buttons are positioned correctly:
![image](https://user-images.githubusercontent.com/2873216/31049990-3664beaa-a5f4-11e7-9653-11889ec99cc8.png)

**Comment by maddalihanumateja** [comment]
Interesting that this happened. Almost as though the buttons are highlighted by position rather than their id. The mturk code button is hidden (with a display:none option so that it doesn't occupy any space) in the left button container. This is the reason that the buttons on the left side look like they're moved up. Its to compensate for the addition of an extra button. I'll check this out.
