### ISSUE TITLE
Possibly remove no sidewalk label

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1126]
Open street maps (OSM) has a tag for each street called "sidewalk" which could have the value both, left, right, or no ([ref](http://wiki.openstreetmap.org/wiki/Sidewalks#How_to_map)). If most or all streets have this tag (and it is relatively up to data and accurate), then I think that we should remove this label type. The no sidewalk label is sort of confusing; we have no agreed upon frequency with which to place this label, and it can be rather time-intensive to place this label.

We could then include this tag in any access score model, etc. Having the tag per street segment is also probably a lot easier to include in an access score model, or to analyze in other ways. We lose a bit of a level of granularity, in that we don't know if the sidewalk ends in the middle of a street, but that seems like a very minor loss.

**Comment by jonfroehlich** [comment]
I fundamentally disagree with this. The OSM sidewalk tags are not comprehensive, not widely supported, and noisy. Indeed, the Taskar Center's [OpenSidewalks ](https://www.opensidewalks.com/) initiative is, in part, dedicated to help fixing OSM's lack of sidewalk support and to better integrate special data structure that are _pedestrian_ specific rather than _car_ specific.

I think there is tremendous value in mapping where there are not sidewalks (we are operating on the assumption that if no "no sidewalk" label exists then a sidewalk exists). In my experience, I have not found it burdensome to apply this label every pano or every other pano (but I realize I could be an exception here as I always use the keyboard and I'm a power user). I am also not confident that the "no sidewalk" label is, in fact, that confusing. More analysis is needed here to support that argument.

If it is indeed true that the "no sidewalk" label is misapplied or not well understood, I do not think that the solution is to remove that label type but rather to: (i) provide better instructions such as when the label is first clicked, in the tutorial, or perhaps some other "smarter" way that examines how the label is being applied and provides feedback; (ii) perhaps redesign how this label is applied by, for example, by having users circle or paint where there is no sidewalk.

**Comment by misaugstad** [comment]
>The OSM sidewalk tags are not comprehensive, not widely supported, and noisy.

This was the main caveat I had brought up. I agree that we should only use this data if it is comprehensive and accurate. I was not sure of how comprehensive it was, thanks for posting the link to the OpenSidewalks initiative!

>In my experience, I have not found it burdensome to apply this label every pano or every other pano (but I realize I could be an exception here as I always use the keyboard and I'm a power user).

Don't we have a general agreement that the overall task we are asking users to perform is quite complex? If we agree on that, then I think that any way that we can make the experience less complex would be useful.

>I am also not confident that the "no sidewalk" label is, in fact, that confusing. More analysis is needed here to support that argument.

I guess it isn't that confusing, per se. The issue is more that we don't have any reasonable standard. We could say that a user should label every panorama, but that is incredibly inefficient. Or we could ask them to do what we did for GT and label only at intersections and where the sidewalk ends, but that is a bit more complex and possibly not as intuitive.

>If it is indeed true that the "no sidewalk" label is misapplied or not well understood, I do not think that the solution is to remove that label type

I was certainly not proposing that we remove the no sidewalk label type as a solution to the no sidewalk label being misapplied. I am saying that if this data is already present in another open data set, then we should remove the label type from our tool, as it adds unneeded complexity so we can collect redundant data.

As you said, the data in OSM is not standardized and sparse, so I think we should keep the label type. I just wanted us to be on the same page here.

>I fundamentally disagree with this

As I said in the last point, it seems like you are disagreeing with the argument that we should remove the label type because it is difficult, while this is not at all what I was arguing. Do you agree/disagree with the argument that if there is accurate, up to date, open data on the presence/absence of sidewalks elsewhere, that we should remove the no sidewalk label type to reduce the complexity of our tool?

**Comment by jonfroehlich** [comment]
My main argument is that there is value in labeling places with no sidewalks.

**Comment by misaugstad** [comment]
I'm confused. If this data exists in some other open data set, are you saying that there is still value in us collecting separately? If so, why is that?

**Comment by jonfroehlich** [comment]
IMO, the data doesn't exist in some other dataset. If you disagree, it would be great to see your alternative source of data. My understanding is that one of the reasons OpenSidewalks was created was to directly address the lack of good sidewalk data on OSM; however, OpenSidewalks is a small initiative thus far and I think our work could (should) complement and/or contribute to that effort.

**Comment by jonfroehlich** [comment]
Oh, and some government agencies are tracking and publishing their sidewalk datasets... but there is no standardization, often no APIs just data dumps, etc.

**Comment by jonfroehlich** [comment]
@misaugstad and I discussed this on Slack and we are in agreement that the 'no sidewalk' label is important to PS and provides value given that there are no comprehensive sidewalk existences datasets (and what does exist, is not standardized, etc.).
