### ISSUE TITLE
Database table 'user' conflicts with PostgreSQL function

### ISSUE THREAD

**Issue by johannkm** [ProjectSidewalk/SidewalkWebpage#1146]
The sidewalk database has a table named `user`. As discussed in this [StackOverflow post](https://dba.stackexchange.com/a/75559),  `user` is a function keyword in PostgreSQL.

```sql
-- returns current database user
SELECT * FROM user;

-- returns the 'user' table
SELECT * FROM "user";
```

We may want to consider renaming this table since its current name leads to confusing behavior.

**Comment by jonfroehlich** [comment]
Wow, oops. That sucks. And I can't believe this wasn't identified earlier. Yes, we should likely rename this table SidewalkUser or something. Who's the SQL expert in group currently? @misaugstad @manaswis @maddalihanumateja?

**Comment by manaswis** [comment]
Yes, this was known. However, we always wrote queries like `sidewalk.user` to resolve the conflict. Renaming it isn't tough. However, we'd also have to go into the code to change all the raw queries to the new name and also change the name in the data model code. Again not difficult. 

However, I would say its low priority for immediate purposes. Since we are in the middle of data collection by turkers and (soon) volunteers, we should take this up after we are done with the collection of data we need for the paper. We should concentrate on things that are absolutely necessary for the paper. We could apply the NextCity tag to this issue. Thoughts?

**Comment by jonfroehlich** [comment]
NextCity tag for sure. Agree that it's low priority as it isn't really negatively affecting anything.

**Comment by misaugstad** [comment]
Possible future name for this table: `sidewalk_user`

**Comment by misaugstad** [comment]
closing via #1329
