### ISSUE TITLE
Neighborhood Completion Overlay Doesn't Fill Screen

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1152]
This is a very low priority but just seems weird that the black neighborhood completion overlay is sort of like an arbitrary size. See below:

![image](https://user-images.githubusercontent.com/1621749/31793984-93f63810-b4d5-11e7-80c3-119291b99300.png)

**Comment by jonfroehlich** [comment]
Also, this was my first experience receiving this dialog. Seemed to work great--except that I missed out on finishing the mission I was almost ready to complete in that neighborhood (I think I was at like ~80%). So, in some ways, I feel like I didn't get credit for the work in the same way. Indeed, it was enough to convince me to click on 'Continue in this neighborhood.' Interesting to think about.

Also, here's a movie of what happens when I selected 'Go to a new neighborhood'

https://youtu.be/NhSV9i4WBlk

**Comment by misaugstad** [comment]
>except that I missed out on finishing the mission I was almost ready to complete in that neighborhood (I think I was at like ~80%). So, in some ways, I feel like I didn't get credit for the work in the same way. Indeed, it was enough to convince me to click on 'Continue in this neighborhood.' Interesting to think about.

We had talked about how it would have made more sense to have a "finish the neighborhood across all users" mission, instead of abruptly leaving, but the way that missions are currently implemented do not support that at all. This is a type of mission that we will likely want in future cities, with a more flexible way to design missions.

**Comment by jonfroehlich** [comment]
> We had talked about how it would have made more sense to have a "finish the neighborhood across all users" mission, instead of abruptly leaving, but the way that missions are currently implemented do not support that at all. This is a type of mission that we will likely want in future cities, with a more flexible way to design missions.

Agree.

**Comment by misaugstad** [comment]
@MattJ12 this overlay only shows up when you finish auditing an entire neighborhood. To test, it would probably be easiest to figure out how to force the overlay to show up without actually completing a neighborhood so that you can iterate quickly. Then just make sure you adjust the HTML/CSS so that the overlay always fills the whole screen!

**Comment by misaugstad** [comment]
closing via #2005
