### ISSUE TITLE
Completely rethink/redesign user dashboard

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1363]
There are a bunch of issues related to incremental improvements to the user dashboard:
* Remove Labels Per Street Table #414 
* Allow User to See Their Contributions Compared to Others #188 
* Enhancement for the label legend in the map in the user profile page #12
* Visualize Recency in Audit Dashboard #83
* Neighborhood Completion Graph #413

But as we've talked about numerous times, it would be great if the dashboard could be redesigned completely with the design rooted in game design, behavioral economics, research, etc. As @jonfroehlich mentioned in [this comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/414#issuecomment-446717733), here are some potential papers to look at:

- Prestopnik, Nathan R., and Jian Tang. "Points, stories, worlds, and diegesis: Comparing player experiences in two citizen science games." Computers in Human Behavior 52 (2015): 492-506.
- Eveleigh, A., Jennett, C., Lynn, S., & Cox, A. L. (2013, October). “I want to be a Captain! I want to be a Captain!”: Gamification in the Old Weather Citizen Science Project. In Proceedings of the first international conference on gameful design, research, and applications (pp. 79-82). ACM.
- Bowser, A., Hansen, D., He, Y., Boston, C., Reid, M., Gunnell, L., & Preece, J. (2013, October). Using gamification to inspire new citizen science volunteers. In Proceedings of the first international conference on gameful design, research, and applications (pp. 18-25). ACM.
- Iacovides, I., Jennett, C., Cornish-Trestrail, C., & Cox, A. L. (2013, April). Do games attract or sustain engagement in citizen science?: a study of volunteer motivations. In CHI'13 Extended Abstracts on Human Factors in Computing Systems (pp. 1101-1106). ACM.
- Wiggins, Andrea, and Kevin Crowston. "From conservation to crowdsourcing: A typology of citizen science." System Sciences (HICSS), 2011 44th Hawaii international conference on. IEEE, 2011.

**Comment by jonfroehlich** [comment]
Tagging @bridgetsheff so she sees this.

**Comment by jonfroehlich** [comment]
I'm working on this now. Related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1680.

Some quick mocks. Note that I've incorporated some of the leaderboard here using "badge" overlays, which we can implement using SVG + CSS overlays (if we decide to go that route).

This is my fav mock so far:
![image](https://user-images.githubusercontent.com/1621749/94269979-45846000-fef4-11ea-95a0-99e43a6d5629.png)

With validations:
![image](https://user-images.githubusercontent.com/1621749/94270033-59c85d00-fef4-11ea-8eb0-b6546a52fbf8.png)

My first try at it but worried about the potential "abelist" perceptions of icon for the mission (climbing a mountain):

![image](https://user-images.githubusercontent.com/1621749/94270091-706eb400-fef4-11ea-9b7d-fdc24f17cc5c.png)

**Comment by jonfroehlich** [comment]
Here's an initial implementation in [this branch](https://github.com/ProjectSidewalk/SidewalkWebpage/tree/1680-give-users-more-feedback-on-dashboard). 

![image](https://user-images.githubusercontent.com/1621749/94301805-11bf2f80-ff20-11ea-9507-9075691ff81b.png)

A few things remain:
- [ ] There is no backend code to calculate accuracy
- [ ] The distance metric is currently fixed to miles rather than adaptive to miles or kilometers depending on locale. Related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2269
- [ ] The distance calculation I'm using `@MissionTable.getDistanceAudited(user.get.userId)` is returning different results from `@Messages("dashboard.distance")`
- [ ] I haven't done the award badges overlays (which I expect to do for 1st - 9th place, I think). This will also require some backend code.

I also want to do an "Achievements" module below this with badges but I'm likely going to make a new issue for that.

**Comment by jonfroehlich** [comment]
OK, the initial version for this is almost done but it's failing on a type conversion of `scala.Some`:

```
@("$%.1f%%".format(LabelValidationTable.getUserAccuracy(user.get.userId) * 100))
```

Because the `getUserAccuracy` method returns a `scala.Some` object, I'm having difficulty converting that down to a float and then to a percentage. Method signature:

```
def getUserAccuracy(userId: UUID): Option[Float] = db.withSession { implicit session =>
```

So, in `userProfile.scala.html`, I need some conditional logic but not sure how to do that with Scala templating. I want to do something like the following pseudocode:

```
@userAccuracy = LabelValidationTable.getUserAccuracy(user.get.userId)
@if(userAccuracy != null){
  @("$%.1f%%".format(userAccuracy * 100))
}
@else{
  N/A
} 
```

I could also just modify or add a function to LabelValidationTable that returns `getUserAccuracy` as a nicely formatted percentage string (or N/A if our criteria is not met) but this feels like breaking the contract between the Scala template and backend.

The full method signature is:

```
def getUserAccuracy(userId: UUID): Option[Float] = db.withSession { implicit session =>
    val accuracyQuery = Q.query[String, Option[Float]](
      """SELECT CASE WHEN validated_count > 9 THEN accuracy ELSE NULL END AS accuracy
			FROM (
				SELECT user_id,
					   CAST (COUNT(CASE WHEN n_agree > n_disagree THEN 1 END) AS FLOAT) / NULLIF(COUNT(CASE WHEN n_agree > n_disagree THEN 1 END) + COUNT(CASE WHEN n_disagree > n_agree THEN 1 END), 0) AS accuracy,
					   COUNT(CASE WHEN n_agree > n_disagree THEN 1 END) + COUNT(CASE WHEN n_disagree > n_agree THEN 1 END) AS validated_count
				FROM (
					SELECT mission.user_id, label.label_id,
						   COUNT(CASE WHEN validation_result = 1 THEN 1 END) AS n_agree,
						   COUNT(CASE WHEN validation_result = 2 THEN 1 END) AS n_disagree
					FROM mission
					INNER JOIN label ON mission.mission_id = label.mission_id
					INNER JOIN label_validation ON label.label_id = label_validation.label_id
					WHERE mission.user_id = ?
					GROUP BY mission.user_id, label.label_id
				) agree_count
				GROUP BY user_id
			) "accuracy";""".stripMargin
    )
    accuracyQuery(userId.toString).list.headOption.flatten
  }
```

**Comment by misaugstad** [comment]
Okay I think you're looking for something like
```
@userAccuracy.map("$%.1f%%".format(_ * 100)).getOrElse("N/A")
```

Where the `_` is just how you can reference the thing you're mapping over. So you could also write it as
```
@userAccuracy.map(a => "$%.1f%%".format(a * 100)).getOrElse("N/A")
```

**Comment by jonfroehlich** [comment]
Can I actually store a variable in the Scala template or do I need to do this all on one line, so like:

```
@LabelValidationTable.getUserAccuracy(user.get.userId).map(a => "$%.1f%%".format(a * 100)).getOrElse("N/A")
```

**Comment by misaugstad** [comment]
You technically can using something like [this](https://www.playframework.com/documentation/2.3.x/ScalaTemplates#Declaring-reusable-values). But I think doing it one line is probably best.

**Comment by jonfroehlich** [comment]
Booya!

![image](https://user-images.githubusercontent.com/1621749/94352823-9d1eea80-001e-11eb-8904-f35c2f8fcb7b.png)

**Comment by jonfroehlich** [comment]
Just committed the fixed version. Now off to make dinner for the fam!

**Comment by misaugstad** [comment]
nice

**Comment by jonfroehlich** [comment]
I'm closing this in favor of:

- https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2280 for adding quick summary of num missions, labels, accuracy, etc.
- https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2281 for adding badges to dashboard
