### ISSUE TITLE
Provide more information about labels on validation interface

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1392]
From #1384. There might be extra pieces of information that we might want to give users (severity, description, temporariness). 

> 7. What do we do about validating 'temporary' problems like this? Should we somehow show that a problem has been flagged as temporary (and hopefully this label was given that flag):
> 
> ![image](https://user-images.githubusercontent.com/1621749/51280017-6c566900-1993-11e9-9874-825b937b7957.png)

> Do we want to show any 'Description' notes left for the label to provide context?

> In addition to description, do we want to include severity? Do we want to validate severity?

**Comment by jonfroehlich** [comment]
I still think this is important because I have a hard time evaluating the correctness of some labels without knowing what the user was thinking--so, I'd like to see if they added comments, etc.

For example, this one:

![image](https://user-images.githubusercontent.com/1621749/54282778-f23cfd80-4559-11e9-8696-a83647fea221.png)

I've zoomed in and hidden the label and it's not clear why this surface problem exists unless it's just marking that the sidewalk is brick--which *is* a surface problem.

**Comment by misaugstad** [comment]
we have a newer issue for this (#1542)
