### ISSUE TITLE
Update cursors on validation interface

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1393]
From #1384:

> 5. Need to change the cursor to a hand when the cursor is over the GSV window (just like when you label) to indicate that you can pan:
> 
> ![image](https://user-images.githubusercontent.com/1621749/51271113-87b57a00-197b-11e9-9757-e3c839a7fae8.png)

> 6. If you mouse over the label right now, the cursor changes to a hyperlink finger-hand; however, nothing happens when you click.
> 
> ![image](https://user-images.githubusercontent.com/1621749/51271146-9f8cfe00-197b-11e9-9470-f0557bfa1c4d.png)

**Comment by misaugstad** [comment]
So what should the cursor look like when you are hovering over the label?

**Comment by aileenzeng** [comment]
@jonfroehlich made this comment on #1391:
> Second, I still think something like a mouseover (e.g., mouseover GSV and label hides) is our most promising solution (though isn't super discoverable so would have to train users)

I was thinking we could leave it as the hand if we hid the label on mouseover (so the same cursor as what we have when we hover over the GSV Panorama). Open to other suggestions too!

**Comment by jonfroehlich** [comment]
1. When you mouseover the GSV pane, the cursor should change to an open hand. When you click to pan, the cursor should change to a closed hand

2. When you mouseover the label, perhaps we just ignore the mouseover and keep the cursor as it is for (1) above.

**Comment by misaugstad** [comment]
Okay this turns out to not be as simple as it seems. GSV seems to have those cursors set and doesn't have options to change them (but of course they have options to change them in Google Maps, Google Earth, etc).

On the audit interface we are just changing the cursor in the CSS... I've tried setting the cursor in every place I can think of but GSV seems to be overriding that cursor :pensive: The audit page code is pretty complex so I am having a really hard time figuring out what exactly is being done there that I haven't done here.

I really don't want to spend any more time on this, so I'm going to stop working on it. Maybe someone w/ more experience w/ front-end dev can figure out what's going on? Or someone who is willing to put in more time than I am :grin:

**Comment by misaugstad** [comment]
@hoominchu I took a look, and at some point this at least mostly resolved itself, it seems?? The cursor looks correct in most cases for me on /validate. The only thing that still seems incorrect is when we mouse of the label icon, it switches to a pointer, but we should keep it as the open hand!

**Comment by jonfroehlich** [comment]
@hoominchu shared this video on Slack but not in his PR:

https://user-images.githubusercontent.com/1621749/195852346-c682ed80-4415-47dc-962d-e90259026a34.mp4

I just want to make sure we are all on the same page. This video shows the regular arrow-based cursor until the mouse goes over label, then converts to a hand and a grasped hand for panning.

However, we want the cursor to immediately show as an ungrasped hand as soon as it enters the GSV pane. Maybe something funky was happening with window focus (that we can't tell from the video).

So, to be clear:

Whenever mouse is over the GSV pane, it should show an ungrasped hand except for two conditions:
- you are panning (e.g., mouse is dragging)
- you are over the "hide label" button
