### ISSUE TITLE
Just Finished a Mission But Not Given Another One

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#142]
I just finished a mission and got the 'Mission Completed' pop-up but when I clicked OK, I was not given another mission and my progress bar says 100%. However, I can see that a red route was added...

![image](https://cloud.githubusercontent.com/assets/1621749/16288671/75f6bc4a-38bc-11e6-93e8-73c2a391ecfc.png)

**Comment by jonfroehlich** [comment]
I've been continuing this mission to see what happens. The progress bar is not updating but everything else seems fine.

![image](https://cloud.githubusercontent.com/assets/1621749/16288927/b29ee7ba-38be-11e6-8321-a5460f4a6816.png)

**Comment by jonfroehlich** [comment]
OK, I keep labeling and it looks like my labels are being saved (according to the map in my dashboard) but my missions are not updating.

I'm currently at 3rd and N:

![image](https://cloud.githubusercontent.com/assets/1621749/16289173/e8d423b6-38c0-11e6-86d4-3cc436e336f4.png)

@kotarohara, any idea what's going on here? Can you look at user logs? 

Here's a screenshot of my dashboard.
![image](https://cloud.githubusercontent.com/assets/1621749/16289220/2bffaeee-38c1-11e6-890a-e7908539fec6.png)

![image](https://cloud.githubusercontent.com/assets/1621749/16289234/50e97ef6-38c1-11e6-8d12-a9e870087125.png)

**Comment by kotarohara** [comment]
Can you copy the error log from the console?

**Comment by jonfroehlich** [comment]
Here's the log file, created by right-clicking in the console and selecting Save As...
[sidewalk.umiacs.umd.edu-1466646905301.log.txt](https://github.com/ProjectSidewalk/SidewalkWebpage/files/329056/sidewalk.umiacs.umd.edu-1466646905301.log.txt)

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/1621749/16289576/346c5674-38c4-11e6-9e28-4ea59a872e23.png)

I'll keep the window open just in case you want me to try other things. I sure hope I get credit for all these labels: 14 surface problems, 7 missing curb ramps, and even 5 obstacles! :)

**Comment by kotarohara** [comment]
I think the problem was three-fold.
- There was a bug in transitioning to the next neighborhood when you are done with all the missions, which should be fixed.
- 100% missions were missing; when the neighborhood had 4.3 miles of streets and you've finished 4 miles, you couldn't do 0.3 miles.
- **Error 503:** I think you hit the timing when the server was down when I was deploying the app. I asked UMIACS staff to enable Apache load balancer so I can run two app processes. This will allow us to kill one app process while upgrading, once the upgrading is done kill another and upgrade the second one.

I'm closing it for now.
