### ISSUE TITLE
Add "Start Validating" button to menubar

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1420]
In our meeting yesterday, we discussed adding a 'Start Validating' button to menubar just after the 'Start Mapping' button. I wonder if it should be 'Start Validating' or 'Start Validating Labels'

![image](https://user-images.githubusercontent.com/1621749/52008063-ae4bd880-2484-11e9-8eed-44d6dc4d6b86.png)

**Comment by aileenzeng** [comment]
I'm taking a small breather and decided to work on this for a bit. I'm also addressing #1429 since they are very similar.

Normal - no hover
![image](https://user-images.githubusercontent.com/25534091/52244211-61577000-2891-11e9-973e-3f8881230908.png)

Here's what it would look like if I hovered over all four buttons at the same time:

Option 1: Validation button is orange (all others are the same)
![image](https://user-images.githubusercontent.com/25534091/52244138-0e7db880-2891-11e9-8999-da7f504e53e1.png)

Option 2: Validation button is orange, labeling guide/results are green
![image](https://user-images.githubusercontent.com/25534091/52244171-3240fe80-2891-11e9-9d38-ff2fae1f3ad0.png)

Option 3: All buttons stay yellow
![image](https://user-images.githubusercontent.com/25534091/52244314-feb2a400-2891-11e9-95db-127e08a03315.png)

**Comment by jonfroehlich** [comment]
I think stick with the current no hover (all white) and hover (yellow) approach.

**Comment by misaugstad** [comment]
closing via #1448
