### ISSUE TITLE
Newberg Deployment: Joan Austin University 21% Complete but No Labels?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1461]
This is confusing. How could the Joan Austin University region be 21% complete but have no labels? Possible bug?

![image](https://user-images.githubusercontent.com/1621749/52448506-01f39d00-2ae9-11e9-97e1-1ec207502834.png)

Looks like other regions have the same bug:

![image](https://user-images.githubusercontent.com/1621749/52448696-90681e80-2ae9-11e9-99cb-177ef7427dbf.png)

**Comment by misaugstad** [comment]
This is because the clustering is not being run on the servers right now b/c the necessary Python libraries are not installed in our Docker containers (#1134 ). I have had a recent email thread with @mechanicjay where he has now added Python 2.7 and pip to the Docker images. And I am in the process of getting the necessary Python libraries for clustering onto the servers.

The lack of clustering on the servers is the issue b/c the /results viz uses clustered attributes instead of labels.

**Comment by jonfroehlich** [comment]
Neat. Glad that the /results viz uses clusters (this is the right approach!). Let's keep this thread open until @mechanicjay has finished integrating Python support so we can test this...

**Comment by jonfroehlich** [comment]
I just checked the page again but it's still broken. What does your process for getting the necessary python libraries involve? Is this all on you or does it require Jason's help too?

**Comment by misaugstad** [comment]
1. I want @aileenzeng and possibly someone else to do a final test of the Docker dev environment PR (#1364) before I merge it.
1. I want @athersharif to then make a PR that auto-installs the Python libraries using the Dockerfile (this PR will also add a requirements.txt file that has all the Python libraries to be installed).
1. Once that works, I will ask @mechanicjay to do the same thing for the Dockerfiles we use on the servers.

Then we should be good :grin:

**Comment by misaugstad** [comment]
@mechanicjay has got the Python libraries on the servers! Clustering is now being run and we can see stuff on the results page:
![results-newberg](https://user-images.githubusercontent.com/6518824/53779853-a71a4f00-3eb6-11e9-8b42-be6e4e9281ad.png)
