### ISSUE TITLE
Make it more clear which part of Seattle metropolitan area is not auditable

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1551]
We should make it more clear which part of Seattle metropolitan area is not auditable (by setting the non-auditable parts to darker gray or something while maintaining translucency).

![image](https://user-images.githubusercontent.com/1621749/54279299-f8c77700-4551-11e9-8943-4a5540d329a3.png)

**Comment by jonfroehlich** [comment]
Update: the results page does this well:

![image](https://user-images.githubusercontent.com/1621749/54281306-a76db680-4556-11e9-8d57-81483a602135.png)

**Comment by misaugstad** [comment]
How does this look? I moved the scale to start a bit darker.

![new-scale-seattle](https://user-images.githubusercontent.com/6518824/54467089-270aa980-4740-11e9-8e77-4af26d90c812.png)
![new-scale-newberg](https://user-images.githubusercontent.com/6518824/54467091-28d46d00-4740-11e9-9542-665d35d4dd82.png)

We can't do exactly what we did for the results page, since we have that entirely separate gray color for when we do not have enough data to give an accessibility rating.

**Comment by jonfroehlich** [comment]
Better but perhaps still a bit subtle. Can you change the color of the non-highlighted areas (ie, outside the Seattle neighborhood boundaries)?

**Comment by misaugstad** [comment]
Messing with the background seems more complicated... The background color comes from the mapbox style we are using across all the maps on our site. I've checked out some other possible styles (including [this one](https://www.mapbox.com/designer-maps/#minimo) that I like), but our current style seems to be the clear favorite.

But we do have the opacity to play with a bit. Here I changed the min opacity from 0.25 to 0.4. How does it look? We normally increase opacity from 0.25 to 0.75 for higher completion percentages. But we could compress that and start with a higher opacity.

**Comment by misaugstad** [comment]
Oops here is the pic

![new-opacity](https://user-images.githubusercontent.com/6518824/54469659-3d246400-4758-11e9-9358-650c8e5dbc38.png)

**Comment by jonfroehlich** [comment]
Definitely better!

**Comment by misaugstad** [comment]
closing via #1567
