### ISSUE TITLE
Slight change to validation example: "Surface problems on curb ramps should not be labeled as surface problems." 

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1586]
"Surface problems on curb ramps should not be labeled as surface problems." should change to: "Surface problems on curb ramps should not be labeled as surface problems. Instead, the curb ramp should be labeled with a curb ramp label with an increased severity." (or something similar)

![image](https://user-images.githubusercontent.com/1621749/54800243-2e3d2600-4c1e-11e9-951f-4438b27e17d8.png)

**Comment by misaugstad** [comment]
To try and shorten it a bit: "Surface problems on curb ramps should be marked with a curb ramp label with a higher severity".

**Comment by htadeusiak** [comment]
Here is what both of your suggestions would look like. I prefer Mikey's because it's shorter and I feel like it gets the same point across.

Mikey:
![Screen Shot 2019-05-20 at 3 45 00 PM](https://user-images.githubusercontent.com/33988444/58056892-9f626200-7b17-11e9-8505-3cd12a62a7d2.png)
Jon:
![Screen Shot 2019-05-20 at 3 47 35 PM](https://user-images.githubusercontent.com/33988444/58056902-adb07e00-7b17-11e9-84a0-d4e9eee137df.png)

**Comment by misaugstad** [comment]
closing via #1732
