### ISSUE TITLE
Console error: failed to get mapbox tiles

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1611]
![console-error-mapbox-tiles](https://user-images.githubusercontent.com/6518824/55575224-3e93dd00-56c3-11e9-913c-dcaf6f6291de.png)

This doesn't seem to be causing any noticeable problems, but I see this error many times in the console on the audit page. Are others seeing this console error?

**Comment by misaugstad** [comment]
Ohp I think I found a place where it _is_ causing an issue. Here is what my user dashboard looks like :worried: 

![user-dashboard-map-sad](https://user-images.githubusercontent.com/6518824/55648931-728c0280-5796-11e9-984d-46514fbc0837.png)

**Comment by jonfroehlich** [comment]
What are we looking at here? And how is the problem recognizable in this image?

**Comment by misaugstad** [comment]
Here, found an old pic of the user dashboard map for comparison. We should be seeing a map behind the outline of Seattle.

![image](https://cloud.githubusercontent.com/assets/1621749/16713733/dae183f4-467e-11e6-9b9c-216ac30d5d3b.png)

**Comment by misaugstad** [comment]
Oh interesting this is only happening for Seattle, not Newberg or DC.

**Comment by jonfroehlich** [comment]
It can get even worse. For example, this user dashboard shows nothing for the map:

![image](https://user-images.githubusercontent.com/1621749/56149950-8d166680-5f62-11e9-96b6-b7ab09304896.png)

`1012@2x.png:1 GET https://a.tiles.mapbox.com/v4/kotarohara.8e0c6890/11.5/466/1012@2x.png?access_token=pk.eyJ1Ijoia290YXJvaGFyYSIsImEiOiJDdmJnOW1FIn0.kJV65G6eNXs4ATjWCtkEmA 404 (Not Found)`

**Comment by htadeusiak** [comment]
Is there any other places besides the user dashboard where this has been causing problems. I've edited the default zoom level. It fixed the dashboard map and seemed to get rid of all but one the console error. 
Before:
<img width="1440" alt="Screen Shot 2019-04-20 at 5 26 43 PM" src="https://user-images.githubusercontent.com/33988444/56463867-c51e0f00-6391-11e9-8138-89450789224b.png">
<img width="1437" alt="Screen Shot 2019-04-20 at 5 26 29 PM" src="https://user-images.githubusercontent.com/33988444/56463868-c64f3c00-6391-11e9-97f8-19d72693a5e5.png">
After:
<img width="1440" alt="Screen Shot 2019-04-20 at 5 29 07 PM" src="https://user-images.githubusercontent.com/33988444/56463870-cd764a00-6391-11e9-8098-0eb6f0d548df.png">
<img width="1440" alt="Screen Shot 2019-04-20 at 5 28 33 PM" src="https://user-images.githubusercontent.com/33988444/56463871-cf400d80-6391-11e9-880c-9d94c571e43a.png">

**Comment by misaugstad** [comment]
Those were the two places I saw. Did you change the default zoom from a non-integer to an integer? Because we did specifically change it to a non-integer recently on purpose (#1602, PR #1603) which is probably what is causing the problem.

Maybe the problem is that we are using an older version of Leaflet on the user dashboard and audit page than on the landing page..? I know that non-integer zoom was introduced in a later version of Leaflet.

**Comment by htadeusiak** [comment]
I changed the default level to 12.0. I believe the zoomSnap is not working then. Because I can only zoom in 7 times when I should be able to zoom in 14 times. This means that zoomSnap should be set to 1, but in the code we actually have ```zoomSnap=0.5```. If you look at the gif with default level 11.5, you see my zoom in 8 times, and then the map appears when I hit the max zoom(19). I tried 19 as a double and I still get the same errors. I will look into another solution then.
![tests](https://user-images.githubusercontent.com/33988444/56464268-63ae6e00-639a-11e9-8995-a01f174124aa.gif)

**Comment by misaugstad** [comment]
Does the zoomSnap param seem to be working on the landing page?

Ok I believe my suspicions have been confirmed. Fractional zoom was introduced in Leaflet version 1.0.0 I think. In the console if you run `L.version` in the console, you will get 1.0.2 but on the user dashboard it is 0.7.2. Looks like we need to upgrade out leaflet version on the anywhere it is not above 1.0.0.

**Comment by htadeusiak** [comment]
On it

**Comment by htadeusiak** [comment]
We are using Leaflet's version 0.7.2 on this page. However, we recently started using fractional zoom which allows us to use values like 0.25, 0.5, etc. instead of integers. We are using fractional values for the default, min and max zoom levels and therefore requires us to update Leaflet to version 1.0+. Not running this later version is causing the console error and missing map on the user dashboard.

I was able to update to Leaflet version 1.0.2 by using a script tag I added into the pages html fixing the original issue. However, a new bug emerged with the labels on the map. The labels didn't appear to have any color to match the label type (Green for curb ramps, red for missing curb ramps, etc.) instead they appeared almost transparent. You can barley see them in the map below.
<img width="1240" alt="Screen Shot 2019-04-28 at 11 28 38 PM" src="https://user-images.githubusercontent.com/33988444/56879482-cabcca00-6a0d-11e9-8c1e-2561b085c78d.png">

This is what I have found relating to this new issue. 

We create the labels for the leaflet map in the 'Progress.js' file.
The is the geojsonMarkerOptions variable which holds the default options for each label:
```
geojsonMarkerOptions = {
                radius: 5,
                fillColor: "#ff7800",
                color: "#ffffff",
                weight: 1,
                opacity: 0.5,
                fillOpacity: 0.5,
                "stroke-width": 1
            };
```
We then change the color depending on label type and add it to the map in the function below:
```L.geoJson(data, {
                pointToLayer: function (feature, latlng) {
                    var style = $.extend(true, {}, geojsonMarkerOptions);
                    style.fillColor = colorMapping[feature.properties.label_type].fillStyle;
                    return L.circleMarker(latlng, style);
                },
                onEachFeature: onEachLabelFeature
            })
                .addTo(map);
```
When testing with Leaflet version 1.0.2, I was able to change the radius of the labels but nothing else.
Example with radius => 20:
<img width="1263" alt="Screen Shot 2019-04-28 at 11 31 09 PM" src="https://user-images.githubusercontent.com/33988444/56879480-c7c1d980-6a0d-11e9-8cbe-9010b34c8ce8.png">

This is where I got stuck, I wasn't sure why I was only able to change the radius for the labels and not color or opacity. I tried looking on Mapbox and Leaflet's websites on how to edit the color of circleMarkers with the updated version. I also tried to see if they had changed any of the label option's names. But, they recommended the same code we have been using.

There could be some CSS that is potentially overriding what ever style we give the labels besides radius. However, I'm not sure where to find CSS that would be affecting the labels as we directly edit the style for each one and then add it to the map in the javascript file.

I also found the way we were sourcing leaflet and mapbox confusing. The parts of the site that were running Leaflet 0.7.2 had 'mapbox.js'. The parts that were running 1.0.2 were using these script tags:
```
<script src='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css' rel='stylesheet' />
<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-zoomslider/v0.7.0/L.Control.Zoomslider.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-zoomslider/v0.7.0/L.Control.Zoomslider.css' rel='stylesheet' />
```
There are also 'leaflet.js' and 'leaflet-omnivore.min.js' files in the javascript/lib but they don't appear to be used.

I think it's best if we have someone new take a look at this issue. But of course if you would like me to keep going on this issue I can.

**Comment by misaugstad** [comment]
Thanks for all the effort on this one @htadeusiak! And thanks for the full dump of current status on the issue. We will get someone else on it :)

**Comment by misaugstad** [comment]
closing via #1701
