### ISSUE TITLE
Validating in Seattle but got DC labels (from tutorial)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1636]
I am currently validating in Seattle but I got the following label to validate--which is from the tutorial (I double checked and the cross streets are in Cleveland Park). Is this on purpose so that we can use it to help validate validators?

![image](https://user-images.githubusercontent.com/1621749/55998065-92796580-5c71-11e9-9404-88b6ebf67dd7.png)

![image](https://user-images.githubusercontent.com/1621749/55998078-9c9b6400-5c71-11e9-9088-3378a2c9896d.png)

**Comment by aileenzeng** [comment]
Hmmm.. This is doesn't seem to be intended behavior (we have a check in our query that is supposed to filter out all tutorial labels). If you run into this again, could you run this command in your console and include the label ID?:

```
svv.panorama.getCurrentLabel().getOriginalProperty("labelId");
```

Something else that's also interesting is that this curb ramp label isn't at the POV that we expect either, since this label was placed from a different POV.

**Comment by misaugstad** [comment]
The way the tutorial works is that it is attached to that street edge in DC. So I just keep that one street edge in DC in the database and add it to one of the neighborhoods. So yeah that one street is still being audited but I figured it wasn't a huge deal :grin:

**Comment by misaugstad** [comment]
To elaborate now that I am back from vacation and not on my phone: due to the architecture of the website, we need to have the tutorial associated with a street edge id, so I included the DC tutorial street edge in all the databases. To make it so that users did not have to actually audit this street, there is code that would have to be changed/written, and edge cases would have to be dealt with in a few places in the code. I made the determination that this added complexity was not worth it, and that it would be preferable to just have this one street from DC in the database being audited by users. I don't expect your average user to notice.
