### ISSUE TITLE
Label Stickiness in GSV Pane Broken in Firefox and Safari

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1644]
https://youtu.be/dji9A0A5hzk

I didn't have a chance to test it in the actual labeling interface but clearly broken in the validation interface on Firefox.

**Comment by Krocketeer** [comment]
Labeling and validation interface also has similar behaviors in Safari - labels don't stay when dragging around the map.

**Comment by misaugstad** [comment]
What I've seen on Firefox is that the stickiness works on the audit page but not on the validate page.

**Comment by aileenzeng** [comment]
Yep - we use our own custom code for sticking labels onto Panos (although it looks very closely related to what PanoMarkers use). I haven't done any digging to see what these exact differences are yet. For the validation interface, we have just been using the PanoMarker API since that was a lot simpler to implement. Probably means that there's a bug in the PanoMarker code then, so this might be kind of tricky to fix (eek!).

**Comment by misaugstad** [comment]
yikes :sob: we should check PanoMarkers repo to see if such an issue is logged there

**Comment by aileenzeng** [comment]
Oh wow! An issue is logged here (and with a fix in the comments!) https://github.com/marmat/google-maps-api-addons/issues/36. We can check to see if this works on Safari too. I'll try this out now.

**Comment by jonfroehlich** [comment]
Ugh, oh no, and I was hoping we could use the PanMarker code to enable the auto-resizing the audit window (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/303) and to support the mobile interfaces (which will clearly have different window sizes)

**Comment by misaugstad** [comment]
Oh my goodness, fingers crossed!!
