### ISSUE TITLE
Add validation columns to Label table in admin interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1658]
Can we add the three validation columns to the Label table in the admin interface (Agree, Disagree, Not Sure) where each column is a count. This is particularly important as the mturk deployment draws near.

![image](https://user-images.githubusercontent.com/1621749/56441685-ba388100-62a2-11e9-81b8-d3f95e580164.png)

**Comment by misaugstad** [comment]
This should also be added to the label search tab!

**Comment by misaugstad** [comment]
@leonli33 could you add these? You should be able to find an example of how to get that data elsewhere on the admin page, since the "Label Search" tab has that data (image below)
![validation-counts-label-search](https://user-images.githubusercontent.com/6518824/77834259-afb47780-7100-11ea-937b-c03c050c8d80.png)

Ideally we don't require horizontal scrolling and that it doesn't look too cluttered. It might help to change the column title "Temporary?" to "Temp?". You might want to just remove that column honestly, I think it's the least important column.

**Comment by misaugstad** [comment]
closing via #2058
