### ISSUE TITLE
Add 'parked bike' to obstacle tag--particularly important for cities with bike share

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1691]
![image](https://user-images.githubusercontent.com/1621749/56824257-cbd1d980-680a-11e9-885e-1a6652b487fb.png)

**Comment by misaugstad** [comment]
is it worth including the word "parked" here, or would "bike" suffice? I think the word parked is important for cars b/c you see so many of them driving, but idk about for bikes.

**Comment by jonfroehlich** [comment]
I agree that bike is fine and better than what I proposed

**Comment by misaugstad** [comment]
@htadeusiak I assigned this one to you. Should be super easy because you can look at the following PRs that add other tags and follow that model: #1521 #1580

**Comment by jonfroehlich** [comment]
Hmm, I've been thinking about this and we don't want our users to tag people riding on bikes as sidewalk obstacles, only parked bikes. So, I think "parked bikes" is still the best term.

![image](https://user-images.githubusercontent.com/1621749/57201205-a0599800-6f4a-11e9-9258-30ce558f8d94.png)

**Comment by misaugstad** [comment]
I still think that this isn't a big deal, since we don't see ppl riding bikes that often in GSV (unlike driving cars, which are everywhere). But @macallmcqueen made a good point that we might as well keep the parallel structure with "parked car". We aren't that pressed for space right now, so "parked bike" is good. We can always remove it later if we end up in danger of spreading our tags to a third line :)
