### ISSUE TITLE
The auto-cropper is broken in Seattle

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1708]
@galenweld found that the auto-cropper is not working in Seattle. @tongning investigated and found that the panos in Seattle are a different size; he updated the pano scraper accordingly but the cropper, it appears, is still not working for Seattle panos.

Forgive me if this is captured somewhere else. I couldn't find it on my quick search. And this is important enough to flag it again because we absolutely need it for CV training.

**Comment by galenweld** [comment]
@tongning and I have spoken briefly on this topic and are going to discuss further. I'm also going to continue to work on this; now that I have more time (with paper submitted), I would like to spend some of it reverse engineering the depth-proportioned code and the different coordinate systems used so that I can better understand how things work, and thus debug them. Once I'm done with that, maybe I can write up my findings succinctly to save future Galens and Anthonys the trouble of doing the same, a few years down the road.

**Comment by jonfroehlich** [comment]
Hi all, any updates on this?

**Comment by misaugstad** [comment]
Would anyone be able to at least point to where this code is located and possibly get @KaviMD up to speed on this?

**Comment by galenweld** [comment]
Since this issue was initially discovered while working on CV projects, the code that was being used is in that repo (galenweld/project_sidewalk_ml/) although it was derived from code in ProjectSidewalk/sidewalk-panorama-tools. The key function that isn't working is `bulk_extract_crops` in https://github.com/galenweld/project_sidewalk_ml/blob/master/GSVutils/utils.py. 

I also created a jupyter notebook that I've been using in my attempts to debug this issue, that's at https://github.com/galenweld/project_sidewalk_ml/blob/master/new_cities/make_centered_null_csv.ipynb. 

I am happy to try and get @KaviMD up to speed on this, but it's definitely complex and sort of tricky - I don't want to block anyone, but it might be easier for us to work together in person.

**Comment by tongning** [comment]
Kavi and I had a quick sync over Hangouts last night and I believe he now
has the link to Seattle scrapes, some Seattle test data, and perhaps a
general understanding of what the code in the sidewalk-panorama-tools repo
is doing. I hope this is enough to get started but I do agree it's a
complex issue that may benefit from more face time.

**Comment by galenweld** [comment]
Update for Kavi and anyone reading this in the future: my earlier debugging work is here: https://github.com/galenweld/project_sidewalk_ml/blob/master/new_cities/seattle_debug/coords_debug.ipynb

**Comment by KaviMD** [comment]
What I figured out is that when sv_x and sv_y are calculated on the Project Sidewalk Webpage, it assumes that the size of the image is 13312x6656 (the smaller resolution used everywhere but Seattle). Because of that, when the labels are drawn on the Seattle image (with a larger resolution of 16384x8192), they are in the wrong places.

The simple "band-aid" solution is to scale sv_x and sv_y **before** they are used to calculate the x and y location of the point in the panorama. Both sv_x and sv_y need to be multiplied by 16384/13312 or ~1.2307692308. This effectively increases the scale to match the Seattle image.

A slightly better and more permanent solution might be for the Project Sidewalk Webpage to take into account a panorama's width and height in the _canvasCoordinateToImageCoordinate_ in _UtilitiesPanomarker.js_

This is a list of the variables used in calculating the x and y location of a label and what I think they represent:

- sv_x: The distance of a label from the true north on the X axis in pixels. It ranges from -(imgWidth/2) to (imgWidth/2) where 0 is true north
- sv_y: The distance of a label in pixels from the horizon. Above the horizon is positive and below is negative. It ranges from -(imgHeight/2) to (imgHeight/2) where 0 is the horizon.
- ph (Photographer Heading): In degrees, the angle distance from the direction the photographer was facing to true north
- h (Heading): In degrees, the angle distance from true north to the point.

**Comment by galenweld** [comment]
This is great, @KaviMD, thanks so much!

To clarify one thing (based on my discussion with Kavi in person): the above fix of scaling the `sv_x` and `sv_y` by a constant factor of ~1.23 still requires the global variables `sv_image_width` and `sv_image_height` which are used both in the CV repository as well as in ProjectSidewalk/sidewalk-panorama-tools to be set to the correct resolution of the panoramas being used.

**Comment by jonfroehlich** [comment]
From https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1708#issuecomment-505623474:
> A slightly better and more permanent solution might be for the Project Sidewalk Webpage to take into account a panorama's width and height in canvasCoordinateToImageCoordinate in UtilitiesPanomarker.js.

Yes, I agree. This should be incorporated into the core system for a robust fix (and these vars should possibly be stored in the backend database as well). @misaugstad should comment.

This is a *high* priority issue because assuming our ASSETS'19 CV paper gets accepted, we want to be pushing hard on trying to incorporate Seattle into the CR.

**Comment by galenweld** [comment]
> This is a high priority issue because assuming our ASSETS'19 CV paper gets accepted, we want to be pushing hard on trying to incorporate Seattle into the CR.

Agreed, however this doesn't need to be fully resolved before the camera ready. @KaviMD's temporary "scaling" fix is more than enough for us to easily produce Seattle crops and train a model(s) using them.

**Comment by misaugstad** [comment]
This is great work!!

>A slightly better and more permanent solution might be for the Project Sidewalk Webpage to take into account a panorama's width and height in canvasCoordinateToImageCoordinate in UtilitiesPanomarker.js.

I'd like to assume the pano's width and height are things we can easily determine? Are we provided with that metadata via the GSV API?

**Comment by galenweld** [comment]
That's probably a better question for someone who's more familiar with the Project Sidewalk website code itself. This is bit tricky because the `SV_x` and `SV_y` are computed when the label is placed by a crowd worker, and their crop is made from a pano (of a potentially different size than the pano displayed to the user in the web interface). So perhaps some more scheming is needed to think about what is the optimal strategy going forward.

**Comment by jonfroehlich** [comment]
@KaviMD can you tell if the depth data is also higher resolution in Seattle?

**Comment by KaviMD** [comment]
The depth data for is the same resolution as in DC (256, 1536). I don't have any Newberg images so I couldn't test those...

**Comment by jonfroehlich** [comment]
@galenweld could you send @KaviMD some Newberg data so he can test those as well.

**Comment by galenweld** [comment]
Sure thing. We're gonna go over this in person when we meet up in a few
minutes.

**Comment by KaviMD** [comment]
I just checked the Newberg depth data; it's the same resolution as Seattle and DC

**Comment by misaugstad** [comment]
This is being addressed in #2485
