### ISSUE TITLE
Show current audit's labels when returning to audit page

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#1737]
In PR #1724 when users return to the audit page they are now dropped back in the same location they were when they last left the audit page, allowing them to resume a street that they had started auditing. However, the labels they had placed on this street the last time they were on the audit page do not show up on the mini map or panoramas. It shouldn't be _too_ hard to get them on the mini map, and I think we should do that at least. I think it is less important that we add the labels back onto the panos, but would definitely like to have it.

We should decide whether we just want to include labels from the street they are currently auditing, or all previous streets they've audited in the neighborhood. We've seen feedback from users saying they would like all their past labels shown on the mini map so that they know if they've labeled an intersection already. But maybe we want users to label intersections multiple times :) And there may end up being performance problems for users who have placed hundreds of labels in a neighborhood.

**Comment by misaugstad** [comment]
As of #1757 the labels are now shown on the mini map. The only thing we are missing is for the labels to be shown on the panos and be editable (the hardest part).

**Comment by jonfroehlich** [comment]
Maybe start by having them show up in the panos and then a second Issue could be opened to make them editable?

(For example, non-editable labels showing in the panos could have a black outline around them)

**Comment by ThatOneGoat** [comment]
So I was reading @htadeusiak 's comments on the completed PR for #1757 and it seems like he was able to get the Panomarkers onto the pano upon refresh then it was decided that we wouldn't place visible labels because those labels (and the panomarker) wouldn't be editable. 

In that case, am I just trying to do what @htadeusiak did and physically show a label in the pano, or was there some blocking feature that would prevent us from making the label editable in a future PR because of the aforementioned implementation where I would have to look at a different way to show a label on the pano for previously placed markers?

**Comment by misaugstad** [comment]
I think the issue was that we don't use PanoMarkers on the audit page (though we do on the validation and admin page). So if we want to make labels editable in the future, we would have to write completely new code to make them editable. Like it would be adding a sort of copy of all the code to show labels as PanoMarkers.

So what I think we want to do is use the current label infrastructure instead. I think this requires making some smaller edits to make the current code more generalizable. Which is preferable to adding PanoMarkers. Let me know if that was unclear :sweat_smile:

**Comment by ThatOneGoat** [comment]
Ah I see, I didn't realize that the labels we place on the panos during auditing are different than the Panomarkers we see in validation (I thought they were all Panomarkers). 

I'm still not quite sure what you mean though by current label infrastructure. It might be because I'm misunderstanding the label infrastructure, but I thought that since we have a way to get the label data around an area (as shown by @htadeusiak in the `svl.labelContainer.miniMapLabelsInRegion` method) we could just rerender them in a sense (maybe with a new helper method). My thought was that the difficulty would be in somehow updating the label data in the database after a user potentially updates an old label from a past auditing session they just resumed.

**Comment by misaugstad** [comment]
>My thought was that the difficulty would be in somehow updating the label data in the database after a user potentially updates an old label from a past auditing session they just resumed.

Yes I think that's the main issue. Though there are likely some issues with that on the front-end as well. Since everything on the front-end is assuming you placed the label during this session. Rendering should be relatively easy, you just also need to record that it is an old label on the front-end and keep track of that until you send it off to the back-end.
