### ISSUE TITLE
Repeating Validation Labels Bug

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1795]
During one validation mission, I kept going back and forth between two labels. When I showed Jon, he said that he had literally just labeled those labels a minute ago and that he should not show up because he has already passed the number of validated labels we are aiming for.

Screen Recording:
https://youtu.be/35G_fFofvHE

**Comment by jonfroehlich** [comment]
So, right: this captures two potential bugs:

- first, and most critically, @daotyl000 got stuck in an infinite validation loop
- second, and strangely, @daotyl000 shouldn't even be seeing my labels because with the new validation prioritization scheme (just pushed to production), I should likely be deprioritized for validations... right?

**Comment by daotyl000** [comment]
I just started another validation mission and it has brought me back to the same validation mission I've done before. Same labels in the same order.

**Comment by misaugstad** [comment]
very very odd... have you tried refreshing the page yet?

**Comment by daotyl000** [comment]
After those two occurrences, it stopped happening by itself. I didn't refresh or do anything different.

**Comment by nchowder** [comment]
Happened to me:
https://streamable.com/7ga21

**Comment by jonfroehlich** [comment]
Others are experiencing the same problem. A common symptom is seeing a very recently applied label--that is, a user during hackathon applying a label and it quickly showing up somewhere else on a different user's machine who is doing validations. @nchowder just saw this too.

**Comment by jonfroehlich** [comment]
Just got this bug. Was not doing validations as part of main mission flow (had selected validations from menu).

**Comment by jonfroehlich** [comment]
Just got it again and started video recording: https://youtu.be/lmlBk83c8d0. I also opened console but nothing.

Watch carefully: I was clicking 'Disagree' and the mission complete percentage goes up but I keep getting the same scene/label for validation. Then I clicked on 'Skip' and the application froze (still frozen after ~8 mins).

**Comment by jonfroehlich** [comment]
OK, I think I have a way of replicating this.

- Load Project Sidewalk
- Click on 'Start Validating'
- Do the three validation missions
- At the end of the third validation mission, click the continue button. You will be taken to an *audit* mission.
- When the audit mission starts (even at the 'Mission Start') screen, click the 'Start Validating' button on the menubar
- You will then be taken back to validations but you'll immediately start to see the repeat bug (that is, the same set of labels to validate over and over again)

**Comment by misaugstad** [comment]
this should actually also be fixed by PR #1811. you may notice that all the repeat label bugs happened with the obstacle label type! the issue was that there were only 1 or 2 obstacle labels that had not yet been validated. and the code had a bug in it where we would _only_ get labels that had not yet been validated at all, even if it meant repeating them.

we haven't seen the bug in the last few days because people have only been validating and not auditing.

**Comment by misaugstad** [comment]
closing via #1811
