### ISSUE TITLE
Should we make the default branch 'develop' rather than 'master'?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2257]
Hey @misaugstad, given that we want all of our dev work to branch off of 'develop' and only use 'master' to push to production, should we set our default branch to 'develop' (or would that cause strangeness with @mechanicjay's deploy hook stuff?).

https://docs.github.com/en/github/administering-a-repository/setting-the-default-branch

(This should really be a Slack discussion but marking it here).

**Comment by misaugstad** [comment]
Hmm I guess this could have some benefit to newcomers, since we want them to be branching off of develop every time, and almost all PRs should be going into develop... Not sure if this messes up the webhooks.  Probably not? Pushes to the develop branch cause the test servers to rebuild. But a new release causes the prod servers to rebuild, so the prod webhooks shouldn't be effected at least.

**Comment by mechanicjay** [comment]
The autodeploy stuff only cares about the name of the branch.  The 
defaultness of the branch should be inconsequential.

**Comment by jonfroehlich** [comment]
Great. Thanks @mechanicjay. I think it would be best to make 'develop' default then. I don't see any problems with doing that, and I think it will cut down on accidental commits and PR requests to 'master.' If you're cool with this Mikey, I'll make the change.

**Comment by misaugstad** [comment]
Yeah go for it... I will hold my breath!

**Comment by jonfroehlich** [comment]
Tis done!

![image](https://user-images.githubusercontent.com/1621749/94194949-43c08b00-fe67-11ea-99be-1285618f3928.png)
