### ISSUE TITLE
Reducing the number of clicks for labeling

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#226]
Currently, for every label, there is a minimum of four clicks (1. Click on type of label 2. Click the interface 3. Click for rating 4. Click for comments (optional) 5. Click for closing the box). This could be reduced. For e.g. automatically closing the labeling/comment box when return-key is pressed.

**Comment by jonfroehlich** [comment]
I agree that this is a problem. We've discussed this quite a bit but have not found a particularly good solution.

Note: although admittedly very few users will probably discover our keyboard shortcuts (because we don't actually teach them about this feature), I actually click only once for every label (1. click to place label) because I use the keyboard shortcuts for:

- Selecting the label type (e.g., type 'c' for selecting curb ramp)
- Selecting the rating (e.g., once the pop-up dialog is open, use the numbers to select the rating)

You do not need to click to close the box but I agree that most users will do that. Note: @kotarohara is implementing 'enter' keypress to close the dialog box.

**Comment by jonfroehlich** [comment]
I think part of the solution here is actually in training people to use a keyboard--maybe in onboarding or during their first mission.

**Comment by Soben713** [comment]
Part of this will be solved by #219 (Hit enter to close the context menu) and #287 (Make keyboard shortcuts feature more visible to the user). I think we can keep this issue open for now to discuss other possible solutions but I am going to remove it from Public Deployment v2 until we agree on better solutions.

**Comment by misaugstad** [comment]
I think that we've addressed all parts of this to the extent that is necessary. Enter now closes the dialog box. Keyboard shortcuts close the context menu. Choosing a new label closes the context menu. Panning closes the context menu. We have keyboard shortcuts for choosing a label type, rating severity, and tagging. And we have added more training to encourage users to use keyboard shortcuts if they are so inclined. I don't think there's anything else for us to really do for this!
