### ISSUE TITLE
In userProfile.scala.html, not clear where to calculate countNumOfLabels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2266]
I was expecting to see a higher-level "class" that encapsulates a user and their contributions/activity.   So, I went looking in UserDAOSlick.scala but that doesn't look like the right place (as this calculates stats _across_ users).

But here's what I've determined thus far. Would love to hear @misaugstad's thoughts on my approach.

I'm looking for the following stats per user id (as this is for userProfile.scala.html):

**Num completed missions**, which I can get by: `@MissionTable.countCompletedMissionsByUserId` 

**Total distance audited**, which I can get by: `@MissionTable.getDistanceAudited`

**Num validations**, which I can get by `@MissionTable.countCompletedValidationsByUserID`

**Num labels**. Here, there is no current function in MissionTable—which is fine but breaks the above consistency (so worth a discussion with @misaugstad about how the code is structured/architected). So, instead, I have to use a different table, it looks like `@LabelTable.countLabelsByUserId` Right?

**Accuracy**. I'm guessing such a method doesn't exist yet given our work on defining the accuracy calculation here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2177#issuecomment-698025554

Finally, much of the current stats appear to be loaded asynchronously using `Progress.js`. Do we still think we'll need to support asynchronous loading of these stats (i.e., because the load times would otherwise be too long)?

**Comment by jonfroehlich** [comment]
As an update, this is what I'm currently doing:

```
              <span class="ps-skyline-stats-holder-stat-number">@("%.1f".format(MissionTable.getDistanceAudited(user.get.userId))) mi</span>
                <span class="ps-skyline-stats-holder-stat-number">@LabelTable.countLabelsByUserId(user.get.userId)</span>
                <span class="ps-skyline-stats-holder-stat-number">N/A</span>
                <span class="ps-skyline-stats-holder-stat-number">@MissionTable.countCompletedMissionsByUserId(user.get.userId, true)</span>
```

Looks like this:

![image](https://user-images.githubusercontent.com/1621749/94302894-cefe5700-ff21-11ea-9bd2-effc167c60e0.png)

**Comment by misaugstad** [comment]
I do actually like the locations of most of these functions. In general, we put functions that query a certain table in the Scala file for that table. Of course, many queries join multiple tables, so there is some ambiguity here.

* I agree with `countCompletedMissionsByUserId` being in `MissionTable.scala` for obvious reasons
* I agree with `countLabelsByUserId` being in `LabelTable.scala` for obvious reasons
* I agree with `getDistanceAudited` being `MissionTable.scala`, since we are looking at the `distance_progress` column in the `mission` table
* `countCompletedValidationsByUserID` is also in `MissionTable.scala` right now, but I think that makes more sense to be in `LabelValidationTable.scala` even though we also join with the `mission` table

And I put the accuracy function in `UserStatTable.scala` because that feels thematically appropriate. But it might actually make more sense in `LabelValidationTable.scala`, since we are computing the accuracy based off of validations.

>Finally, much of the current stats appear to be loaded asynchronously using Progress.js. Do we still think we'll need to support asynchronous loading of these stats (i.e., because the load times would otherwise be too long)?

The load time seems pretty good to me right now. We'll see if things get worse as we add more stats!

**Comment by jonfroehlich** [comment]
Great, sounds good to me @misaugstad.

**Comment by misaugstad** [comment]
These are all actually in appropriate files at this point.
