### ISSUE TITLE
Tutorial: Give info on hovering over buttons

### ISSUE THREAD

**Issue by manaswisaha** [ProjectSidewalk/SidewalkWebpage#227]
Hovering over each of the buttons could give a pop-up box to tell about its functionality. This would be helpful if for some reason the user gets stuck at some point. (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/225)

**Comment by jonfroehlich** [comment]
What buttons?

Also, some buttons do have pop-up boxes (hover on the '?').

See also perhaps the most controversial and discussed issue in Project Sidewalk's history: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/78

(Note: I'm not a fan of the '?' but we have not had time to come up with a great alternative solution and now our entire focus is on deploying. So, again, unless you have a nice idea of how to implement this, we're probably not going to do this--at least not in the shortterm).

**Comment by manaswis** [comment]
Was referring to the buttons around the GSV screen e.g. jump, the labels etc.
<img width="1192" alt="screen shot 2016-09-02 at 1 07 03 am" src="https://cloud.githubusercontent.com/assets/2873216/18282044/57916500-742d-11e6-89bc-14fe64c9e75b.png">

This can be closed. It isn't very important.

**Comment by jonfroehlich** [comment]
We could certainly discuss implementing hover tooltips for the buttons.

**Comment by r-holland** [comment]
**Possibilities for left sidebar hover over text:**

I assume we want the hover over text appearing to the left, where there is blank space. All of these messages are short, as there is not much space to the left and I tried to fit everything on one line of text.

Sound:
![image](https://user-images.githubusercontent.com/19720010/27545567-1d216b96-5a5e-11e7-9a63-9292b739d01a.png)
![image](https://user-images.githubusercontent.com/19720010/27545602-37e5faf0-5a5e-11e7-892e-2415c1070e09.png)
Another possibility is showing "Mute" when sounds are enabled and "Unmute" when sounds are disabled

Jump:
![image](https://user-images.githubusercontent.com/19720010/27545188-3420615e-5a5d-11e7-916c-b03a4352a9d1.png)
![image](https://user-images.githubusercontent.com/19720010/27545346-95ea834c-5a5d-11e7-880a-270d0b90c49b.png)
![image](https://user-images.githubusercontent.com/19720010/27545263-68a88bfe-5a5d-11e7-8178-d04d1991fc3d.png)
![image](https://user-images.githubusercontent.com/19720010/27545473-e8c5b44c-5a5d-11e7-98b8-86fdbcaf9da2.png)

Feedback:
![image](https://user-images.githubusercontent.com/19720010/27544669-d6717738-5a5b-11e7-8b9d-b9c7c77be32f.png)
![image](https://user-images.githubusercontent.com/19720010/27545081-ea157400-5a5c-11e7-8d95-a975be35b84e.png)
![image](https://user-images.githubusercontent.com/19720010/27544797-3a677576-5a5c-11e7-993a-aec5d284e5ce.png)
![image](https://user-images.githubusercontent.com/19720010/27544989-a8c99332-5a5c-11e7-9efd-8341d02e4ddf.png)

Opinions on any of these wordings? Or suggestions for new text/rewording?

**Comment by r-holland** [comment]
I started this but it was pushed to after relaunch. @manaswis do we still want hover over text for thes buttons? And if so, what do you think of these hover over texts? For the sound button, I think showing "Mute" when sounds are enabled and "Unmute" when sounds are disabled is the best option. I have no real preference for the jump and feedback buttons. If we decide on some text, I can get a PR in real quick.

**Comment by misaugstad** [comment]
@tanayaxsharma our buttons have changed around a little bit since this was initially created (in 2016!!). Here are the buttons on the Explore (/explore) page that don't yet have tooltips:
* Sound: I think we are okay without a tooltip for this one
* Jump: "Start exploring somewhere new"
* Stuck: "We'll try to move you back to your mission"
* Feedback: "Share your thoughts with us"

Some notes:
* I'm assuming that you can copy the way that we add tooltips to the zoom in/out buttons for these tooltips!
* Make sure to use the translations files, though I can add the non-English translations once you create the PR

And can you do this for the Validate (validate) page as well? Here are those buttons:
* Skip: Skip this label if there is a problem with the image"
* Feedback: "Share your thoughts with us"

Some more notes:
* The Explore page translations should be in `audit.json` and the Validate page translations should be in `validate.json`. Since the Feedback button is on both pages, those should go in `common.json`!
