### ISSUE TITLE
Add in message with link to download data on results page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2298]
In the explanation portion of the Results page that starts ("Gray neighborhoods..."), I think we should include a clickable link to our API/data and encourage people to explore the data for themselves.

![image](https://user-images.githubusercontent.com/1621749/95387894-45963f80-08a6-11eb-8d18-0ded8e5c0d95.png)

**Comment by misaugstad** [comment]
I worked with @uditpatwal on this a bit yesterday. It turns out that it is really hard to add a hyperlink to a Leaflet legend. If we don't add the legend using Leaflet, and instead just have it as a standalone HTML element (like we do on /labelmap) I think the hyperlink should work just fine. So we might just want to make that move so we have more control. We should avoid doing this until the choropleth restructuring PR is merged though, to minimize merge conflicts.

And who knows, when we upgrade the Mapbox library, maybe this will be resolved anyway? So maybe best to wait until after that.

**Comment by misaugstad** [comment]
At some point we switched away from a Leaflet legend, so this will be easy to do.
