### ISSUE TITLE
Logging of clicks in navbar is incorrect

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#2347]
When we added the new Data drop down menu, I forgot to check that the logging was all working correctly. Some of the logic is bad, so we are logging `Click_module=SignOut` to the `webpage_activity` table for most items in the drop down menus. @uditpatwal can you go through and make sure you can get the correct thing logged for every navbar element? And some buttons are different on different pages (you can find that logic in `navbar.scala.html` as well), so you'll need to make sure that all the buttons work on those pages that work differently too.

**Comment by uditpatwal** [comment]
**Problems**
Currently, some of the user clicks are not being logged correctly. In the `webpage_activity` table, we are supposed to be receiving an entry following `Click_module=<button user clicked>_location=Navbar_route=<route where user was>`. However it does not always log. I think this is because the page redirects before it can send the log info to the database. I noticed that at line ~166 with the `logWebpageActivity` function, if we change `var async = true` to false, all the clicks are logged. This makes it so that we do not redirect the page until the request is *either sent to the database OR sent to the database and confirmed*. The problem is that I do not know which case this follows.


**Only have to wait until the request is sent to the database**
I do not think we have a problem because it just sends the request to the database and redirects the page!

**Have to wait for a confirmation that log is written/sent to the database**
If this is the case, then if the database is is under a heavy load, it could possibly take a long time for the user to receive the   confirmation and slow down the user experience.

**Comment by misaugstad** [comment]
I don't think that the server being under a heavy load should be something we should worry about for the most part. Ideally we could just make sure that the data was sent and then redirect before waiting for a response, but since it looks like we don't have that option, I think we should just set async to false and collect the data. 

A bigger change we could consider making in the future (though I don't think you need to worry about this now) is to allow any of our webpages to take in a query parameter that says which page they are being redirected from. That way, we can do load the page _and_ log to the webpage_activity table from the one redirect.

**Comment by misaugstad** [comment]
closing via #2361
