### ISSUE TITLE
Misalignment of SV interface image with the top-down map

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#235]
The top-down map doesn’t align with how far I am from the intersection (next or previous) on the main image screen.

<img width="1280" alt="screen shot 2016-08-22 at 11 44 11 am" src="https://cloud.githubusercontent.com/assets/2873216/17869406/228a9352-6881-11e6-98d2-bfa643a1842d.png">

**Comment by jonfroehlich** [comment]
@manaswis, what do you mean by the 'small walk screen'?

**Comment by manaswis** [comment]
Okay, found the term. I wasn't sure what to call it. Its the 'top-down map'.

**Comment by jonfroehlich** [comment]
The position of the human avatar on the top-down map is based on Google's own APIs. We do not have control of this. It should be a fairly precise representation of your location in GSV (as precise as Google's data is).

Is this what you are referring to?

**Comment by manaswis** [comment]
Ah, I see. Yes, that's what I was referring to.

**Comment by jonfroehlich** [comment]
I'm closing this because it's not a problem on our side (and I'm not sure it's really a problem... I've found that the avatar placement is perfectly fine).

@manaswis, if you have some examples documenting how you think the avatar placement is wrong, please provide them. I'm closing for now. Feel free to reopen.
