### ISSUE TITLE
Cannot Load Admin Page (Proxy Error)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2475]
Both @gari01234 and I are experiencing trouble loading the admin page on the SPGG server:

![image](https://user-images.githubusercontent.com/1621749/109649398-b74e7e80-7b10-11eb-8226-daddc8843c6b.png)

@misaugstad, this is a high priority fix because Gari needs this data to help review student work.

**Comment by jonfroehlich** [comment]
Notably, I'm not seeing this problem on Newberg but I am seeing this issue on Seattle as well. So, my guess it has to do with queries taking too long and the load cycle timing out?

**Comment by misaugstad** [comment]
Mentioned on Slack, but I messaged Jason about increasing this timeout on the Apache proxy, since that's what had caused this issue in the past. So hopefully that can resolve this in the near term. Once I implement #2474 that should also drastically speed up loading the admin page, but that likely won't be on production until at least next week.

**Comment by jonfroehlich** [comment]
Looks like it's fixed!

![image](https://user-images.githubusercontent.com/1621749/109725799-8862f780-7b66-11eb-9a46-5847f09c0959.png)

You can check too and close out.

**Comment by misaugstad** [comment]
Confirmed working, thank you @mechanicjay !
