### ISSUE TITLE
Why are some streets missing from SPGG?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2503]
I noticed that we have then neighborhood Valle Poniente marked as 100% complete:
![image](https://user-images.githubusercontent.com/1621749/111196933-17b2d680-857b-11eb-9477-d17d70ea5658.png)

However, if you look on LabelMap, you can see that there are lots of unaudited streets, especially along the southern border of the region:
![image](https://user-images.githubusercontent.com/1621749/111196888-0c5fab00-857b-11eb-946d-56ec4e966088.png)

Is this a limitation to OSM (i.e., the data is missing from OSM) or is the data missing from Google Street View? It looks like the data is in GSV:

![image](https://user-images.githubusercontent.com/1621749/111197272-83953f00-857b-11eb-8136-bdaf1d57e927.png)

**Comment by misaugstad** [comment]
@jonfroehlich if you compare those two maps, you'll see that the border we have drawn in Project Sidewalk is wider than the city limits drawn by Google. Just south of those limits, the same streets that we don't have audited also do not have GSV imagery. Showing a zoomed in version of both so you can compare the street names to see that they line up:

![Screenshot from 2021-03-15 12-49-58](https://user-images.githubusercontent.com/6518824/111212876-66696c00-858d-11eb-8ed6-6ad1e8f27b36.png)
![Screenshot from 2021-03-15 12-50-07](https://user-images.githubusercontent.com/6518824/111212883-68332f80-858d-11eb-9b03-d1d272ef8054.png)

And those streets where the GSV imagery ends, they seem to mostly end at gates:
![Screenshot from 2021-03-15 12-50-45](https://user-images.githubusercontent.com/6518824/111212969-8305a400-858d-11eb-8496-f4ae823dc63a.png)
![Screenshot from 2021-03-15 12-51-01](https://user-images.githubusercontent.com/6518824/111212980-86009480-858d-11eb-8ad9-8032f07319e1.png)

Furthermore, I checked the OSM `way_id`s for those streets, and we do have them in our database. I have those streets turned off because there's no GSV imagery. If GSV imagery becomes available in the future, it will be easy to just flip the switch to include those streets :ok_hand:
