### ISSUE TITLE
Why Is The City Name Hyperlinked Here?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#251]
![image](https://cloud.githubusercontent.com/assets/1621749/17953193/5e2df54c-6a3f-11e6-8d76-218f655efca1.png)

Clicking this just seems to open a new window for that neighborhood. Why do we do this?

**Comment by kotarohara** [comment]
That's what we decided :) 

We talked about showing more information on the status pane, but I thought showing more than what we have now will clutter this area of the interface. The neighborhood name is hyperlinked, so that the user can see their neighborhood-level progress on the dashboard page. If you are anonymous, it just shows the neighborhood name and no link.

**Comment by jonfroehlich** [comment]
But clicking the link does not open the dashboard. It opens another GSV audit window in a new tab. That's my point.

**Comment by jonfroehlich** [comment]
@kotarohara, literally, the link opens: http://sidewalk.umiacs.umd.edu/audit

Can you please respond?

**Comment by kotarohara** [comment]
Ok, fixed.
