### ISSUE TITLE
Sidewalk Beta Test Issues

### ISSUE THREAD

**Issue by EdigaHe** [ProjectSidewalk/SidewalkWebpage#267]
I played Sidewalk beta for about 20 minutes. Here are some questions about the interface:

1. What do the scale "2" and "4" mean? Is there any criteria for picking these scales? If so, please add it to the tutorial. 

2. After I added some labels in the Street View window, the labels appear for a while but after I switch back from other places they disappear. I understand that the mini map at the right bottom corner shows all added labels but I prefer that the Street View window also remember all added labels.

**Comment by jonfroehlich** [comment]
Hi @EdigaHe, thanks for your comments. Generally, we reserve github tickets for actual bug reporting and issue tracking rather than discussion points... but thank you for posting your feedback.

@kotarohara, @manaswis, @Soben713: this is the second time that a beta tester has reported confusion over point 2 above. We do cover it a bit in the onboard tutorial (but it's very subtle). I think we should at the very least add this to the FAQ about *why* we can't do this (though I agree that it would be nice).

**Comment by kotarohara** [comment]
@Soben713 There are two issues in this issue. Can you close this issue and create two separate issues?

**Comment by Soben713** [comment]
@kotarohara Sure.
