### ISSUE TITLE
Gallery "next page" button 

### ISSUE THREAD

**Issue by sidlak-c137** [ProjectSidewalk/SidewalkWebpage#2716]
##### Brief description of problem/feature
When you click the next page button in the `/gallery`, the page reaches a "crash" state where there is no way to filter or go back to a previous page.
 

##### System info (OS, browser, city, and local/prod/test)
Windows, Chrome, localhost

##### Current behavior (add screenshots if applicable; check terminal & browser console for errors)
The site reaches this state:
![image](https://user-images.githubusercontent.com/15069663/140022098-9a3af439-9d3a-4194-b832-85781999b778.png)

##### Steps to reproduce
1. Go to `\gallery`
2. Ensure that there is only one page of images
3. Click the refresh button
4. Click the next page button
Here is a video of the bug: 
https://user-images.githubusercontent.com/15069663/140023626-77d11869-9c65-4504-a72c-79109617fc99.mp4

##### Potential solution(s)
Hide the next page button when there is only one page in the gallery (this assumes the bug is caused by the gallery only having one page).

**Comment by jonfroehlich** [comment]
Good catch @sidlak-c137!

**Comment by misaugstad** [comment]
There are two ways to test this one out. The first, is to be given an empty database dump so that you are starting from a database with no labels, thereby allowing you to open Gallery with only one page of labels. The other option would be to modify the back-end code temporarily to only send a small number of labels. I'd suggest the former, so whenever I assign this to someone, I want to send you an empty database dump... If I don't then please ask me! :grin:

**Comment by misaugstad** [comment]
This has now been fixed as of #3118!
