### ISSUE TITLE
Chicago API default map locations aren't centered on data

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2728]
In the Chicago partner meeting, we showed the /api page and noticed that the data visualizations are not centered

![image](https://user-images.githubusercontent.com/1621749/141858986-027b4b4d-0450-4acd-abe8-b4ffbd374e57.png)

**Comment by misaugstad** [comment]
@alligu here's some info to help you work through this one!

* You can see an example of what we want this page to look like [here](https://sidewalk-sea.cs.washington.edu/developer). That page is for Seattle, and we want the maps in Chicago to also some some useful data from Chicago.
* You'll need an up-to-date Chicago database to test on in order to find a nice area, which I've sent you over Slack
* You can set up the Chicago database as a 2nd database using [these instructions](https://github.com/ProjectSidewalk/SidewalkWebpage#setting-up-another-database-or-city) in the README. You can always switch back and forth between your different databases by stopping `make dev`, changing the `DATABASE_URL` and `SIDEWALK_CITY_ID` in your `docker-compose.yml`, and rerunning `make dev`.
* The locations that these maps show are defined using the latitude and longitude in the `conf/cityparams.conf` file. If you start looking at the HTML/JavaScript for the API page, you'll find which variables need to be modified in the .conf file.
* I think that the easiest way to find some areas that would look good are to look at the /labelMap URL. When you find a place that looks like it might be good, I think it's probably easiest right now to just look at the cross streets and put those into Google Maps. Then you can find the lat/lng from Google Maps. Then I put the lat/lngs into the config file, see what the API page looks like, and then start tweaking the different lat/lng/zoom values to get it looking nice :)
* Figuring out a good spot for the attributes API example is pretty easy from /labelMap. You'll want some intersections with a good mix of different label types. It might be the case that you can just use the same location for the streets API example, but if it doesn't have a good mix of red and green streets, then you should find a different spot for the streets. The neighborhoods API example will need to be zoomed out much further in order to see multiple neighborhoods.

**Comment by misaugstad** [comment]
closing in favor of #2855
