### ISSUE TITLE
Cleaning up the issues in the issue tracker

### ISSUE THREAD

**Issue by kotarohara** [ProjectSidewalk/SidewalkWebpage#276]
One issue with the way we use the issue tracker is that we have too many issues that cannot be closed. For example, #272, #269, and #234 cannot be closed as they are off-topic or there aren't clear definition of "resolve." This impacts the development productivity. 

We should spend a few hours to go through all the issues to either (i) close the ones that are off-topic (#272) and move to an appropriate place (an email thread?), (ii) tag things that are not resolvable (because they are not issues) as `discussion` (#234 and #269), and (iii) clarify some issues that doesn't really make sense because of poor description.

**Comment by jonfroehlich** [comment]
I agree that we should clean up issues. I disagree that we have Issues that are off topic.

For example, https://github.com/ProjectSidewalk/SidewalkWebpage/issues/272 isn't off topic. You need to modify the html source on the landing page to support social media sharing (so that the correct image is shown). We did this for Project Access (http://access.umiacs.umd.edu/maf8ecre/). See, for example: https://www.facebook.com/help/community/question/?id=10200814000150949

Also, I think it's useful to have things like this in the Issue tracker so we don't forget about them. 

My feeling is that we should have a new tag called Public Deployment 2 that prioritizes things for the next release.

https://github.com/ProjectSidewalk/SidewalkWebpage/issues/269 is also not off topic. It's a problem identified in our pilot studies. Users are confused. It needs to be discussed amongst the team, prioritized, and hopefully fixed.

Similarly, I agree with @manaswis on https://github.com/ProjectSidewalk/SidewalkWebpage/issues/234. I think the mission dialog does need to be redesigned. This is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/163. Again, this problem was discovered during user testing and *is* a problem. Our process should be: discuss the issue amongst the team, decide if it is addressable, if it is high priority (worth addressing), and if we have the resources to address it.

Please do not prematurely close Issues. We should use Labels and Milestone tags to help keep our Issues organized and prioritized. We can discuss this as a team during our team meeting tomorrow.

**Comment by kotarohara** [comment]
I see. 

Regarding #272, I agree updating the HTML is of the landing page is not off-topic. I will update the issue.

I did not say #269 is off topic, but it is not resolvable because it is neither a bug nor a feature request with a clear goal. That issue needs to be labeled appropriately.

Title of the #234 needs to be clarified. "X is confusing" is not resolvable. "X needs to be updated to Y because Z" is much more informative and actionable. Also, #234 seems to be a duplicate of existing open issues. So it should either be closed or marked as duplicate.

I do not close issues prematurely.

**Comment by jonfroehlich** [comment]
Great. I agree. 

Before marking a duplicate Issue closed, we should make sure that the details captured in the duplicate Issue are also in the open Issue.

**Comment by manaswis** [comment]
Closed it as the discussion was complete.
