### ISSUE TITLE
Add 'sand/gravel' to Surface Problem and Curb Ramp label types

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2805]
![image](https://user-images.githubusercontent.com/1621749/157338760-bce5c823-282a-488c-8b98-225595f75217.png)

**Comment by jonfroehlich** [comment]
![image](https://user-images.githubusercontent.com/1621749/157338954-5a97f908-8423-46b8-b76a-f060c7eb373a.png)

**Comment by misaugstad** [comment]
Right. We have historically told people to label surface problems on a curb ramp as a separate surface problem label. But there's no reason we can't just add tags to the curb ramps and interpret those as surface problems on our own. Makes it easier for users to label.

@jonfroehlich for curb ramps, do you want the tag to specifically be sand/gravel? How would you feel about just a generic "surface problem" tag for curb ramps? I'm worried about this ballooning into curb ramps having 10 different surface problem related tags.

Reminder to self: we'll want to update the labeling guide when making this change, since the labeling guide says to label issues with the curb ramp as their own surface problem label.

**Comment by misaugstad** [comment]
We discussed at our 1:1 meeting today. Summary of changes we want:
* For surface problems, add a "sand/gravel" tag
* For curb ramps, add just a "surface problem" tag
* For crosswalks, add the following tags
    * brick (#2802)
    * rail/tram tracks
    * bumpy
