### ISSUE TITLE
On user dashboard's top-down map, let them filter by "incorrect" and "correct" labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2811]
![image](https://user-images.githubusercontent.com/1621749/157672838-6744c2ad-fdc0-427d-851b-7a4baca80c65.png)

Related to allowing users to see their recently validated labels on their dashboard (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2288), another "easy" way to give access to this information is via the top-down map on the dashboard. We could add a little "filter widget" that let's users filter their labels by "validated correct", "validated incorrect", and "not yet validated." This also relates to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2786

I also agree with @gari01234's old comment on this that it would be great if users could then change/update their labels to correct info, which we've also discussed here. https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2575

**Comment by misaugstad** [comment]
@nschung28 for this ticket, here's what I think needs to be done on the user dashboard map (you can see the fully featured legend at /labelMap):
1. Add in rows with checkboxes for validated correct, validated incorrect, unsure, and unvalidated
2. Reduce vertical spacing in the legend so that it fits nicely
3. Add in the ability for users to click on their labels on the map and open the menu showing extra info. However, we should remove the validation section from this UI for the user dashboard only (since users shouldn't be validating their own labels).
4. Optional: allow filtering based on label type using checkboxes

The code for the maps is in a centralized place, and we essentially turn features on/off depending on which page the map is for. There will have to be new parameters added to account for the current situation (like excluding the validation options from the label popups). I'm also not sure if there are tweaks that will be needed if we are only adding the filters based on validations (and not the other filters as well).

**Comment by misaugstad** [comment]
>we should remove the validation section from this UI for the user dashboard only

Maybe it's best to make it so that across all places where we use this view for a label, we remove the validation options if the label was placed by the signed in user? It's possible that we only include which user added the label if it's an admin looking at the page, but we should at least be able to add in a boolean indicating whether the label was placed by the current user or not! I'd save this bit for last though.

**Comment by misaugstad** [comment]
Just a note for the future that soon we'll want to add the ability for users to edit/delete their labels from this map (#3591), but let's start smaller with what we outlined above!
