### ISSUE TITLE
Forgot your password user error

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2817]
If you try to request a link to reset your password, you get the following error:

```
onError Happened
Execution exception[[EmailException: Sending the email to the following server failed : smtp-relay.sendinblue.com:587]]
```

To replicate, start by clicking "sign in"
![image](https://user-images.githubusercontent.com/1621749/158596214-d89df0aa-0f68-49d3-ba92-e5454c3e3fb9.png)

Then click "Forgot your password"
![image](https://user-images.githubusercontent.com/1621749/158596259-daff52c2-51f1-4d7b-9eb4-0ab3db108752.png)

Then click "Send email"
![image](https://user-images.githubusercontent.com/1621749/158596317-590191bb-9804-4f57-97e0-8344307312b5.png)

Once you do this, you get:
![image](https://user-images.githubusercontent.com/1621749/158596346-ab2317a1-6593-4410-addb-bac73e18b12c.png)

**Comment by misaugstad** [comment]
What in the world. I guess that sendinblue deletes your account and all of your data if you don't sign in or use it for 3 months. Since I hadn't tested out the password reset features since November, they deleted our account. All we got was an email 7 days before the account was deleted. And I obviously don't check our "do not reply" email address every week.
![sendinblue-deleted](https://user-images.githubusercontent.com/6518824/158666220-de763e4c-4696-497a-882e-a43f4ba2a93a.png)

![sendinblue-deleted-warning](https://user-images.githubusercontent.com/6518824/158666256-62e47d42-0369-44d5-a730-0b66e7069c02.png)

So I guess that I'll make a new account and make sure to reset my password on a test server every month :roll_eyes:

**Comment by misaugstad** [comment]
This should be resolved now. I've successfully sent a password reset email to myself.

**Comment by jonfroehlich** [comment]
Ugh, the trials and tribulations of software as a service!
