### ISSUE TITLE
Creating account in the middle of a mission bounces user back to a new mission

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#285]
**UPDATE (Jun 28, 2017)**: Editing the issue for starting a new mission when you newly sign up. Updated according to the [latest comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/285#issuecomment-310861272) in this thread. 

When the user gets the "contributing a lot" message asking them to sign up, the next mission they get is a new mission. This creates confusion for the user that all his progress made as an anonymous user was lost, and at which point they could drop out of the site (as mentioned by 1 user during the relaunch usability testing).

Ideal behavior: Continuing with the same mission and their previous contributions as an anonymous user getting added to their newly created account.

However, this is time-consuming for the relaunch. We need to come with some temp fixes that removes the user confusion that leads to a drop-out.

**Original Issue Text (Sep 1, 2016)**:
This would have happened when the user was labeling as an anonymous user and was requested to create an account when he labeled a good amount.

<img width="1255" alt="bouncing_back_to_beginning" src="https://cloud.githubusercontent.com/assets/2873216/18187778/8c81cf72-707a-11e6-867e-fa9936707b77.png">

Is it a bug?

**Comment by jonfroehlich** [comment]
It should definitely not bounce you back to the tutorial. Did you confirm this @manaswis.

**Comment by jonfroehlich** [comment]
Also, I believe I had opened an Issue (but can't find it now) or otherwise I sent Kotaro an email or wrote it down in a PPTX mockup that the correct behavior for logging in should be that it simply allows you to continue where you were while you were contributing anonymously. Unfortunately, I don't believe that's what is happening now and that's probably very frustrating to the user---especially since we prompt them to login and, when they do so, our interface makes it seem like they lose work.

**Comment by manaswis** [comment]
Yes, I just tested it. It doesn't show the tutorial (maybe coz I skipped it when I was anonymous - not sure about it - @kotarohara can tell). But it assigns a different neighborhood and starts at the very beginning.

<img width="1187" alt="bouncing_back_to_new_neighborood" src="https://cloud.githubusercontent.com/assets/2873216/18189288/7dc201de-7087-11e6-9fb4-d12985fd55c8.png">

**Comment by jonfroehlich** [comment]
This is unfortunate. @kotarohara, I remember chatting about this with you and you decided it was not worth the effort to fix. I could not find the Issue in github--perhaps we discussed it in email?

**Comment by manaswis** [comment]
Just noticed, Kris also reported about the same problem

<img width="637" alt="bouncing_back_kris_twitter" src="https://cloud.githubusercontent.com/assets/2873216/18194129/64cf8afa-70b1-11e6-8cdb-bdc871e815ad.png">

**Comment by kotarohara** [comment]
No, the tutorial should not be shown to the same user. I'll take a look why it showed up for the user.

**Comment by kotarohara** [comment]
And I think there is another issue in this thread about how we treat the anonymous contribution after the user decides to sign up/sign in.

**Comment by kotarohara** [comment]
I am retracting myself from this issue. @manaswis , as a leading graduate student of the project, please decide what you want to do with the behavior of the application. If you want to keep the application as-is so it refresh the page after logging, I think that's fine. If you want to change the behavior so the application allows the user to login without page refresh, you can do so by merging PR #375 . I recommend writing unit tests to define the behavior which captures the issues that @Soben713 mentioned.

**Comment by jonfroehlich** [comment]
I am interviewing a high school student for a summer lab position. He generally thought Project Sidewalk worked well but mentioned this criticism:

> The only problem I had was when I was in the middle of my first mission and I clicked on the signup popup, after I had signed up it directed me to a different mission and did not go back to the mission that I was in the middle of previously.

So, I'd like to fix this whether for v2 or v3.

**Comment by jonfroehlich** [comment]
I see a pull request has been submitted for this issue but it's unclear to me what, exactly, is being addressed. There are multiple important things in this thread, which I emphasize in my comments above. To summarize:

* If anonymous user selects the sign-in option, they are pushed to a new mission rather than simply continuing their current one (as one would expect). The current behavior is demotivating and confusing. (See: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/285#issuecomment-244247745 and https://github.com/ProjectSidewalk/SidewalkWebpage/issues/285#issuecomment-244256914 and https://github.com/ProjectSidewalk/SidewalkWebpage/issues/285#issuecomment-268020344). 

* What to do with anonymous contribs for user that switches to signed-in. Ideally, the anonymous contribs would all be retroactively assigned to the signed-in user. (We'd likely have to write a SQL table update).

**Comment by manaswis** [comment]
As mentioned above, ideal behavior is continuing with the same mission and their previous contributions as an anonymous user getting added to their newly created account. However, that's time-consuming and requires significant changes to the code. So we can't take this route for the relaunch.

Few temp fixes that we came up in our brief brainstorming session:

1. Removing that pop-up to show up **Disadv**: we won’t have any user convert to a registered user

2. Show the pop-up at the end of a mission **Disadv**: We already have two dialog boxes at the end of a mission i.e. the mission complete box and the next mission instruction box. So this would just add clutter to the mission completion process

3. Show a different mission complete box for only **the first mission** (similar to first mission instruction box - #731) that will show both: count of labels they contributed in the first mission (something similar, content-wise, to our current mission completion box) and ask the user whether they want to now sign up/sign in. **Disadv**: Time consuming since this needs significant redesign of the mission complete dialog box

4. The page doesn’t reload after sign-up/sign-in, so that the user doesn't get confused **Disadv**: We currently don’t know if its easy/hard to do it. @sbower213 is working on it the PR that was submitted by Kotaro and seeing if he can make it work.

**Comment by jonfroehlich** [comment]
The other thing that is related to this is that we still do not have a clear value proposition for *why* a user would want to sign-in. This also needs to be clear.

Regardless of this point, I consider this problem significant because the people who choose to sign-in are giving us a signal that they are motivated and interested--and then we basically slap them in the face by confusingly placing them in a new location and making it seem like they lost their work/progress. 

@maddalihanumateja, I just talked about this with @manaswis. Depending on what's on your plate right now, maybe you can help @sbower213 with this?

**Comment by sbower213** [comment]
The main issue of being jumped to a new location has been fixed. The pull request kotaro submitted worked very well for the most part; I had to make a couple minor changes to make sure the "you've been contributing a lot, sign in!" message didn't show up after a user logged in (after initially being anonymous). Still a few more changes on this front to make sure users don't see alerts they shouldn't.

I'm a bit confused about the second issue @Soben713 noted in #375, are we supposed to put the user in the same spot after they refresh the page? Because that functionality is not happening right now, so I can't reproduce the issue of completion percentage suddenly jumping.

What I've done so far also doesn't retroactively update the actions that were done anonymously to show as done by the now signed in user. This results in a user's dashboard showing incomplete routes they have audited (only saving the information from after they logged in) but a few SQL update statements should be sufficient to fix this, I think.

**Comment by manaswis** [comment]
This is great, @sbower213! Could you update your branch with the latest changes from develop and then test if it works? You could do that after you fix other issues too.

>are we supposed to put the user in the same spot after they refresh the page? 

I think @adash12 was working on something similar about putting them at the same spot after they retake the tutorial. Check with him once.

**Comment by sbower213** [comment]
Yeah, I pulled from develop and merged all the necessary changes and I think it still works fine. Aditya said that his issue wasn't quite as easily applicable and that it was still kind of hit-or-miss as far as refreshing and being put in the same location goes. I will look further into the issues I mentioned earlier tomorrow.

**Comment by jonfroehlich** [comment]
@sbower213. This is great news. We'll have to test this like crazy on sidewalk-dev.

> The other thing that is related to this is that we still do not have a clear value proposition for why a user would want to sign-in. This also needs to be clear.

Is anyone working on that? Is that listed in another issue?

**Comment by manaswis** [comment]
Closed via PR #786
