### ISSUE TITLE
The API examples on the Amsterdam API return empty sets

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2855]
If you click on the highlighted examples below, they return empty sets: `{"type":"FeatureCollection","features":[]}`. I haven't checked other cities to see if that's the case.

![image](https://user-images.githubusercontent.com/1621749/162201051-5e3574a0-968f-4e18-bbb8-004dd2ae72e1.png)

![image](https://user-images.githubusercontent.com/1621749/162201113-de4aa5de-d4d5-4815-b3c0-4801b391bb49.png)

My guess is the geo boundary is off?

**Comment by misaugstad** [comment]
When I make a new database, I generally try to contribute some data myself, and then set the boundaries for these maps in the config files so that there is at least something there from the jump. I think that there was just more important stuff I needed to be doing at the time (like adding new label types), so this got pushed to the future. But I forgot to make an issue for it!

This is actually an issue in a few cities. So I'm going to wrap that up into this one issue...
- Amsterdam is not centered on data anywhere
- Chicago is not centered on data anywhere (#2728)
- SPGG isn't showing data for just the 'Access Neighborhoods' API
- CDMX is showing data, but it's showing too large of an area, which leads to a really slow page load as the maps query a ton of data

**Comment by misaugstad** [comment]
in #2728 I posted some instructions to help guide someone on how to update the maps in Chicago. Editing slightly and pasting the instructions below:

* You can see an example of what we want this page to look like [here](https://sidewalk-sea.cs.washington.edu/developer). That page is for Seattle, and we want the maps in each city to also some some useful data from that city.
* You'll need an up-to-date database for each city to test on in order to find a nice area, which I'll send over Slack
You can set up multiple databases using [these instructions](https://github.com/ProjectSidewalk/SidewalkWebpage#setting-up-another-database-or-city) in the README. You can always switch back and forth between your different databases by stopping `make dev`, changing the `DATABASE_URL` and `SIDEWALK_CITY_ID` in your `docker-compose.yml`, and rerunning `make dev`.
* The locations that these maps show are defined using the latitude and longitude in the `conf/cityparams.conf` file. If you start looking at the HTML/JavaScript for the API page, you'll find which variables need to be modified in the .conf file.
* I think that the easiest way to find some areas that would look good are to look at the /labelMap URL. When you find a place that looks like it might be good, I think it's probably easiest right now to just look at the cross streets and put those into Google Maps. Then you can find the lat/lng from Google Maps. Then I put the lat/lngs into the config file, see what the API page looks like, and then start tweaking the different lat/lng/zoom values to get it looking nice :)
* Figuring out a good spot for the attributes API example is pretty easy from /labelMap. You'll want some intersections with a good mix of different label types. It might be the case that you can just use the same location for the streets API example, but if it doesn't have a good mix of red and green streets, then you should find a different spot for the streets. The neighborhoods API example will need to be zoomed out much further in order to see multiple neighborhoods.
