### ISSUE TITLE
Google is reminding us to upgrade to Analytics 4 by July 1, 2023

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2857]
When you visit Google Analytics, you receive a message:

> Universal Analytics will no longer process new data in standard properties beginning July 1, 2023. Prepare now by setting up and switching over to a Google Analytics 4 property.

![image](https://user-images.githubusercontent.com/1621749/162577045-2f942425-e27f-4cee-be0a-3cd1c9154f8a.png)

One thing that worries me is that the [Google support website](https://support.google.com/analytics/answer/11583528) says:
> After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time

So, like, would we still be able to access all previous visit logs, etc.? I think this data is important for any future papers we might want to write (e.g., about the locations of visitors to the website, how many came, etc.)

**Comment by misaugstad** [comment]
I've already set up Google Analytics 4 in every city. For the old data, I'm assuming that we'll be able to get that data... We can get various reports right now, and they have some API as well. I'm not sure how granular of data that we can get right now. The site does also say
>We intend to offer more guidance on data export as we approach the date when Universal Analytics is no longer available.

So it might be easiest to put this off for now and wait for them to give us better directions for exporting the old data.

**Comment by jonfroehlich** [comment]
OK, yes, I think we'll have to export the old data... but let's keep track of this and reassess.

**Comment by misaugstad** [comment]
Bringing this back up because the old GA logging ends in July 1. We have the new logging set up, I'll just need to export the data from the old logging method and save it somewhere, and then we can delete the old logging code.

**Comment by misaugstad** [comment]
I've finished exporting all the old data using the [Google Sheets add-on for Analytics](https://developers.google.com/analytics/solutions/google-analytics-spreadsheet-add-on). The report for each of our cities can be found [here in Google Drive](https://drive.google.com/drive/folders/1U1nRwi--u-ep38dqMkzg3m8Dn6KgC8z7?usp=drive_link) (only shared w/ Jon and I). Note that only DC, Seattle, Newberg, SPGG, CDMX, Columbus, and Pittsburgh are included here, because all other cities were collecting data with the new GA4 from the beginning, so there's no need to export old data for those cities.
