### ISSUE TITLE
Make keyboard shortcuts feature more visible to the user

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#287]
Currently, availability of keyboard shortcuts as an option for navigating the interface is hidden. Need to make it more visible.

TODO:
In the first mission, after the user takes two steps, show an instruction pop-up informing about keyboard shortcuts e.g. "Did you know you could use X for doing Y? For more info, look at our FAQ".

**Comment by kotarohara** [comment]
@manaswis Is this a TODO that we decided to implement?

**Comment by manaswis** [comment]
Yes, we discussed this in last week's meeting.

**Comment by kotarohara** [comment]
OK!

**Comment by Soben713** [comment]
I don't really like the idea of using a popup message in the first mission. My reasons:

1. Shortcuts are useful if you use the system a lot. There are already too many things to learn when you first start that displaying a message for introducing the shortcuts would just make things more complicated for the user.
2. These types of messages are usually annoying and distracting because they are shown when user does not need them.
3. Most people don't read them.

My suggestion is to use tooltips for the label buttons, just like what other applications do, e.g., Photoshop:
![image](https://cloud.githubusercontent.com/assets/1576529/18322623/91aaf150-7501-11e6-810f-109deadf577a.png)

**Comment by jonfroehlich** [comment]
Hmm, good discussion.

I actually almost always read pop-ups that occur during onboarding in games--which is the model we are following here--as long as they are quick to read, well-designed, and contextualized to what the user is currently doing. This is very different from pop-up boxes that some software has when a program first loads (e.g., tips of the day)--I never read those because they are decontextualized and annoying, they actually prevent me from doing what I want to do, which is use a program. 

I also think the value of using keyboard shortcuts is *extremely* high in terms of improving user efficacy (though some users simply do not like to use their keyboard or keyboard shortcuts, so will ignore them). So, I think we do want to make sure all users at least know about them.

I think tooltips are probably a good idea but for me at least, I rarely see or pay attention to these. For example, I just noticed that they actually have them in the github rich text editor interface. See:

![image](https://cloud.githubusercontent.com/assets/1621749/18322944/48be5958-7503-11e6-93c0-9b8176eb1c75.png)

Also, this is a **passive** approach to informing the user rather than a proactive approach, I think we need the latter.

**Comment by Soben713** [comment]
Ok then I guess we are different on that, would be useful to have some user studies to see what other users do. But in general, I agree with this:

> --as long as they are quick to read, well-designed, and **contextualized to what the user is currently doing**

It would probably be better if we show the message when the user clicks on a label instead of showing it after they take some steps. Also it would probably be better if the message does not interrupt the labeling and is shown somewhere else in the screen without requiring the user to press an OK button.

**Comment by manaswis** [comment]
Ideas from our meeting yesterday:

Provide:
- hover support on the label marker buttons
- show a message about keyboard shortcuts at the 6th (or xth) step in the first mission 
- auto detect continuous use of the buttons, then show the message to use keyboard shortcuts
- toolbar showing the keyboard shortcuts (with a Dismiss button) for the first few walks just underneath top canvas border within the canvas window e.g. how websites show temporary toolbars about enabling cookies

Keyboard support for walking and rotating should also be made clear (from undergrad reviews) using one of the ways above.

**Comment by jonfroehlich** [comment]
I think all of these are really important to help not only improve user efficacy but also enjoyment. Without the keyboard shortcuts, I find labeling rather tedious. With keyboard shortcuts, I can really get in the flow and go much faster--far more enjoyable.

I think we should implement all of these (with, perhaps, the exception of the last one, which doesn't really make sense to me and seems redundant with the 2nd and 3rd bullets). Priority:
- hover support
- auto-detect continuous use of buttons then show recommendation to use keyboard shortcuts
- show message about keyboard shortcuts at the xth step in first mission

**Comment by Soben713** [comment]
I implemented the second (tooltip) and the third (auto-detect & alert) solutions and I agree with Jon that the last one is redundant. Also, taking the tutorial again, I think maybe the first one is also redundant. This is a screenshot of the tutorial:

![image](https://cloud.githubusercontent.com/assets/1576529/20228531/a3c75a12-a81f-11e6-9b8e-c7958c1f15f7.png)

I think the tooltip is visible enough. I still would rather keep the onboarding tutorial short to be honest. Thoughts?

**Comment by manaswis** [comment]
When does the tooltip appear? I think I would still like the hover support: show whenever he is clicking the button. If we can add a delay to show the tooltip e.g. if the user hovers over the button for more than x seconds, then show the hover, else it might get frustrating to see the hover each time he/she clicks the button (e.g. for people, who just prefer using the mouse than the keyboard.)

The above comment is not specific to the tutorial, but talking in general during usual audit.

**Comment by jonfroehlich** [comment]
I think the tooltip hover should be implemented very similarly to the github hover, which seems to pop up after ~500ms.

Note that we must disable this hover tooltip during the tutorial as we do not allow users to use the keyboard during the tutorial--so this would be incredibly confusing.

**Comment by Soben713** [comment]
@manaswis Sorry, I updated my comment. I implemented the first and the 3rd solutions.

**Comment by Soben713** [comment]
I just submitted a pull request for this.

@jonfroehlich Thanks for pointing out the tutorial problem. I fixed it and keyboard shortcuts correctly work in the onboarding tutorial.
