### ISSUE TITLE
The statistics don't seem to be updating during the mapathon

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2870]
The label and validation counts are increasing but not the percentage audited or miles audited. I've refreshed multiple times (including in incognito and across browsers).

This is the admin interface, which shows 7.8 mi audited today and 8.7 mi audited yesterday, which adds to more than the 10.6 mi overall number.
![image](https://user-images.githubusercontent.com/1621749/164815769-8b93bf6e-dcad-4151-beba-1098525dd048.png)

When we started the mapathon, the stats showed 9.6 mi audited. Now it only shows 10.6 mi audited:
![image](https://user-images.githubusercontent.com/1621749/164815862-cba833cd-6a0a-4cdd-9ff1-5f346ec91d61.png)

Also, we've been hearing complaints that the leaderboard isn't updating... there are probably 20-25 people at the town hall mapathon but only 7 shown on the leaderboard:
![image](https://user-images.githubusercontent.com/1621749/164815944-b3a73a8c-6542-4076-bf39-1ba6a547b948.png)

**Comment by jonfroehlich** [comment]
Looks like the leaderboard issue was because about four of the Girl Scouts were on the **test** server by accident. We discovered this because a mapathon participant complained that they were not showing on the leaderboard.

![image](https://user-images.githubusercontent.com/1621749/164816392-1a3417fc-052a-471c-964e-dac3423ee95e.png)

However, the stats on the landing page are still not updating (the % and the miles are not updating but the label and validation counts are)

**Comment by jonfroehlich** [comment]
So the Today column is still updating but the landing page and overall is not:

![image](https://user-images.githubusercontent.com/1621749/164816759-bf52300b-54bc-48bd-a96f-5d841d7907c8.png)

![image](https://user-images.githubusercontent.com/1621749/164816780-2d64482d-73e2-4f5c-926e-d508eaf3579c.png)

**Comment by jonfroehlich** [comment]
@misaugstad told me on Slack to clear the play cache... I just did and the stats went up.

![image](https://user-images.githubusercontent.com/1621749/164817073-d249c638-2d60-4ea7-99de-722200f11461.png)

![image](https://user-images.githubusercontent.com/1621749/164817095-388704dd-6a44-4104-9ce8-6127c32c10f6.png)

**Comment by jonfroehlich** [comment]
I hit the "clear play cache" again and here's the new stats:

![image](https://user-images.githubusercontent.com/1621749/164817447-245df122-d587-49bf-9ab7-f1f1e2e4c0e9.png)

**Comment by misaugstad** [comment]
>This is the admin interface, which shows 7.8 mi audited today and 8.7 mi audited yesterday, which adds to more than the 10.6 mi overall number.

It looks like we are calculating these using different methods. The daily/weekly are counting duplicates, whereas the total column is excluding duplicates. The total column should also include the duplicates, since we already have the distance audited excluding duplicates in the 'Coverage' section to the right.

>told me on Slack to clear the play cache... I just did and the stats went up.

I'm now remembering our old conversations where we decided to cache the audited distance on the landing page to improve the landing page load times. We have it set to clear the cache once per hour. Based off of last week's events, I'm assuming that you'd like to have this amended in some way?

>When we started the mapathon, the stats showed 9.6 mi audited. Now it only shows 10.6 mi audited
>... the stats on the landing page are still not updating (the % and the miles are not updating but the label and validation counts are)

From above, the landing page not updating at all has to do with the caching. While the smaller than expected increase in the distance completed has to do with re-auditing areas that were audited by users marked as "low quality". Similarly, users whose data has been marked as "low quality" likely continued to audit, and their new contributions may not have been counted in those stats either.

You can see my lengthy musings on these issues in #2770

**Comment by jonfroehlich** [comment]
This all makes sense. Thanks Mikey.

I think some of these things only arise when we are doing an high-energy mapathon and really closely tracking stats. We should sync up to figure out how to address these cases.

It's unfortunate about data quality. I think the mapathon was a lot of fun—but there was also many distractions (which is a good thing, of course, as it makes for a festive atmosphere) and some of the girls that attended had not received any training.

**Comment by misaugstad** [comment]
Most of this has been dealt with, but the following problem was pointed out in this thread that needs to be addressed to close this: The Total Audited Distance in that table needs to be counting duplicates like we do for the Today and Yesterday values. There should be a function in our code that will do this, we probably just need to be calling it. But I could be wrong!
