### ISSUE TITLE
LabelMap should show both audited streets and yet-to-be-audited streets

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2873]
To help us better interpret our data and distinguish between street segments that are unaudited but are allocated for auditing and street segments that simply did not make it into Project Sidewalk (for whatever reason), LabelMap should show both. This will also allow us (and partners) make sure that we have the inclusion of all expected streets for auditing.

Currently, it only shows audited streets in black:
![image](https://user-images.githubusercontent.com/1621749/164896681-16a624b9-5198-4c44-9196-5577d9114da6.png)

So you get a visual like this:
![image](https://user-images.githubusercontent.com/1621749/164896694-7d5b3f7c-b1ab-473b-b459-81dd69aee684.png)

But we should add another checkbox for "Unaudited streets" (or something better named) that shows scheduled audited streets maybe in light gray or something.

This is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2872 and is pretty important for us to better understand our datasets and what areas of a city are accidentally being excluded from auditing. Currently, I'm thinking we might need to manually select new streets for inclusion into Oradell so we can comprehensively finish the whole city.

**Comment by GPA0VERKD** [comment]
Are the "unaudited streets" we want just any street within the outlined polygons that aren't audited? Or are there more streets outside of those that should be outlined?

**Comment by misaugstad** [comment]
Just the streets inside. I think that the two ways to find the full list of streets would be either every street in the `street_edge_priority` table, or every street in the `street_edge` table where `deleted` is set to `false`.

**Comment by GPA0VERKD** [comment]
Here's what the label map looks like with black audited streets and gray unaudited, is the color scheme and interface for the new legend marker looking good?

![image](https://user-images.githubusercontent.com/77756028/183482572-f3ee6f74-2de4-4832-8a93-cbbb85b5bdd7.png)

Also, some issues/ideas about how to label map is looking right now:
1. The black outline on regions when hovering makes it look the exact same as audited streets, not sure if that's a concern
2. When the page loads, it seems like some of the audited street layers aren't loading until after you uncheck some of the label types or zoom in. If you re-check the label types/zoom out again, the audited street layers stay as they should, the issue is only when you first load the page so it looks like way less streets have been audited than in actuality. Idk if it's just being covered by the labels or if they actually aren't loading in.

Initial page load:
![image](https://user-images.githubusercontent.com/77756028/183485021-191387c2-6284-42fe-bd31-e9513bbcec05.png)

3. The visual clutter with all the markers is overbearing and slows down the page load time considerably; is it possible to implement a feature like consolidating similar label types into 1 point if they're too close together, and when zooming in the point will separate into individual points for each label when there's enough space between them (kind of like with google maps, when you zoom in more streets and landmark names become visible, but when zooming out they disappear to reduce visual clutter)? We could even add a little number on labels if there's more than one label included in the point or some other kind of visual sign to show that there's a lot of tags in one point/area
4. Zooming in/out is a bit annoying with the mousepad/scroll wheel, especially with how laggy the label map page is. Could we also add in an actual zoom in/zoom out button or key mapping like we do with the audit page?

**Comment by jonfroehlich** [comment]
This is looking quite nice. You also offer some great points (that likely deserve their own tickets).

I wonder if this "audited street" version could be the default load (so all labels are off by default)? Or, alternatively, maybe we could pass in some REST arguments to load diff versions by default? Or perhaps the audited streets vis is its own page entirely?

![image](https://user-images.githubusercontent.com/1621749/183490366-6da0e13a-4a66-4562-9044-e985c28c65dd.png)

I can't comment on the black outlines on hover as you didn't include a screenshot of this.

**Comment by GPA0VERKD** [comment]
Here's the hover issue with the region outlines. The red dot is where my mouse was, so the black outline around that region isn't audited but looks the exact same:
![image](https://user-images.githubusercontent.com/77756028/183491245-52f6ea10-8fd5-4163-aa9e-340b5a81c38e.png)

Maybe we could have a button to turn all labels on/off to make it easier to see just the audited streets, or 'preset' buttons that will auto check/uncheck certain boxes (i.e. all labels off + audit/unaudited streets on, all labels on + audit/unaudited streets off)? That way it'd function pretty much the same as having an audited streets page on its own

**Comment by jonfroehlich** [comment]
Yah, the UI on this page is pretty horrendous tbh. I like the idea of a button to turn on/off all labels (or show/hide all of them but retain the same UI state of severity levels, etc.)

**Comment by GPA0VERKD** [comment]
Just to finalize what should be in this ticket alone and what should be in other tickets/not important, we have:

- [ ] Hiding cluttered markers depending on zoom in distance
- [ ] Adding a zoom in/out button
- [ ] Make labels off by default
- [ ] Preset checks/unchecks (show/hide all labels button)

Among those (if any), which should I focus on implement in this ticket and which should be saved for a different ticket/ignored?

**Comment by jonfroehlich** [comment]
I would defer to @misaugstad but I'd prefer we close this ticket with just adding in the audited/unaudited streets feature.

Then you can create another ticket for:
![image](https://user-images.githubusercontent.com/1621749/183500732-f3ffc48c-2029-4db0-abc5-ef51c0b81a02.png)

**Comment by misaugstad** [comment]
>Hiding cluttered markers depending on zoom in distance

I believe that I had looked into this before, and I think that it being possible is predicated on upgrading to the newer version of mapbox, which is a nontrivial effort! But it could have a lot of other performance improvements for our maps as well! Here's the ticket: #2194 

>Adding a zoom in/out button

We actually do have a zoom in/out button in the top-left!
![Screenshot from 2022-08-11 09-34-50](https://user-images.githubusercontent.com/6518824/184184637-9d9a8526-e954-4f52-93af-9e08a51526c7.png)

>Make labels off by default

I don't think that we need a ticket for this one... The tool is literally called LabelMap :joy: So I don't think that the way to improve performance is to not show labels by default.

>Preset checks/unchecks (show/hide all labels button)

Sounds like a good idea! Especially after we update the legend to group things together a bit more (#2849), then having a checkbox on the "labels" header that checks/unchecks all those boxes would be great! Feel free to make an issue for this one @GPA0VERKD :)
