### ISSUE TITLE
Why are so many labels in LabelMap only showing outline color?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2913]
I believe we made a modification to LabelMap to be able to visually tell a label with an expired pano vs. not by only outlining the label (an outlined label without a fill color had an expired pano). However, this no longer seems to be working correctly.

Take a look at this map of La Piedad. So many labels only have outlines, however, you can click on them and actually see the label/pano just fine. 

![image](https://user-images.githubusercontent.com/1621749/169673473-637e17ee-bc48-4c4a-95b4-443c1564a829.png)

This also suggests that we should have a better legend that helps us understand what all these variations mean...

**Comment by misaugstad** [comment]
The likely explanation (and solution) for this is in #2458! If there is a network connection issue, it can lead to imagery being marked as "expired" when that's not actually the case. And if it's marked as such, we never go back through to check if it was marked that way incorrectly. So I'd like for us to be checking that on a nightly basis.

In the short term, I can manually run a query that will check the imagery for everything in La Piedad, since it looks like this issue heavily impacted this city. It's possible that we (or Google) had a network issue at a time when we tried to load Gallery or Validate in La Piedad, and it ended up marking everything as expired.

**Comment by misaugstad** [comment]
Okay, nope, looks like a new issue! I tried resetting everything, but got similar results. I used our usual method of checking if the imagery exists for a label that was marked as expired incorrectly, and I got this error!
```
{
    "error": {
        "code": 403,
        "message": "SSL is required to perform this operation.",
        "status": "PERMISSION_DENIED"
    }
}
```

But this is only happening maybe 1 our of every 3 time that I try it. If I try it repeatedly on the same set of labels, about a third of them get marked as expired each time, and it just continues to dwindle :joy: 

I think we might just need to switch the URL from http to https?

**Comment by jonfroehlich** [comment]
What's the request URL? Do you need an API key to test it?

**Comment by misaugstad** [comment]
Thank you, I meant to include an example URL! You do not need an API key to test. It looks like this:
http://maps.google.com/cbk?output=tile&panoid=MKS1rGHMGE73P86LkIpkPA&zoom=1&x=0&y=0

**Comment by misaugstad** [comment]
And the way I'm manually retrying all the labels is to run this in the browser console while on the website. I was doing it one label type at a time, though I think there's a way to do it all at once.
```
$.ajax({
    async: true,
    contentType: 'application/json; charset=utf-8',
    url: '/label/labels',
    type: 'post',
    data: JSON.stringify({ labelTypeId: 1, n: 1000, loadedLabels: [] }),
    dataType: 'json',
    success: function(data) { console.log(data); },
    failure: function(data) { console.log(data); }
});
```
