### ISSUE TITLE
Just Started a Brand New Mission and Mission Bar at 47%

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#297]
I just completed a mission in Fort Lincoln and started a new one and at the beginning of my mission, the mission bar is 47%:

![image](https://cloud.githubusercontent.com/assets/1621749/18225686/690bd54a-71c6-11e6-8b81-b3d8a9ef5f0c.png)

This is related to but I think different from https://github.com/ProjectSidewalk/SidewalkWebpage/issues/159 and https://github.com/ProjectSidewalk/SidewalkWebpage/issues/195 because in those cases, supposedly, the mission bar was reflecting my previous progress on that mission from the last time I signed in (because I left without completing the mission).

This case is different in that I literally just finished a mission, was assigned a new one, but my progress bar started at 47%. This doesn't make sense.

**Comment by jonfroehlich** [comment]
Hmm, now, as I am walking around, the mission bar reset. I'm not sure when this happened but now it's at 17%. This is definitely a bug.

![image](https://cloud.githubusercontent.com/assets/1621749/18225705/31260c26-71c7-11e6-950d-760735ebe4b6.png)

**Comment by jonfroehlich** [comment]
Seems to be going up correctly now:

![image](https://cloud.githubusercontent.com/assets/1621749/18225742/5599b318-71c8-11e6-85d7-4953b5bd117c.png)

**Comment by Soben713** [comment]
Had the same experience today. The mission progress bar started at 43% and after walking a little it was reset to 0. Luckily I was recording my screen. Here is the video: https://www.youtube.com/watch?v=vC_-dY3aw9o

**Comment by kotarohara** [comment]
Yeah, I don't know why it's happening. @Soben713 , do you want to look into it?

**Comment by jonfroehlich** [comment]
@kotarohara, wouldn't this require @Soben713 investigating both backend and frontend--seems like a pretty difficult task to debug with his current understanding and experience of codebase.

**Comment by Soben713** [comment]
I don't mind investigating the backend :)
I can look into it once we find a way to reproduce this bug.

**Comment by kotarohara** [comment]
I don't think it's related to backend though. There is something going on in `Mission.getMissionCompletionRate` method which is used to update the status pane.

**Comment by jonfroehlich** [comment]
Just happened to me again:

![image](https://cloud.githubusercontent.com/assets/1621749/20112800/c9812cee-a5bb-11e6-9a7a-dc033773a805.png)

![image](https://cloud.githubusercontent.com/assets/1621749/20112855/ecab38e0-a5bb-11e6-8001-f1ade97dca69.png)

![image](https://cloud.githubusercontent.com/assets/1621749/20112887/10d0d694-a5bc-11e6-93de-ed34452fd904.png)

@Soben713, any updates on this?

**Comment by Soben713** [comment]
I found a way to reproduce it. I am looking into it.

**Comment by Soben713** [comment]
Finally, I figured out what the problem is. In fact, it is a deep structural problem in the system.

We mark a street segment as `completed` in the database when the user completely audits it. In other words, we don't store what portion of each segment has been audited. Now, if the user refreshes the page while in the middle of a mission, we load the data from the database and compute the `completedDistance` based on the completed street segments and ignore the one that they were auditing (because we don't have any data about it). This causes two problems:

1. If you refresh the page, the mission progress bar goes down a little bit.
2. [**The Current Issue**]: If you happened to complete a mission and then refresh the page while in the middle of a street segment, then the last mission will be stored as "completed" but the total length of the audited streets will be less than the size of that mission.

There are two ways to resolve this issue: (1) changing the underlying system and the way we store missions and tasks, and (2) quickly fixing the progress-bar by some conditional statements to detect the mentioned problem.

I am leaning towards doing the second solution because the first one requires a lot of changes both in the backend and the frontend and requires a deep understanding of the code. Thoughts?

**Comment by jonfroehlich** [comment]
@Soben713, in my opinion, it looks like missions were, unfortunately, poorly implemented--which is not too surprising since they were added in later after the initial system was architected. It does seem to me, however, that we should be tracking a persons mission progress directly and we should implement missions more elegantly on the backend. Not sure we want to open this pandora's box for v2 though--thoughts?

**Comment by Soben713** [comment]
@jonfroehlich Based on my current knowledge of the system I agree that the mission progress could be directly stored in the database, but I am not sure about the consequences because, for example, we will have some sort of data redundancy in the database.

I agree that at some point, we need to re-implement or at least refactor this part of the code. But it requires a lot of time and we might want to consider other gamification ideas before doing that since we all agree that it is not currently very entertaining.

Anyway, I just came up with an idea to fix this issue in a somewhat clean way without changing the backend. I will do it for now and we will figure out what to do for it in the next versions.

**Comment by jonfroehlich** [comment]
@Soben713. Completely agree. Glad you came up with a 'somewhat clean way' to fix it without changing backend. Nice job.
