### ISSUE TITLE
Getting label data from clusters API

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3042]
We have now integrated getting severity information and even the underlying GSV image dates in the cluster API.

I do not think, however, that the cluster API includes label tags. Chu and I were talking today and would like to add this.

The key unresolved Q here is: should we do a **union** of the tags in the cluster or an **intersection** of the tags. I lean towards union.

**Comment by misaugstad** [comment]
What we have done is add the tags to the /attributesWithLabels API. We only added it to that endpoint because it is just so much easier to add it to that endpoint, and if you combine the /attributes and /attributesWithLabels endpoint, you can still get all of the information.

>The key unresolved Q here is: should we do a union of the tags in the cluster or an intersection of the tags. I lean towards union.

I think that ultimately, no matter which one we do, a few months from now we're going to make a ticket that says that we want a count of the number of labels in the cluster that have each tag 😛

**Comment by jonfroehlich** [comment]
Gotcha. @crescendochu, can you followup with Mikey over Slack to make sure you get everything you need for your tag analysis.

@misaugstad, do you think we should close this ticket then?

**Comment by misaugstad** [comment]
Yeah I think so. I think that it's not worth our time to do the aggregation ourselves for everything. If someone is making use of the API, I'm hoping that they will be able to connect the data themselves for the most part. When we beef up the documentation, we can make this a lot more clear that people should be checking the /attributesWithLabels endpoint for more data.
