### ISSUE TITLE
Interactively building a custom audit route

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3079]
Recently, our Zurich partners floated the idea of:

1. Drawing an audit route on a map
2. Allowing more than one labeler follow that same route (independently, of course) to complete an audit

This is basically what Devon and Mikey have been doing but in this case, it would be streamlined and broadly supported.

The interaction could be something like this. 

1. The user draws a route on a map (like LabelMap)
2. Once the route is complete, the user names the route
3. Then you are presented with a 'start exploring this route' button. You could also click on the route and share it with others.

https://user-images.githubusercontent.com/1621749/203134282-d0e778bc-e27a-4e99-bb78-41339542eb08.mp4

**Comment by jonfroehlich** [comment]
@misaugstad, we may want to prioritize this one in an upcoming release. Thoughts?

**Comment by misaugstad** [comment]
@jonfroehlich is it necessary to be able to specify the order of the streets that the user will be routed down?

Our algorithm already tries to send users through a contiguous route, so I don't think that the ordering is important to specify (it would mostly complicate the UI at this point). But if the use cases we already have involve the ordering being really important, then of course we should think about how to incorporate that!

The tool is going to look a bit different from your mock up video, because users need to be choosing from the selection of streets that we have available. So the "drawing" aspect doesn't make as much sense. I have it set up now so that users can essentially pick a set of streets that they want as part of their route. Here's what it looks like rn:

https://user-images.githubusercontent.com/6518824/214450985-b54a9d8c-ccb6-4695-9f0c-d188740b347e.mp4

**Comment by jonfroehlich** [comment]
I like this! Neat! Great work Mikey.

- Should we enforce that the streets must be connected as part of specifying a route?
- Do you think we should enforce directionality or order as you suggest? Maybe we talk to @devonsnyder and Yochai about this?
- Once you choose the streets, how do you as a user: (1) choose to explore that route (as a mission); (2) sharing this route with others. Relatedly, how do you view and choose existing routes that have been created?

**Comment by misaugstad** [comment]
>Should we enforce that the streets must be connected as part of specifying a route?

I don't think that's important! And it doesn't cost us any dev time to let them do that.

>Do you think we should enforce directionality or order as you suggest? Maybe we talk to @devonsnyder and Yochai about this?

Agreed that we should talk to them. I don't think enforced order or directionality matters unless it's for a paper where you want to control for that. Someone might want to demo where everyone follows the exact same route as well I suppose. But at that point they could just make a one-street route so that everyone does the same thing :grin: 

>Once you choose the streets, how do you as a user: (1) choose to explore that route (as a mission); (2) sharing this route with others. Relatedly, how do you view and choose existing routes that have been created?

I haven't actually ironed out any of those details yet! :grin: I was just thinking that there is some UI element in the top-right corner with buttons for saving / exploring / sharing the route. Maybe it also shows the total length of the route as you're creating it. Haven't thought through how someone would look through existing routes though!

**Comment by jonfroehlich** [comment]
Gotcha. We are aligned.

> I haven't actually ironed out any of those details yet! 😁 I was just thinking that there is some UI element in the top-right corner with buttons for saving / exploring / sharing the route. Maybe it also shows the total length of the route as you're creating it. Haven't thought through how someone would look through existing routes though!

Great. Those things sound good. Let's keep it as simple as possible for now in the spirit of MVP and shipping something.

**Comment by misaugstad** [comment]
I forgot to mention one technical constraint: It is much more difficult to allow routes that span multiple neighborhoods. We make a lot of assumptions that stem from an Explore mission being confined to a single neighborhood. It's certainly possible to generalize and work around this, but it would take some time. My assumption is that, for an MVP, we just restrict a route to a single neighborhood.

>For the question about directionality, would allowing users to choose the direction of travel make comparing labels on a route difficult?

When we are saying that users would get to choose the direction, we mean that when creating the route, you specify the direction for the route, which would ensure that users always go in the same direction. And comparing their audits is exactly why we were asking if having it be consistent was important!

>Another thing that comes to mind is naming convention when saving routes. I could see a world where a user has a bunch of Route1, Route2, Route3, which might be confusing to search for and share.

That's a good point, and I'll think about it a bit... At the very least maybe I'll just give the option to rename the routes in case it gets unruly :grin:
