### ISSUE TITLE
Defaulting to all data when no bounding box supplied?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3081]
I think a common case when using our APIs is to retrieve *all* data for a given city rather than just a subset for a given bounding box. As now, we must supply a pair of latlng coordinates to define a bounding box.

I think we should make it so that if we don't supply any lat/lng coordinates, then we return all data collected in the city.

For example, https://sidewalk-amsterdam.cs.washington.edu/v2/access/attributesWithLabels would return all data in Amsterdam. I'm giving the example for attributesWithLabels but it's actually the case with all of our APIs (except for General Project Sidewalk Stats API and Users API).

![image](https://user-images.githubusercontent.com/1621749/204344871-98ff6fc4-c6cf-4fcb-a320-ef3a099e208c.png)

**Comment by misaugstad** [comment]
Just to bring the rest of our conversation into this thread: When making the API endpoints, I had considered doing something like that. I chose not to because getting data for the entire city ends up returning a HUGE dataset, especially for cities like Seattle and SPGG. I didn't want that to be the default, or for someone who is unsure of how to use the API just trying an empty API call over and over, causing our servers to crash or something :sweat_smile: Though I 1000% agree that this is a much easier UX...

**Comment by misaugstad** [comment]
Closing in favor of #3236
