### ISSUE TITLE
Validate mission tutorial looks really bad at high zoom level

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3103]
##### Brief description of problem/feature
Right after pushing to the test servers, I happened to look at it on one where I was zoomed in at 150% browser zoom, and it looked like this! :joy: 
![Screenshot from 2023-01-06 12-27-51](https://user-images.githubusercontent.com/6518824/211094439-feddbb64-f5ab-4c67-b1c9-b92d6f98cd4e.png)

Looks fine back at 125% zoom!

**Comment by jonfroehlich** [comment]
Good catch! I think I generally do 150% on my desktop! 

Curious how many folks do, however :)

**Comment by hoominchu** [comment]
Oops! I will take a look at this. Sorry about that!

**Comment by jonfroehlich** [comment]
Just a note that I checked, and I believe I commonly do 125% Zoom rather than 150% on my desktop.

Also, I checked with 150% Zoom and this mission screen, at least, looks great (at 150%)!

![image](https://user-images.githubusercontent.com/1621749/211155401-084c115c-7ed0-441c-9e3d-56b941f5f1af.png)

Here we are at 125% (still good!)

![image](https://user-images.githubusercontent.com/1621749/211155427-3a4a5538-c1d7-484a-8152-bf12f8f22568.png)
