### ISSUE TITLE
Adding a URL column to the recent labels table that lets us see the labels in the GSV scene

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#317]
Idea is to make another column that is a url that, when clicked, takes you to the location in GSV for that label. We could implement this in two stages:

Stage 1 - Easy: When you click on URL, you're taken to the location of the label and you are looking in the same direction as that label; however, the labels from that user are not actually visible.

Stage 2 - Harder: When you click on the URL, you're taken to the location of the label but you can see all the labels from that user in the GSV scene--the label that corresponds to the one you clicked in the URL is highlighted in some way.

Refer: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/222
Related: #151

**Comment by Soben713** [comment]
Just submitted the pull request for this. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/1576529/19827159/2829e926-9d6e-11e6-8f1d-f60ab635e901.png)

**Comment by Soben713** [comment]
I just added a link to the task ID in which the label was added:
![image](https://cloud.githubusercontent.com/assets/1576529/19827223/952f667a-9d70-11e6-90b5-05438f4153f3.png)

After clicking on the link, you'll be taken to the task page. Remember that this is the task page:
![image](https://cloud.githubusercontent.com/assets/1576529/19827236/bcc7ec34-9d70-11e6-8ee7-46133e3ce31b.png)
Since we added the panorama view in this page, we can now simply observe every label added by the user in that street segment. With this update, I don't think stage 2 is needed.

@manaswis @jonfroehlich let me know what you think.

**Comment by jonfroehlich** [comment]
Great work on this guys! Exciting!

I have some feedback but would be better over face-to-face conversation where we can sketch together, etc. 

I still think we need something that quickly pops up when you hover over labels in the top-down map interface (using an interaction technique called 'brushing'). https://github.com/ProjectSidewalk/SidewalkWebpage/issues/151 briefly mentions this but perhaps it needs to be it's own ticket. The idea here is that as you move your mouse over labels in this interface: 
![image](https://cloud.githubusercontent.com/assets/1621749/19829835/70b01f6c-9db9-11e6-91dc-14a72cc87bef.png), a window (similar to the one you designed above but likely more compact) showing a picture with the label would pop up.

Oh, and I just noticed that there is no year in the timestamp. Also, it has '48768'--what does that mean? Finally, perhaps good to also translate this timestamp into an age (e.g., Label Age: 2 mos, 2 days)

![image](https://cloud.githubusercontent.com/assets/1621749/19829859/bcfc6740-9db9-11e6-80fe-8e30707f7434.png)

**Comment by Soben713** [comment]
I'll work on the map version but I don't think it works well on hover, my suggestion is to make the map clickable. Mainly because it takes ~1 second to receive the data from the server and render it for every label (it runs a huge query to aggregate all the necessary information) and it would be too slow to work well on hover.

Good suggestion about including the label age instead of the timestamp. I am not exactly sure what that number in the date shows, it is javascript's default date formatting.

We can push this to server after the code I added is reviewed and merged to the master.

**Comment by jonfroehlich** [comment]
I was worried about lag for hover. Click is fine. 

Re: label age. I would prefer both timestamp and label age. They tell you two different things.

Re: when is the code review?

**Comment by Soben713** [comment]
I'm afraid about the space being used if we include both the timestamp and the age in individual rows. Maybe we can update the timestamp value to include the age as well, like:

**Time Stamp:** Sat Jul 13 01:14:40 EDT (2 months ago)

And I don't know when @manaswis will be able to review the code but it probably won't take so much time because she already knows how it works.

**Comment by jonfroehlich** [comment]
I like that. We need year in there.

**Comment by Soben713** [comment]
Just added a commit to the same branch, the map is now clickable and the same modal is shown after clicking on a label. Also changed the content of the modal a little bit (added username and updated the time)

![image](https://cloud.githubusercontent.com/assets/1576529/19834223/46c80510-9e2d-11e6-9cbb-06f8704a16fe.png)

**Comment by manaswis** [comment]
This looks awesome! I have reviewed and merged it with the master.

@Soben713 Can you create the distribution and push it to the server? I won't be available before evening tomorrow to do it.

Thanks!

**Comment by Soben713** [comment]
@manaswis Yeah will do it.

**Comment by Soben713** [comment]
This is now deployed. :)

**Comment by jonfroehlich** [comment]
Great, I'll check it out!

We may want to think about deploying some of these things to Access Score and to the user's dashboard (since they all have the label dots on a map).
