### ISSUE TITLE
Add bounding box lng1, lat1, lng2, lat2 to API page for each city

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3236]
I wanted to download the full dataset for [Oradell ](https://sidewalk-oradell.cs.washington.edu/developer) today but then noticed I had to supply a bounding box that encompassed the full city boundary. Unfortunately, the API page does not include such a bounding box—which means that every developer would have to go find this info on their own and then plug it in.

I propose that, for each city, we state somewhere on the API page what the current city's bounding box is—perhaps listing it right here since it's most relevant.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/eeb6fad5-901e-433b-87b2-a63b96d83fd1)

We could also consider defaulting to the full city if no `bbox` is supplied (my guess is @misaugstad won't like this as it could create unnecessary load on our servers).

Jon

**Comment by misaugstad** [comment]
Agreed, we should at least make it so that everyone doesn't have to figure it out for themselves! Though you're right that I don't want the entire city to be the default. Both because of the load on our servers, and because I think that having the default give you a quick result that is easy to look through is probably helpful for users. Especially since we don't have good formal documentation yet (#2754).
