### ISSUE TITLE
Email address for login is case sensitive- document or remove restriction

### ISSUE THREAD

**Issue by rbracket** [ProjectSidewalk/SidewalkWebpage#326]
my email login is Sssss@xxxx.xxx

Often case in an email login does not matter.  I've often wondered if this is just a convention, or a known requirement.

Anyway, when I created my account from my iPad, the First character of my login was set to uppercase.  I did not change.   Later, when trying to access my account with my email address all in lower case, I was not able to login.

If ProjectSidewalk checks for case in email addresses, please mention this in the FAQs and when people initially setup accounts.

**Comment by jonfroehlich** [comment]
Thanks for this @rbracket. I agree that login should be case insensitive.

Also, unfortunately we do not yet support touch screens (iPads, Android tablets, smartphones) with our interfaces--as I'm sure you noticed. :( 

Lots more work to do! Thank you for your help in making our tool better!

**Comment by Soben713** [comment]
I found another related issue.

It is possible to sign up with the same email many times only if you change the email's case. If we are going to make it case-insensitive, then it is also necessary to prevent this. Otherwise, it would be impossible to login to such accounts.

**Comment by jonfroehlich** [comment]
Yes, this should be fixed.

**Comment by misaugstad** [comment]
this caused another issue recently because someone signed up with "Gmail.com" and then wasn't able to sign in with "gmail.com" :'( would love to get this fixed soon!

**Comment by misaugstad** [comment]
@SahilS1203 is working on fixing this issue for new users that sign up (and making signing in case-insensitive for all existing users).

I only found 6 instances of users that have signed up with the same email address with different cases. Given how few of those cases we have, I think that I'm just going to manually go through and pick which account they will be allowed to log into going forward; I think that in all cases, it's the account that they have both contributed more data into and logged into most recently, which makes the decision really easy.

I found the users with duplicate accounts using this query in each city:
```
SELECT COUNT(*), LOWER(email)
FROM sidewalk_user
GROUP BY LOWER(email)
HAVING COUNT(*) > 1;
```

I think that one of the easiest ways to "invalidate" one of the accounts is just to edit their email address in the `login_info` table. Maybe we do it in the `sidewalk_user` table as well for consistency. I don't want to delete their old account completely, both because that's difficult to do, and because it would be deleting good data.
```
UPDATE sidewalk_user SET email = '<new-dummy-email>' WHERE email = '<old-email>';
UPDATE login_info    SET email = '<new-dummy-email>' WHERE email = '<old-email>';
```

I'll wait until @SahilS1203 finishes their fix so that I can test out this method on my local dev environment first.
