### ISSUE TITLE
Something is really wonky with validations

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3261]
I've observed three buggy things... perhaps this is related to the recent validation mission fix (where we tried to insert validation mission screens every time if a user was validating a different label type).

Here are the problems I've observed... all pretty serious and captured on the attached video:

1. The mission start doesn't match what you end up actually validating
2. The validation mission label type gets switched out midstream
3. The validation appears to auto-advance

Here's video evidence (three examples so far):
* https://youtu.be/o0AKk1xVoiI
* https://youtu.be/Xglu1Ak2tI4
* https://youtu.be/10tX54UmJX4
* https://youtu.be/trj1-bvyvwg (weird one, happens right away in second mission; skips first validation!)
* https://youtu.be/XbFwUVdvU50 (happens right after first mission; this is the one I stopped on for Mikey to investigate backend; not shown in the video is the fact that I did click 'agree' on the first surface problem shown but i did not record this in the video)

**Comment by misaugstad** [comment]
@jonfroehlich is this happening every time for you? Or multiple times and that's why you caught it on video? Any more info about the situation? Thought I'd be able to reproduce it immediately but couldn't

**Comment by misaugstad** [comment]
From the video, it looks like your 'Continue validating' button is never disabled! It's supposed to be disabled and show a 'wait' cursor until everything gets updated for the new mission. From your video, it is never disabled. When I'm testing, I can't press the 'Continue validating' button for at least a second or two. What's the browser and OS you're using?

**Comment by jonfroehlich** [comment]
OK, based on our Slack discussions and further investigations, we believe this: appears to only be on the Seattle server and possibly only affecting me. Notably, I have over 10k validations on the Seattle server so maybe it's causing some strangeness in terms of timing.

Here's another video: https://youtu.be/Xglu1Ak2tI4

**Comment by jonfroehlich** [comment]
OK, I was able to trigger the problem using Incognito mode in Seattle, so it is not isolated to my account (e.g., because I have so many validations)

**Comment by misaugstad** [comment]
Update: the issue is that we can sometimes send two batches of data to the back end when a user completes a mission, and they are both sending data back for different missions. Then they are stepping on each other and causing these issues!

The solution is to have a specific "mission complete" flag that we make sure that we only send once. And we only prepare and send back data for a new mission when the back end gets this flag.

**Comment by jonfroehlich** [comment]
Awesome. Great sleuthing and debugging Mikey. Can you help me understand why we would send two batches of data when the user completes a mission? And sending data back for different missions? I just don't understand why this is happening with our architecture... is it due to async uploads? What would happen if user closes browser?

**Comment by jonfroehlich** [comment]
Also, do you know if this led to any data loss or corrupted data (e.g., validations getting associated with the wrong thing)

**Comment by misaugstad** [comment]
>Also, do you know if this led to any data loss or corrupted data (e.g., validations getting associated with the wrong thing)

I do not believe that it did! From the situations I looked at, everything seemed good. It's likely that the occasional validation was made for the wrong label when the label switches out from under you as you were rating that first label in a mission. But the data should primarily be in a good place!

>Can you help me understand why we would send two batches of data when the user completes a mission?

We send one back when a user completes a mission. We also send data back whenever we get 200 interactions logged, we were filling up with 200 interactions frequently enough that this would trigger around the end of a mission too. It's likely that one of those two batches had very little data to log, but both batches would indicate that the user finished the mission.

>And sending data back for different missions?

The back end's logic was essentially "if the current mission is complete, create a new mission and send it". Since both of those batches said that the mission was complete, the back end would create a new mission on two separate occasions.

My fix for this makes it so that we only tell the back end that the mission is complete if it was our dedicated logging that comes with ending a mission. Even if the mission is complete, we are no longer saying that that is the case when we send data just from hitting 200 logs.

**Comment by jonfroehlich** [comment]
Got it. Thanks!
