### ISSUE TITLE
Add Verizon as an organization to Project Sidewalk Seattle

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3312]
We've been asked to do this a few times but it's slipped through the cracks.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/a21014e6-980a-4bae-a3de-112472bfd262)

And another request from Jul 7:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/53d97464-5f4c-4fc1-a6c8-72d01acb5e65)

@misaugstad, can you get this quick one done today? (I assume it takes like ~5 minute, ha!)

**Comment by jonfroehlich** [comment]
Aha, they are actually working on the Oradell, NJ location:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/6ba1890d-eb44-4dff-8dbd-3469c495b872)

So, wonder how/if we can just apply Verizon to a variety of cities (should it just be US or all sites?). Hard to know how to handle this.

Ultimately, I still lean towards allowing end-users to sign up for their own organizations.

**Comment by misaugstad** [comment]
I actually added the Verizon org to all public deployments (the ones you can see from the dropdown in the navbar) on July 7. They didn't do a reply all so you didn't see my responses either.

Not sure why this new user is having an issue, because the org is listed. I'll email them to help troubleshoot.
![Screenshot from 2023-07-24 11-30-27](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/6518824/130086ea-d8d6-4b09-a1f6-5e5a783d901a)
