### ISSUE TITLE
In user profile (or dashboard), make it so users can create an organization

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3313]
As discussed here (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2338#issuecomment-776769593), it would be nice if users could create their own organizations. Could they do this in their own dashboard/profile screen? This would take care of cases like https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3312.

Easiest would just be to allow a person to join one and only one organization (I mention this because of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2338#issuecomment-777777882).

Similarly, it would be nice if users could see their own usernames and emails (and possibly change this information)

**Comment by misaugstad** [comment]
@aslassi777 let's have you work on this one next! It will involve some full stack work! I'm thinking that we should maybe just edit the look of this so that the org itself is part of the drop down menu instead of having it in an "edit" button..? We had a user emailing last week being unsure of how to change their org. And I realize that the UI we have right now isn't standard. But I'm also worried about it not looking as nice...

Anyway, thinking it would look more like these drop downs that we have on the admin page:
![Screenshot from 2024-10-10 11-51-32](https://github.com/user-attachments/assets/1033c9f0-b16e-4109-af4a-7cfe953a065e)

And then we would need to add the ability to create a new org as well!

**Comment by aslassi777** [comment]
Sounds good @misaugstad, will take a look at this over the weekend and probably get started on it!

**Comment by aslassi777** [comment]
@misaugstad Just making sure, so instead of edit, you want the button to have a dropdown of the org **type** and then the org **name**? Would it potentially make sense to have one dropdown that showcases the **current org they are in**, and then if they click on another org in the dropdown, it switched them to that org? And then the last dropdown would be the leave current org button... if they click the button and they are not in an org, then the button will display "Not in org, use dropdown to select". Does this make sense?

**Comment by misaugstad** [comment]
>you want the button to have a dropdown of the org type and then the org name?

We don't have a notion of an org type, so not that!

>Would it potentially make sense to have one dropdown that showcases the current org they are in (it would say "Current Org:" and then display the dropdown, and then if they click on another org in the dropdown, it switches them to that org?

This sounds more like what I was suggesting!

>And then the last dropdown would be the leave current org button...

If by "last dropdown" you mean "last option in the dropdown" then yes! Right now it's the first option... Not sure whether we want it to be first or last tbh... In Chicago, for example, we have a ton of orgs bc class sections were split into different orgs, so there are a lot of options. Makes it nice to have the "Leave org" button at the top.

>Not in org, use dropdown to select

Probably looking for something more inviting like "Join a team!" -- Let's actually move towards the "team" wording on the user-facing side at this point!

>I could also foresee a "Create new org" button to the right of this dropdown that would prompt the user to create the org, add it to the dropdowns and automatically switch them to that org. Does this make sense? (at least for me, this seems to resemble the "standard ui" in this case)

Do you have any examples where this is the UI that's used? I was imagining it more like the last option in the dropdown being a "create your own team" button. Was thinking of the flow as users looking through the list to see if there is a team that they want to join, if they get to the bottom of the list and there isn't one then we have the button right there to create the new team. Thoughts?

**Comment by aslassi777** [comment]
I like those suggestions a lot @misaugstad. I'm thinking leave org button stays at the top of the dropdown. Create org also at the top, above leave makes the most sense to me. And if no team, it will say join a team! as you mentioned. It should show all of the teams available to join and the create/leave buttons at the top of the dropdowns as usual. Also, might be a nice touch (the team they are currently on should have a checkmark next to it on the dropdown). Does this sound good? Sorry just want to clarify before getting started!

**Comment by misaugstad** [comment]
>Also, might be a nice touch if the team they are currently on has a checkmark next to it on the dropdown

Should def do smth like that, yeah!

**Comment by aslassi777** [comment]
Alright sounds good, I'll go ahead and get started

**Comment by aslassi777** [comment]
@misaugstad I've finished most of the basic implementation/renaming, but how should I handle creating teams? I have the create team dropdown and I see that Progress.js is what's used to handle leaving/joining orgs but I don't know how to go about handling a request to create the organization.

**Comment by misaugstad** [comment]
>how should I handle creating teams? is it just a matter of adding to the orgs table?

I think so, yes! I assume that you'll need to make a new endpoint to handle that since as of now we can only create teams if I manually run a query on the db!

And if you have any visual progress to show, that would probably be a good idea! Then I can give you some feedback on the design in case there are changes to make there. The user dashboard is one of our nicer looking pages, so we definitely want to make sure that this looks good!

**Comment by aslassi777** [comment]
Yup! Makes sense... I need to actually handle creating orgs since my local host has no orgs I can choose from, but as soon as I figure this out I will send over... 

![Uploading Screenshot 2024-10-14 at 3.01.14 PM.png…]()

**Comment by misaugstad** [comment]
Nice, thank you! Looks like we can remove the tooltip at this point, since the UI should be more self-explanatory now!

And I think the idea is to get rid of the "No team:" bit, and just have the drop down and that's it?

**Comment by aslassi777** [comment]
Yup perfect! Just implementing create organization now!

**Comment by aslassi777** [comment]
@misaugstad how does this look? 


<img width="1512" alt="Screenshot 2024-10-14 at 6 38 59 PM" src="https://github.com/user-attachments/assets/97163210-f907-44a9-98b0-0b749a180e4e">

**Comment by misaugstad** [comment]
I'm happy with the form, glad that it uses the same UI as the sign in form and such!

>might also want to bold the leave and create dropdown options

Yeah probably something... whether it's bold or italics or something...

**Comment by aslassi777** [comment]
@misaugstad sounds good... I'll get finishing touches on it here in a day or two and have it pushed out for review. I'll try and rename things and make sure all the languages are switched in advance this time haha!

**Comment by misaugstad** [comment]
Since you're talking about finishing touches & translations, a quick set of edits after looking at the text more carefully:
* Create team -> Create a team OR Create a new team
* Leave team -> Leave \<curr-team-name\>
* Team Name -> Team name
* Team Description -> Team description (optional) OR indicate that only the name is required in some other way -- if no description is provided, just fill in with an empty string
* Create Organization -> Create team
* Close -> Cancel
* In the modal where you create the team, the X in the top-right corner should be higher up
* I think I like the leaving a team option being before creating a team... That way all the ways of joining a different team are bunched together

**Comment by misaugstad** [comment]
And since users can now create their own teams and then display them on other users' browsers, when displaying team names/descriptions, let's use the new `escapeHTML` utility function that @jsomeara added to prevent malicious code being run!

**Comment by aslassi777** [comment]
Sounds good! I'll make these changes and try to get it pushed out for you to review tomorrow.

**Comment by aslassi777** [comment]
Okay @misaugstad. I think I've made all the changes we talked about... I'm going to push code in a bit, and let me know if anything needs more work (I made changes to a lot of files, so there might be something I missed)
