### ISSUE TITLE
Training Server for first few missions

### ISSUE THREAD

**Issue by yeisenberg** [ProjectSidewalk/SidewalkWebpage#3317]
##### Brief description of problem/feature
Suggestion for training server to be used for training new raters

##### Design ideas & mockups
Suggestion to set up a training server that would be used for training sessions. This can be used for sessions where people are doing like their first 5 or so missions. I imagine that people's first 5 missions are their worst in terms of reliability. Having them work on this training server first, get feedback from validations could help improve rater quality and let people feel like they can 'play' with the tool and not feel pressure of it being used or getting it wrong. This may also be explained to cities as another enhancement to rater quality.

**Comment by misaugstad** [comment]
@yeisenberg how would you consider this to be different from our test servers like sidewalk-chicago-test.cs.washington.edu? Is it that we would be expecting users to try their best on this training server (so we don't use it for stress testing)? I suppose that could help to ensure that we are validating labels from actual users if we do validations on said training server.

One issue is the differences in infrastructure across the world. If we make a training server in the US context, that likely wouldn't be useful in Amsterdam or Quito, for example.

**Comment by yeisenberg** [comment]
@misaugstad , I don't think i knew of the test servers! But that could maybe work? was thinking that it can serve as a way to Get raters to a certain level of reliability before they collect data on the main server for a city and that they get to practice on it without affecting the larger dataset from that City.  If they can do those kind of practice missions on the test server that would be great. Good point on the different infrastructure around the world. is there a way to set up different test or training servers for different countries?

**Comment by misaugstad** [comment]
>is there a way to set up different test or training servers for different countries?

Right now we have a test server that accompanies nearly every production server (just add -test) to the URL! I think we have it everywhere except for the validation study server. So I kind of think that this process that we already have makes sure that we have test data that people can use regardless of the city!

Though of course if we created dedicated training servers, we could make a bunch of them with data from different countries. Or we could just throw the data from all different countries onto one training server, assuming that there is someone around to help guide users to the correct part of the world on that training server.

**Comment by yeisenberg** [comment]
Hmm, interesting. Will try to think about what else would be unique about a training server vs. test server. Perhaps, it is more about us creating a standardized approach to training, where we first use the Test Servers and then the main servers after validation of 2-3 missions. I realize we're 'losing' data that could be going into the City's main dataset, but thinking this can help improve quality. Much of it based on our experience yesterday with a group that was doing what i'd say was pretty low-quality rating.

**Comment by misaugstad** [comment]
I do think that that's likely a good approach. I have had a lot of similar experiences when training high school volunteers. I often wish that I could ask them to just create a new account after their first 2 hours of work so that I can mark all their old work as low quality and they can start fresh.

**Comment by yeisenberg** [comment]
Right, I hear that. And with the highschoolers with disabilities that we were working with yesterday, it seemed to happen that it was easier for them to focus on one type of label at a time. So with the test server, if they do a mission and just focus on one type of label, than that is also not affecting anything with missing labels. That might work out very nicely, for us in training to do each label and then have them practice one where they combine them all. That also might depend on individual learners and what they feel comfortable doing. Maybe we will try that in our next session.

**Comment by misaugstad** [comment]
I like that!

**Comment by jonfroehlich** [comment]
_My apologies but I wrote this draft but then was disrupted by a meeting, so didn't finish. Still posting here._

Hmm, interesting idea. We already have a sibling test server for every production server in every city (so that part is easy). However, because of the way our test servers work, people would have to create two accounts: one per server, which could become confusing.

Moreover, I might lean towards this idea: let us adopt a philosophy where it's OK to make mistakes--even on production--when you're first learning how to label. That's OK! We should craft our user experience to help people grow, learn, and get better. 

I think it's fine to have people get training and start labeling on a production server--and then we can even watch (study) their growth and ability over time.

But I'm also OK with facilitators using test servers, if they'd prefer, for their training sessions. Just note that users will have to create two accounts then.

-----

OK, now responding to the current thread, which has updated significantly since @yeisenberg's first post.

I guess I'm fine with folks using test servers for training if that gives them a "safe" space to train and play. 

It's also an interesting idea to think of missions where people are supposed to look for just one type of problem. I could see how this dramatically simplifies the labeling task; on the other hand, this would come with at least a ~5x or 7x cost. So, in that regard, I would hope that we could come up with a better approach that balances efficiency, simplicity, and accuracy.

**Comment by misaugstad** [comment]
>I think it's fine to have people get training and start labeling on a production server--and then we can even watch (study) their growth and ability over time.

I do think that this is the best long term plan, but I would like to have better tooling for discounting users early work if it's sub-par (#2508). I think that right now, having users start on the production servers is ultimately contributing to poor quality data more than user confusion about making a second account.

The confusion about making a second account is the reason why I would only want to do this in a controlled setting where one of us is running a mapathon/training, for example.

**Comment by yeisenberg** [comment]
Great points Jon! Definitely understand the balance. If we can try to test out the training high-schoolers/newer users on one label type missions i think that could be interesting and then perhaps see if that gets folks to a better place than it may be worth while? It may get more users invested in continuing with it as they feel that 'sense of growth.  I could see how new learners vary across the spectrum of being comfortable with multi-label missions. I think the one-label missions just offers the differentiation to those that need a slower pace and then those who are more comfortable can perhaps skip that part.

**Comment by jonfroehlich** [comment]
Thanks @yeisenberg. Are you proposing that we design a new mission type that only has people label one and only one thing at a time (and only shows one button in the labeling UI as a result)? 

So, for example, we'd have a mission to "_Label all the curb ramps_" and the UI would look something like this:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/9b7afa61-7f30-42b4-9757-0581a86cda50)

**Comment by yeisenberg** [comment]
Right, that was the mission i was thinking, but was not necessarily needing to design a new mission interface, but just instructing them to just use one label at a time. Like the sequence could be to describe a label and how to label it and then do a mission for that label. Was assuming such new mission types would be a big lift?

**Comment by jonfroehlich** [comment]
Yes, it would take time/effort to implement such a new design/mission type. And it's not yet clear to me if it's worth that effort. :)

But, of course, you could do just as you suggest right now--but if you do that, I'd strongly advise you to only do it on the test servers. If they did this on the production server, they would be marked as low quality by our algorithm.

**Comment by yeisenberg** [comment]
Right, sure. Yes, that is what I was thinking. focus those single -label missions on the test servers. thanks.

**Comment by misaugstad** [comment]
Closing this discussion since it sounds like there isn't enough reason to create new training-specific servers that are separate from our test servers.
