### ISSUE TITLE
projectsidewalk.org URLs aren't successfully forwarding

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3427]
##### Brief description of problem/feature
URLs like projectsidewalk.org, https://taipei.projectsidewalk.org/, etc. are not working. Getting an `ERR_CONNECTION_TIMED_OUT` error.

@jonfroehlich set these up. As far as I know, I don't have access to these. But @jonfroehlich let me know if I actually do so I can troubleshoot if things go awry in the future as well!

**Comment by jonfroehlich** [comment]
I'm not sure what is up. I was able to (easily) replicate the problem.

Chatting with dreamhost support team now.

<img width="786" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/80c6df63-398f-437e-a996-bbe12413c78e">

<img width="505" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/27720471-b82a-4978-a4f1-3435a74d6e46">

**Comment by jonfroehlich** [comment]
The problem is that the Dreamhost redirect server was retired and they never let us know that. Doh. 

I asked them to switch each redirect url over. I suppose we could do this manually if they don't finish soon.

Here's the chat transcript:

Chat started on 26 Nov 2023, 02:15 AM (GMT+0)
--
(02:15:13) | *** Jon Froehlich (jonfro3) joined the chat ***
(02:15:13) | Jon Froehlich (jonfro3)Category: Domain RegistrationDomain: projectsidewalk.orgSubject: Redirect for projectsidewalk.org brokenThe redirect for http://projectsidewalk.org/ and all subdomains like chicago.projectsidewalk.org stopped working. Can you help us fix this?
(02:15:17) | *** Cherry E joined the chat ***
(02:15:18) | Jon Froehlich (jonfro3)Category: Domain RegistrationDomain: projectsidewalk.orgSubject: Redirect for projectsidewalk.org brokenThe redirect for http://projectsidewalk.org/ and all subdomains like chicago.projectsidewalk.org stopped working. Can you help us fix this?
(02:15:49) | Cherry EHi Jon! Thanks for contacting DreamHost Support! I’ll be happy to assist you today.
(02:15:51) | Cherry EAllow me to have a look. Please bear with me.
(02:16:17) | Jon Froehlich (jonfro3)Thank you!
(02:20:04) | Cherry EThank you for waiting and for this one, let me connect you to our dedicated support to help further check and help on this, please stay on the line
(02:20:19) | Jon Froehlich (jonfro3)Thank you
(02:20:31) | *** Cherry E has transferred chat to Domain Registration ***
(02:20:36) | *** Camille F joined the chat ***
(02:20:45) | Camille FHello Jon, thanks for contacting DreamHost Support! My name is Camille, I'll be happy to assist you. One moment while I pull up your account.
(02:20:57) | *** Cherry E left the chat ***
(02:24:37) | Jon Froehlich (jonfro3)Thanks Camille
(02:26:42) | Camille FI am sorry that you are having trouble with the redirects. Please allow me a few minutes to check this further.
(02:27:16) | Jon Froehlich (jonfro3)Thank you
(02:33:21) | Camille FHello Jon, thank you for waiting. It looks like the server connected to the Redirects has been removed. In this case, it is highly recommended to re-add the Redirects once again so that it will be placed to an active server.
(02:34:22) | Jon Froehlich (jonfro3)I don't understand. The server that projectsidewalk.org points to is https://sidewalk-chicago.cs.washington.edu/ and that website is up and alive
(02:37:51) | Jon Froehlich (jonfro3)Similarly, teaneck.projectsidewalk.org points to https://sidewalk-teaneck.cs.washington.edu/ and that server is up. I have checked that the destination locations for the redirects are alive.
(02:38:00) | Camille FI am referring to the redirect server and not the destination website.
(02:38:17) | Camille FIt need for to Re-ADD the redirect.
(02:38:28) | Jon Froehlich (jonfro3)Ah, ok, why would I need to do this?
(02:38:32) | Camille FMeaning, deleting them and adding it again.
(02:38:44) | Jon Froehlich (jonfro3)And how would I know that I am supposed to do this? Did Dreamhost email me?
(02:39:10) | Camille FLooks like there was no email about this. Sorry about that.
(02:39:19) | Camille FI can help you re-adding the redirect instead
(02:39:31) | Jon Froehlich (jonfro3)I also don't see anything on my dashboard or in my notifications that this redirect server was going away
(02:39:43) | Jon Froehlich (jonfro3)Can you just automatically update all of my redirect entries please?
(02:40:10) | Camille FI'm afraid that it needs to be done manually
(02:40:23) | Jon Froehlich (jonfro3)OK, can you do it manually then?
(02:40:32) | Camille FYes
(02:40:38) | Camille FI am doing it now
(02:40:45) | Jon Froehlich (jonfro3)Thank you
(02:40:53) | Camille FPlease bear with me
(02:44:23) | Jon Froehlich (jonfro3)Could you also tell me how to do it so I can replicate in the future?Also, just FYI: I am on an international flight right now and might lose Internet connectivity.
(02:45:43) | Camille FIf a timeout error occurs, it normally caused by the DNS. So we need to check if the DNS is propagating and the server connected to it is up.
(02:46:12) | Camille FIt looks like there are several domains listed on this account that needed to re-add the redirect.
(02:46:19) | Camille FWould it be okay if I move this to a ticket?
(02:46:27) | Camille FOnce complete, I will send you an update via ticket.
(02:47:52) | Jon Froehlich (jonfro3)Yes, please do so. We have actively advertised these .org urls so it's critical that this gets fixed. People think our websites are down when, in fact, it's just the redirect that is broken.Many thanks. Please open the ticket and I will follow asynchronously
(02:47:58) | *** Jon Froehlich (jonfro3) has rated the chat Good ***
(02:48:05) | Camille FI have created a ticket for this Ticket: 12734875
(02:48:18) | Camille FYou can contact us back in case you havent heard from us.
(02:48:28) | Camille FIn the meantime, is there anything else I can assist you with?
(02:48:28) | Jon Froehlich (jonfro3)Thank you Camille. Our plane is beginning our descent so losing Internet soon
(02:48:37) | Jon Froehlich (jonfro3)No. Thanks.
(02:48:45) | *** Jon Froehlich (jonfro3) left the chat ***

Chat started on 26 Nov 2023, 02:15 AM (GMT+0)
(02:15:13)	*** Jon Froehlich (jonfro3) joined the chat ***
(02:15:13)	Jon Froehlich (jonfro3)
Category: Domain Registration
Domain: [projectsidewalk.org](http://projectsidewalk.org/)
Subject: Redirect for [projectsidewalk.org](http://projectsidewalk.org/) broken

The redirect for http://projectsidewalk.org/ and all subdomains like [chicago.projectsidewalk.org](http://chicago.projectsidewalk.org/) stopped working. Can you help us fix this?
(02:15:17)	*** Cherry E joined the chat ***
(02:15:18)	Jon Froehlich (jonfro3)
Category: Domain Registration
Domain: [projectsidewalk.org](http://projectsidewalk.org/)
Subject: Redirect for [projectsidewalk.org](http://projectsidewalk.org/) broken

The redirect for http://projectsidewalk.org/ and all subdomains like [chicago.projectsidewalk.org](http://chicago.projectsidewalk.org/) stopped working. Can you help us fix this?
(02:15:49)	Cherry E
Hi Jon! Thanks for contacting DreamHost Support! I’ll be happy to assist you today.
(02:15:51)	Cherry E
Allow me to have a look. Please bear with me.
(02:16:17)	Jon Froehlich (jonfro3)
Thank you!
(02:20:04)	Cherry E
Thank you for waiting and for this one, let me connect you to our dedicated support to help further check and help on this, please stay on the line
(02:20:19)	Jon Froehlich (jonfro3)
Thank you
(02:20:31)	*** Cherry E has transferred chat to Domain Registration ***
(02:20:36)	*** Camille F joined the chat ***
(02:20:45)	Camille F
Hello Jon, thanks for contacting DreamHost Support! My name is Camille, I'll be happy to assist you. One moment while I pull up your account.
(02:20:57)	*** Cherry E left the chat ***
(02:24:37)	Jon Froehlich (jonfro3)
Thanks Camille
(02:26:42)	Camille F
I am sorry that you are having trouble with the redirects. Please allow me a few minutes to check this further.
(02:27:16)	Jon Froehlich (jonfro3)
Thank you
(02:33:21)	Camille F
Hello Jon, thank you for waiting. It looks like the server connected to the Redirects has been removed. In this case, it is highly recommended to re-add the Redirects once again so that it will be placed to an active server.
(02:34:22)	Jon Froehlich (jonfro3)
I don't understand. The server that [projectsidewalk.org](http://projectsidewalk.org/) points to is https://sidewalk-chicago.cs.washington.edu/ and that website is up and alive
(02:37:51)	Jon Froehlich (jonfro3)
Similarly, [teaneck.projectsidewalk.org](http://teaneck.projectsidewalk.org/) points to https://sidewalk-teaneck.cs.washington.edu/ and that server is up. I have checked that the destination locations for the redirects are alive.
(02:38:00)	Camille F
I am referring to the redirect server and not the destination website.
(02:38:17)	Camille F
It need for to Re-ADD the redirect.
(02:38:28)	Jon Froehlich (jonfro3)
Ah, ok, why would I need to do this?
(02:38:32)	Camille F
Meaning, deleting them and adding it again.
(02:38:44)	Jon Froehlich (jonfro3)
And how would I know that I am supposed to do this? Did Dreamhost email me?
(02:39:10)	Camille F
Looks like there was no email about this. Sorry about that.
(02:39:19)	Camille F
I can help you re-adding the redirect instead
(02:39:31)	Jon Froehlich (jonfro3)
I also don't see anything on my dashboard or in my notifications that this redirect server was going away
(02:39:43)	Jon Froehlich (jonfro3)
Can you just automatically update all of my redirect entries please?
(02:40:10)	Camille F
I'm afraid that it needs to be done manually
(02:40:23)	Jon Froehlich (jonfro3)
OK, can you do it manually then?
(02:40:32)	Camille F
Yes
(02:40:38)	Camille F
I am doing it now
(02:40:45)	Jon Froehlich (jonfro3)
Thank you
(02:40:53)	Camille F
Please bear with me
(02:44:23)	Jon Froehlich (jonfro3)
Could you also tell me how to do it so I can replicate in the future?

Also, just FYI: I am on an international flight right now and might lose Internet connectivity.
(02:45:43)	Camille F
If a timeout error occurs, it normally caused by the DNS. So we need to check if the DNS is propagating and the server connected to it is up.
(02:46:12)	Camille F
It looks like there are several domains listed on this account that needed to re-add the redirect.
(02:46:19)	Camille F
Would it be okay if I move this to a ticket?
(02:46:27)	Camille F
Once complete, I will send you an update via ticket.
(02:47:52)	Jon Froehlich (jonfro3)
Yes, please do so. We have actively advertised these .org urls so it's critical that this gets fixed. People think our websites are down when, in fact, it's just the redirect that is broken.

Many thanks. Please open the ticket and I will follow asynchronously
(02:47:58)	*** Jon Froehlich (jonfro3) has rated the chat Good ***
(02:48:05)	Camille F
I have created a ticket for this Ticket: 12734875
(02:48:18)	Camille F
You can contact us back in case you havent heard from us.
(02:48:28)	Camille F
In the meantime, is there anything else I can assist you with?
(02:48:28)	Jon Froehlich (jonfro3)
Thank you Camille. Our plane is beginning our descent so losing Internet soon
(02:48:37)	Jon Froehlich (jonfro3)
No. Thanks.
(02:48:45)	*** Jon Froehlich (jonfro3) left the chat ***

**Comment by jonfroehlich** [comment]
OK, as of this morning, this is resolved. Sorry for the delay as I was traveling.

In sum, the Dreamhost redirect server hosting our redirects was retired. We were not notified. I worked with Dreamhost support to copy our settings over to a different redirect host. This morning, I added in SSL certificates so both http and https should work.

I'd like @misaugstad to test before closing.

Here's the most recent message from Dreamhost.

> Thank you for contacting the Dreamhost Support Team! Today you contacted
> us because you had problems with the redirects on this account. We are
> here to help you!
> 
> I would like to inform you that the redirects have been re-added and they
> are now working.
> 
> Feel free to reply anytime if you have any further questions or in case
> you need additional assistance. We'd be happy to help!
> 
> Please stay safe and healthy!
> 
> Regards,
> 
> Camille F

**Comment by misaugstad** [comment]
Looking good, thanks @jonfroehlich !!
