### ISSUE TITLE
Ensure that cropped images that we save are a consistent size

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3467]
##### Brief description of problem/feature
@hoominchu just added a feature that saves screenshots of the GSV when users add a label. But the dimensions of the image changes based on the user's browser zoom level. We can scale it after the fact, but it's probably best if we save them at a consistent size from the start.

**Comment by hoominchu** [comment]
If we want to resize images on the client side, we will have to process the canvas in order to resize the image.

1. [https://stackoverflow.com/questions/33033378/is-it-possible-to-download-canvas-as-image-with-custom-size](https://stackoverflow.com/questions/33033378/is-it-possible-to-download-canvas-as-image-with-custom-size)
2. [https://stackoverflow.com/questions/23481210/resize-the-canvas-output-image-to-a-specific-size-width-height](https://stackoverflow.com/questions/23481210/resize-the-canvas-output-image-to-a-specific-size-width-height)

Client side overhead should be avoided I think as we don't want this flow to affect or slow down user interactions.

We can try to resize the images on the server side before saving and this shouldn't affect the user flow. We may potentially be getting lower resolution images when the user is at negative zoom levels but I don't think we can avoid it without too much manipulation at runtime. Plus, if the user is on a Mac for example, we are getting the crops at 2x resolution, so even if the user is at 50% zoom level, we will still get the resolution we are currently need.

@jonfroehlich thoughts?

**Comment by misaugstad** [comment]
Agreed that if we do the resizing automatically, we should do it on the server side. Thanks for looking into it! Shouldn't be too hard to set that up async so it doesn't slow anything down for the front-end. 

And we should do it as long as we are not going to lose out on legitimate image quality by doing it... We don't lose image quality by scaling up, but do we lose any by scaling down? I'm assuming that zooming in past 100% zoom doesn't improve the image quality at all, I figure that it just gets scaled up. So I would think that scaling down doesn't cost us any image quality and we can do that safely.

**Comment by hoominchu** [comment]
Right, I just pushed a change that resizes the crops to 1440x960 which is 2x the actual GSV size since retina displays give us that resolution. In our current CV flows we are using 720x480 only so it should be okay and we will have higher resolution images if need them.

**Comment by misaugstad** [comment]
Would you be able to check if we are actually getting an image quality improvement by doing that compared to using 720x480? I expected that we would be bottlenecked by the GSV panorama resolution, and therefore wouldn't be getting anything out of the larger images from retina displays... Do you think that's the case? If we don't get anything out of it, I'd rather not artificially increase the size of the images for the sake of storage space and transfer speeds in the future, because we're going to end up with a TON of these!

**Comment by hoominchu** [comment]
Yes, there is a difference in the image quality. Here is an example. The actual resolution of the panorama image is much higher and it gets scaled down to the GSV window size and the display resolution I believe.

![crop_temp_seattle-wa_893010c1-c072-4b06-afe3-0a15dad15f5f_7_Obstacle](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/8168506/034a69a1-6cbc-41e4-ba4f-ac79f2a81c98)

![crop_temp_seattle-wa_893010c1-c072-4b06-afe3-0a15dad15f5f_12_Obstacle jpg](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/8168506/56706755-adf7-4948-b54c-ef9697f7458a)

**Comment by misaugstad** [comment]
Nice, thank you!

**Comment by jonfroehlich** [comment]
This got stuck in my outbox (and I also shared it on Slack) but putting here for consistency/archiving:

> There are lots of different algorithms for scaling down an image but all are lossy (because you literally lose pixels). I use ImageMagick’s backend via Python on the Makeability Lab website for scaling and this lets you choose lots of approaches.
