### ISSUE TITLE
Double Tapping Issue in Touchscreen Devices

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#347]
Double clicking (tapping) works in touchscreen devices, but the problem is that it also zooms in and out which is annoying.

One quick fix would be disabling double-tapping zoom on the entire page.

**Comment by jonfroehlich** [comment]
So, two quick thoughts:

1. First, I agree that touchscreen should have special handling for double tapping. I think we should disable this interaction, except if it's over the GSV window
2. If over the GSV window, then perhaps the double tap triggers the Zoom In function (analogous to clicking the Zoom In button). Of course, then the user may be confused about how to Zoom Out since there is no clear opposite gesture for zooming out (two finger pinch and zoom would work, but this is more complicated).

**Comment by Soben713** [comment]
I don't exactly understand your second point. But I don't think double tapping should trigger the Zoom In function even over the GSV window, because currently we assume double clicking moves the user forward and it is actually necessary in some locations where the arrows are not shown correctly.

**Comment by jonfroehlich** [comment]
Oh right, good point! So just disable double tap outside GSV window then?

**Comment by Soben713** [comment]
The correct way to fix this is to prevent browsers from zooming when double-tapped on the GSV window. There won't be any problem if zooming is not disabled in the rest of the screen.

**Comment by misaugstad** [comment]
This conversation is covered more thoroughly in issue #282 so I'm closing this issue.
