### ISSUE TITLE
Streets on the Boundary of the Neighborhoods

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#355]
This neighborhood (Hill East) is marked as complete in my local server, but note that a street segment on its boundary is not audited yet:

![image](https://cloud.githubusercontent.com/assets/1576529/19425125/fa5b68b4-93fc-11e6-9622-81341dd6907d.png)

We thought maybe the streets on the boundary are randomly assigned to one of the neighborhoods containing them. But this is probably not true because the other two audited streets that are on the lower boundary of this neighborhood belong to both neighborhoods containing them.

![image](https://cloud.githubusercontent.com/assets/1576529/19425051/6f641b34-93fc-11e6-93ff-22035f3eaa3e.png)

This should be investigated. What exactly is happening? How are boundary streets handled?

**Comment by jonfroehlich** [comment]
Do you know if you actually walked/audited that street?

**Comment by Soben713** [comment]
@jonfroehlich Not really.

**Comment by jonfroehlich** [comment]
Here's another interesting/weird example. It looks like I started at the circled intersection and then was routed East, which is, ostensibly, outside the North Cleveland Park boundary--when I finished that street segment, I was, rightfully transported back to a different part of the neighborhood.

![image](https://cloud.githubusercontent.com/assets/1621749/19623483/fff8387e-9898-11e6-8a8e-a708e06c5fb4.png)

Note: I took this screenshot while testing anonymous auditing. I added a Feedback for tracking (and there mentioned that it was me auditing under anonymous).

**Comment by misaugstad** [comment]
Streets that go through multiple neighborhoods will have an entry in the `street_edge_region` table for each neighborhood it intersects. If you start auditing a street, you get to audit the entire street, even if it leads you into another neighborhood. However, once you reach the end of that street, you are transported back to another street in the neighborhood.

And streets that run along the boundary of two regions may be marked as in one of the two regions, or both of them. And in any neighborhood that is associated with that street, you will be able to audit that street.

I think all the confusion here comes from not realizing that we consider streets indivisible, while streets can intersect multiple neighborhoods.

So this isn't a bug! However, I still want to answer the question that @Soben713 asked in the initial comment, namely
>How are boundary streets handled?

When we move to new cities, I need to know how all the street and region data were generated so that I can generate it again!

**Comment by jonfroehlich** [comment]
> When we move to new cities, I need to know how all the street and region data were generated so that I can generate it again!

@kotarohara should be able to help with this. He could likely writeup a github wiki post or a README.md that describes the process.

**Comment by misaugstad** [comment]
I sort of made changes to how these are generated anyway... And now streets only belong to one neighborhood! And (for the most part) they don't cross neighborhood boundaries. The code is still flexible enough to deal with this, but we should hardly ever see those oddities that were shown above.
