### ISSUE TITLE
Value of minimap in validation UI

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3593]
We have long discussed adding a minimap to the validation UI, which @misaugstad then recently added (thanks @misaugstad); however, now that it's there, I question the value of the information it provides. How does it help with the validation task? Currently, it seems minimally helpful and not worth the tradeoff in pixels (it takes up screen real estate and can cause occlusion problems with seeing a user's label https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3582).

I think, in my mind, I was envisioning that the user could see street names and more context about the area they were validating—so perhaps if we zoom out on the minimap a bit it could help.

But as now, it seems minimally useful.... and this is just my first impression/reaction to finally having the minimap available in validation (and I'm surprised by my reaction).

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/1bd343bc-8dd7-4ead-84bd-dbf901dff502)

**Comment by misaugstad** [comment]
I did play around with the zoom level and road labels a bit, and was struggling to find a way to get more info onto the minimap without it getting too crowded or hard to read, or by making the minimap bigger. And the minimap I added is actually significantly bigger than the one in our mocks. But I was pressed for time, so I could play around with it a bit more. There may have been an issue with not having control over the text size for the road labels?

We could also use Mapbox instead of Google Maps here, as I expect that we would have more control over it. But it would mostly mean starting over on the minimap, so we should carefully consider if it's worth it.

**Comment by misaugstad** [comment]
We talked about this during our 1:1 and decided that the minimap doesn't provide nearly enough value given the space it takes up on the screen. We've both struggled to find situations where the additional context is helpful. So the plan is to remove the minimap.
