### ISSUE TITLE
Very strange behavior in the gallery, creating multiple validations per label

### ISSUE THREAD

**Issue by jsomeara** [ProjectSidewalk/SidewalkWebpage#3629]
##### Brief description of problem/feature
In the gallery, when you switch between agree and disagree or any two validation options, it can create multiple validations. Weirdly, only one of these validations has the tags. The gallery system cannot properly handle these multiple validations when moving left/right (but that's not what this issue about - this issue is about the fact you can create multiple validations per label).
##### System info (OS, browser, city, and local/prod/test)
Windows 11, Chrome, Seattle, Local, No account signed in/anonymous user 
##### Video of current behavior
https://github.com/user-attachments/assets/5d45a7fb-9b6a-4795-8d23-bb5da86be115
##### Steps to reproduce
1. Go to the gallery
2. Pick a label
3. Switch between agree and disagree a lot
4. Refresh the page
5. See that multiple validations are created per label

**Comment by misaugstad** [comment]
Thank you for catching this and making a ticket for it! It's _definitely_ not supposed to be working like that! And it was probably something that we haven't caught before because it can be hard to notice unless you're looking at the same labels over and over in Gallery, which is uncommon unless you're testing some of the issues you've been working on!
