### ISSUE TITLE
Project Sidewalk Website is Down

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#368]
We need to fix this ASAP. I also want to ensure this doesn't happen again or, if it does, that we are aware if it in a short time frame. Perhaps we need a watchdog service or something to email or text us if the website goes down.

-----

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.2.15 (Red Hat) Server at sidewalk.umiacs.umd.edu Port 80

-----

![image](https://cloud.githubusercontent.com/assets/1621749/19598973/d533a05c-976b-11e6-879e-20a31a242860.png)

**Comment by jonfroehlich** [comment]
IT staff said this:

> UMIACS had it's monthly maintenance window last night.  While the sidewalk server is up and running, it appears that the application is not.  Let us know once you've started the web app, and we can talk about what options are available to have it automatically start on reboot.

**Comment by Soben713** [comment]
After the UMIACS' monthly maintenance window, the geotools' package`gt-espg-hsql` which uses HSQL does not work anymore. I am not sure about the reason. But using its alternative plugin `gt-espg-wkt` fixes the problem for now.

While this solves the problem, it is a workaround and not a real fix to the actual problem. We need to understand why that plugin does not work and prevent this problem to occur again for other packages that we use.

This is resolved in PR #373

**Comment by Soben713** [comment]
This should not be closed yet.

**Comment by Soben713** [comment]
Testing this on the 9005 port, the new plugin is slower than the previous one. It takes 2-3 seconds for the mission to load when the audit page is loaded. This is probably because `gt-espg-wkt` (the new plugin) uses a text file to load the data but `gt-espg-hsql` (the previous plugin) uses HSQL database. Therefore this is not really a long-term solution.

**Comment by Soben713** [comment]
The original plugin was not working properly because of some ownership issues that are now fixed. This issue could be closed.

### Detailed Explanation
All the data that the `gt-espg-hsql` plugin uses are stored in `/tmp/Geotools/Databases/HSQL/v8.6.0.0`. The shared user we use to deploy the code did not have writing access to these database files because they weren't part of the `sidewalkproj` ownership group. We are still not sure what changed after the reboot and why it was working fine before that; however changing the ownership fixed the problem.

**Comment by jonfroehlich** [comment]
So, to be clear, we have moved back to `gt-espg-hsql` again?

**Comment by Soben713** [comment]
@jonfroehlich Correct.

**Comment by jonfroehlich** [comment]
Nice, thank you very much @Soben713. Can you also update the staff@umiacs email thread with what we found out and our solution.

**Comment by Soben713** [comment]
Done.

**Comment by jonfroehlich** [comment]
What's the plan to try and get the hsql version to work?

**Comment by Soben713** [comment]
You mean for future problems? Because currently the hsql version is deployed and correctly works.

**Comment by jonfroehlich** [comment]
Weird. I sent that a long time ago. We can close this comment thread.

**Comment by jonfroehlich** [comment]
What's the plan to try and get hsql
