### ISSUE TITLE
Track Participate button clicks using Google Analytics for the landing page

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#440]
Add the google analytics tracking code to 'Participate' button/'Start auditing' link on the top menu bar on the landing page. Also, track visits to the audit page. Currently, we can't determine these stats using Google Analytics Dashboard.

**Comment by jonfroehlich** [comment]
This should be a very easy fix and, honestly, I'd like this to get done for v2 if possible. We should be using Google Analytics on every page on our website.

**Comment by kotarohara** [comment]
Actually I don't understand what the issue is. Isn't the application already tracking the web page visit using Google Analytics? I can see page visit on: `Behavior > Site Content > All Pages` ([ref](http://stackoverflow.com/questions/19502359/number-of-visitors-on-a-specific-page)). Also, isn't the `webpage_activity` tracking page visit to the `/audit` page? Are we talking about tracking more granular interactions (_i.e.,_ clicking the Start Auditing button on the navigation bar vs clicking the Participate button)?

**Comment by jonfroehlich** [comment]
I asked @manaswis to check whether the audit page was being tracked and I thought she said 'no.' So, I figured that the Analytics code was not being dropped into all pages (e.g., was not like in a base template). I did not investigate this myself.

I'm not sure we really care how many users click Participate vs. Start Auditing. We care about how many users come to landing page and then go to the /audit page, which it sounds like we can do. @manaswis, please investigate and respond when you get a chance.

**Comment by kotarohara** [comment]
I see. @manaswis , please check if necessary information is there so you can decide if you need to work on this. If not, one less issue to work on for you :)

**Comment by manaswis** [comment]
Thanks @kotarohara. I am looking into it now.

**Comment by manaswis** [comment]
I looked into this and the behavior flow chart from Google Analytics dashboard shows how many users come to landing page and then go to the /audit page. So we don't need to implement this.

Closing this issue.
