### ISSUE TITLE
activator/sbt download errors on first run when setting up development environment

### ISSUE THREAD

**Issue by tongning** [ProjectSidewalk/SidewalkWebpage#483]
During initial setup of the development environment, does anyone recall seeing download errors like this one when performing `activator run` for the first time?

```
[error] (*:update) sbt.ResolveException: download failed: org.apache.commons#commons-compress;1.7!commons-compress.jar
[error] download failed: org.tukaani#xz;1.4!xz.jar
```

What is strange about this error is that simply exiting and retrying the command (possibly two or three times) fixes it. After that, future launches of `activator run` do not result in any errors. There is a [question](http://stackoverflow.com/questions/36627511/play-framework-inconsistent-build) on StackExchange that describes this exact issue, but unfortunately doesn't have any answers.

Ultimately it's not a big issue, but I am trying to automate setup of the development environment in Docker and it would be preferable to not require this workaround in the setup scripts :)

**Comment by manaswis** [comment]
Yes, I also got this error. And like you mentioned, it works after 2 or 3 tries. At the time, I thought it might have to do with network connectivity. Maybe, its a problem at their (activator/sbt) server end.

**Comment by tongning** [comment]
Thanks, good to know it's not just me! It's strangely consistent for what seems like a download error. I'll see if I can find any solutions, but if not I'll just make a note of it in the setup instructions.

**Comment by manaswis** [comment]
That will be great, Anthony! Thanks!

**Comment by jonfroehlich** [comment]
@tongning, since you are investigating this again, it appears that the [StackExchange ](http://stackoverflow.com/questions/36627511/play-framework-inconsistent-build)post now has responses--though they don't seem too useful.

Also, perhaps you could add to the post and say you are having the same problem and provide your own details. Lots of folks seem to think it's user error (e.g., did you check your internet connection), etc., so having additional people point out the problem and their troubleshooting steps seems helpful to the community.

**Comment by misaugstad** [comment]
With our new Docker dev environment in PR #1364 this is solved. The repos we use to get these libraries has been changed so the downloads are no longer an issue :+1:
