### ISSUE TITLE
Label count in the current mission counter in the sidebar is not accurate

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#497]
When the user leaves an ongoing mission, and comes back to it later, the current mission label counter is filled with the label count of that mission. However, it isn't accurate. This issue is explained in great detail in the PR https://github.com/ProjectSidewalk/SidewalkWebpage/pull/445#issuecomment-267469882.

There is another issue in the current implementation of tracking the counts for the ongoing mission, see in the screenshot below:

![after_reloading_page_current_mission_counter_loads_everything](https://cloud.githubusercontent.com/assets/2873216/21444084/0418e0f2-c878-11e6-8770-14325b27b49d.png)

It appears all the labels of the neighborhood are accounted for in the current mission counter. However, the neighborhood Mayfair was an old neighborhood that was completed by Jon. Not sure, if it has to do with anything. This isn't seen in other neighborhoods. Another ramification of the same issue is that the labels shown in the current mission counter is more than the total labels count of the neighborhood. So further investigation is needed to debug it.

**Comment by sarahsmo** [comment]
I assigned myself this issue, because I need it resolved in order to complete issue #1079 

I figured out the discrepancy in label counts. In the screenshot above, the total labels placed adds up to 334, but yet it is displaying 336. This is because the removing of labels doesn't update label counts properly. So in the screenshot above, Jon must have removed 2 labels. 

I will be following up with another comment with the test results that have brought me to this conclusion.

**Comment by sarahsmo** [comment]
So I enter this neighborhood, and this is my current status.
![image](https://user-images.githubusercontent.com/31173144/32676462-b98632c4-c628-11e7-96f7-12ee59bcffdf.png)

I place 2 curb ramps
![image](https://user-images.githubusercontent.com/31173144/32676491-d0b17882-c628-11e7-8b9d-5b879b9f8d15.png)

I then "accidentally" place an missing curb ramp
![image](https://user-images.githubusercontent.com/31173144/32676505-e42366aa-c628-11e7-8b37-40c7a4654b1b.png)

I delete the curb ramp I "accidentally" placed
![image](https://user-images.githubusercontent.com/31173144/32676525-f4c5f806-c628-11e7-9fb2-0040f9c60b92.png)

Label counts are correct so far. 

Now I just finish up my mission, without adding or removing anything else. I placed 3, but deleted 1. Therefore I should finish the mission with 8 labels. Instead I finish with 9 because deleted labels are not being accounted for. 
![image](https://user-images.githubusercontent.com/31173144/32676592-3515d458-c629-11e7-98f8-6d04a97968ef.png)

I will proceed to figure out why this is happening and attempt to resolve it.

**Comment by manaswis** [comment]
#445 (comment) still needs more investigation I believe. The comment doesn't talk about deletion of labels. Keeping this issue open till that it is solved.
