### ISSUE TITLE
Reset current mission counter after onboarding

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#498]
The labels added during the onboarding are visible in the current mission counter of the first mission after the onboarding. They need to be zero to be accurate.

**Comment by jonfroehlich** [comment]
OK, so, if I recall correctly, we did not reset the mission counter stats after the tutorial because we were trying to give the user a sense of achievement and help build their sense of investment in the tool (i.e., harness the endowment effect; see: http://ui-patterns.com/blog/beyond-usability-designing-with-persuasive-patterns). However, perhaps this is/was confusing and rightly needs to be fixed.

I think it's a low priority issue either way but I just wanted to provide a back story on our design rationale. There is a specific example from the book Nudge, I believe, about starting off potential clients/users with a non-zero credit because it helps build a commitment to a product. You've probably seen this done in other services (e.g., airline mile signup bonuses, etc.). We were trying to tap into similar psychological principles but like many of the persuasive (and gamification) elements of the website, it's probably not implemented particularly well.

**Comment by manaswis** [comment]
Closed via #651
