### ISSUE TITLE
Confusion between driveways and curb ramps

### ISSUE THREAD

**Issue by manaswisaha** [ProjectSidewalk/SidewalkWebpage#503]
Add this to the FAQ.

**Comment by manaswis** [comment]
In the recent pilots, our collaborator pointed out that driveways are important for them to know where they are, because they serve the same purpose as curb ramps - essentially they are a different type of ramp.

While labeling, he contemplated on this a bit - as to how should he label this - he went with curb ramp since that's the closest to it. In other usability tests, users have mentioned that the keyword while labeling a feature as curb ramp is "ramp".

So even though, it might mess up ML algorithms, however, this shows the need for users to label them as well.

**Comment by manaswis** [comment]
Especially important for navigation applications when this data would be used.

**Comment by jonfroehlich** [comment]
I'd like to suggest *not* adding this to the FAQ right now and instead waiting until we: (1) have conducted all of our interviews to see if this is a common shared view; (2) had external validation of our current codebook from people with impairments; (3) are passed the CHI deadline; (4) discuss it as a team and decide what UI changes are necessary. 

In my understanding of the situation, while driveways can indeed allow someone in a wheelchair to go down to street, it's less than ideal and puts them in a situation where they must navigate on the street, which is dangerous.

**Comment by manaswis** [comment]
This issue is old from Dec 2016, and its about adding clarification information to FAQ - to let users know that driveways aren't supposed to be marked as curb ramps.

I wasn't suggesting adding curb ramp labels for driveways. However, I wanted to make a note of the point the participant made. Since I had seen repeated occurrences of people marking driveways as ramps, and their reasoning behind it, I thought we should log it. Would be helpful in the future when we do deal with this issue.

**Comment by jonfroehlich** [comment]
Definitely. And this is addressed in Mikey's codebook. 

We are in agreement. Thanks for clarifying.

**Comment by jonfroehlich** [comment]
We now know from @aileenzeng's analyais that 22.2% of false positive curb ramp labels were applied to driveways (and 44.4% were for sidewalks that transition to driveways but don't actually have or require a curb ramp):

![image](https://user-images.githubusercontent.com/1621749/49302733-c1d6c500-f47c-11e8-846c-c8be1d6b348d.png)
 
Two potential follow-ups to this:

1. Do we want to consider adding in a driveway label? We know that--in the worst case--driveways can substitute for curb ramps (when no other strategy is available). We also know that some users confuse driveways with curb ramps. Would adding a driveway label help resolve this? (Note: I'm not entirely enthusiastic about this option tbh... and would want to weigh adding this label in the context of all other potential label types, if we consider it at all).

2. If we don't add a specific label type for driveways, I wonder if we could, at the very least, try to infer when a curb ramp label is inappropriately being used for a driveway--even if just by heuristics based on where the user is on the street (and then use a pop-up label to ask "are you sure?" or something similar.

**Comment by misaugstad** [comment]
>I wonder if we could, at the very least, try to infer when a curb ramp label is inappropriately being used for a driveway--even if just by heuristics based on where the user is on the street (and then use a pop-up label to ask "are you sure?" or something similar.

This is what I have been thinking of as our best solution (it has its own issue #1253). It shouldn't be terribly difficult to determine if a user is far from an intersection.

>Do we want to consider adding in a driveway label?

I think that the way a driveway label would resolve the incorrect labeling is by forcing us to add training for it, and thus explaining the difference between driveways and curb ramps. If we are going to go that far, we may as well just add training on the difference between the two and not ask them to label driveways.

**Comment by jonfroehlich** [comment]
> This is what I have been thinking of as our best solution (it has its own issue #1253). It shouldn't be terribly difficult to determine if a user is far from an intersection.

Great... but yes, may take some time to do well.

> I think that the way a driveway label would resolve the incorrect labeling is by forcing us to add training for it, and thus explaining the difference between driveways and curb ramps. If we are going to go that far, we may as well just add training on the difference between the two and not ask them to label driveways.

Except that labeling driveways may actually have value (e.g., for future routing algorithms, etc.)

**Comment by manaswis** [comment]
> Except that labeling driveways may actually have value (e.g., for future routing algorithms, etc.)

This in fact was mentioned by interview participants last summer--the primary reason of labeling them is that they would like to know if there is a ramp-like structure on the sidewalk that they could use. So there is value in knowing of their existence.

My concern is creating too many label types. One thing participants mentioned was the set of label types were concise enough to cover most things they see in their day-to-day commute. So maybe instead of creating a new label type have a way of sub-categorization within curb ramp (e.g. description tags that were recently added) OR use of the "Other" label type with the tag? I agree having a clear distinction between curb ramps at intersections are important. So it might be worthwhile to think about doing sub-categorization well since its useful in other label types as well (e.g. obstacles).

**Comment by jonfroehlich** [comment]
Right, so, to be clear, I am not advocating for adding this label--and certainly if we do begin to consider it, we need to weigh this choice in concert with other potential label types that we could add. We would also have to brainstorm how to best support new label types (I like potentially expanding the other label with a tag but this wouldn't be used consistently enough for driveways to be useful I would expect). I agree that there is tremendous value in keeping the list of labels super tight.

**Comment by jonfroehlich** [comment]
Labeling driveways as curb ramps continues to be one of our most common labeling mistakes. I would offer two suggestions:
1. We improve this with better user education and training (in the tutorial, in the FAQ, in the mission screens that Katrina/Daniel were working on)
2. We auto-detect these errors by noticing frequent use of curb ramp labels within the midpoints of street segments (we could probably identify this _in situ_ while the user is making the mistake and alert them in addition to identifying it via posthoc analysis and filtering it from our dataset).

**Comment by misaugstad** [comment]
I think that we can close this ticket at this point. We've added a lot of dedicated training for this over time. There's always more that we can do to surface mistakes that users make so that they don't continue to make them, but I'm not sure that we need a dedicated ticket for this specific mistake anymore. Feel free to reopen if you disagree @jonfroehlich!
