### ISSUE TITLE
Tutorial Issues

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#531]
@manaswis, my apologies for duplicating pre-existing tutorial related issues. I wanted to dump everything here as a user log when taking the tutorial this morning on the dev server.

1. The tutorial should recognize when the user has done the wrong thing and offer corrective advice. In the following case, for example, the user selected the wrong label type and placed it in the wrong area. (Rather than or in addition to corrective guidance, we could restrict the tutorial interface a bit to only allow users to click on the labels that we want them to--i.e., the flashing things in the interface)
![image](https://cloud.githubusercontent.com/assets/1621749/23999563/2fefc4cc-0a2f-11e7-9a6d-1da9b4667215.png)

2. To be consistent with our use of flashing animation to call user attention to something, we should flash this arrow (simple change arrow to a gif that switches between yellow and white fills):
![image](https://cloud.githubusercontent.com/assets/1621749/23999661/6cbedbc2-0a2f-11e7-9501-7446f58b8def.png)

3. In our user testing, I observed a very common problem: users would misperceive the panning hand animation to mean that they should pan to the right ---> rather than the appropriate pan to the left <---. We need to do two things: (i) add an additional arrow that tells the user where to pan (not sure on language here)--see drafty mockup below; (ii) if they start panning the wrong way, pop up a more salient and helpful message that helps them correct this action; (iii) if they continue panning the wrong way, auto-pan the right way all the way to appropriate spot. We could also consider a different animation than the hand thing since that seems confusing.

![image](https://cloud.githubusercontent.com/assets/1621749/24000001/64ee0aa2-0a30-11e7-9f11-461b387b4271.png)

![image](https://cloud.githubusercontent.com/assets/1621749/24000061/8cdf9788-0a30-11e7-95db-a56b36dc7474.png)

4. With the new GSV placement location in the tutorial, it's very hard to actually see this corner & the fact that there is no curb ramp. Perhaps we could have user zoom here (& train them in on zooming). 

![image](https://cloud.githubusercontent.com/assets/1621749/24000125/c9012d76-0a30-11e7-925b-10f669c28182.png)

5. I have observed users getting confused here too. They now see two curb ramps to label but the tutorial interface is telling them to continue panning. I think the UI needs to acknowledge this someway and say something like 'keep panning to the right' or something. Otherwise, I've seen users stop here and try to label the curb ramps (before they get to the correct pan position for the tutorial to continue).

![image](https://cloud.githubusercontent.com/assets/1621749/24000311/41ede5ee-0a31-11e7-9ddc-d2bbce7565f4.png)

6. This has been commonly said among the team but we should probably keep both of these arrows up and let the user label the curb ramps in the order they want rather than enforcing this weird right-to-left order that we do now (which confuses users). 
![image](https://cloud.githubusercontent.com/assets/1621749/24000324/4aa1c48a-0a31-11e7-9cb8-028495e2e841.png)

See, I've already labeled the curb ramp but now the tutorial interface is telling me to label it again. This should not happen. It's confusing!
![image](https://cloud.githubusercontent.com/assets/1621749/24000340/58bf2bca-0a31-11e7-8a2e-0e62e13b90c9.png)

7. This arrow should be in a slightly different position imo (moved slightly upwards on dirt path):

![image](https://cloud.githubusercontent.com/assets/1621749/24000369/73d1a8c0-0a31-11e7-89ae-1c9a10ec175b.png)

8. @manaswis, we've discussed this one but this part of the tutorial now completely does *not* make sense since the GSV imagery is new and the blurriness/washed out does not actually exist. So, we need to come up with a better solution to onboard walking behavior.

![image](https://cloud.githubusercontent.com/assets/1621749/24000443/a155461c-0a31-11e7-9278-f200fdd55e34.png)

9. Finally, and we've discussed this as well, we need to better onboard the fact that labels disappear in the GSV interface after you take a step so that users should focus on top-down map for previously placed labels. Could also show user that the labels are still there if they step back in the labeling location. @manaswis, I want you to think about and propose a good way to handle this.

**Comment by manaswis** [comment]
I will create issues for the new suggestions you have added and update the existing issues.

Responses inline:

> 1. The tutorial should recognize when the user has done the wrong thing and offer corrective advice. In the following case, for example, the user selected the wrong label type and placed it in the wrong area. (Rather than or in addition to corrective guidance, we could restrict the tutorial interface a bit to only allow users to click on the labels that we want them to--i.e., the flashing things in the interface)
![image](https://cloud.githubusercontent.com/assets/1621749/23999563/2fefc4cc-0a2f-11e7-9a6d-1da9b4667215.png)

New issue. We could disable the rest of controls, while keeping the one in question active, then enable the appropriate one again for the next step.

> 2. To be consistent with our use of flashing animation to call user attention to something, we should flash this arrow (simple change arrow to a gif that switches between yellow and white fills):
![image](https://cloud.githubusercontent.com/assets/1621749/23999661/6cbedbc2-0a2f-11e7-9501-7446f58b8def.png)

This suggestion is included in an existing issue #499. I'll update the interface.

>3. In our user testing, I observed a very common problem: users would misperceive the panning hand animation to mean that they should pan to the right ---> rather than the appropriate pan to the left <---. We need to do two things: (i) add an additional arrow that tells the user where to pan (not sure on language here)--see drafty mockup below; (ii) if they start panning the wrong way, pop up a more salient and helpful message that helps them correct this action; (iii) if they continue panning the wrong way, auto-pan the right way all the way to appropriate spot. We could also consider a different animation than the hand thing since that seems confusing.
>![image](https://cloud.githubusercontent.com/assets/1621749/24000061/8cdf9788-0a30-11e7-95db-a56b36dc7474.png)

Existing issue #437. The problem with panning is the users have to pan the opposite direction to the way they want to go. E.g. to see the next intersection in the tutorial, they have to drag to the right to move left, which is why they get confused. So adding an arrow saying "Pan" might not help. We could add to the instruction text that "Drag to the right to move left" or something like that and show the arrow in the direction of the drag (and inside the arrow, add the appropriate text like you showed).

> 4. With the new GSV placement location in the tutorial, it's very hard to actually see this corner & the fact that there is no curb ramp. Perhaps we could have user zoom here (& train them in on zooming). 

Yes, we could do that. Will require adding new instructions to the onboarding script for zooming. I'll add this to a new issue.

> 5. I have observed users getting confused here too. They now see two curb ramps to label but the tutorial interface is telling them to continue panning. I think the UI needs to acknowledge this someway and say something like 'keep panning to the right' or something. Otherwise, I've seen users stop here and try to label the curb ramps (before they get to the correct pan position for the tutorial to continue).

I can update the text to say "continue till you see two curb ramps" and update the script to show the next instruction sooner.

>6. This has been commonly said among the team but we should probably keep both of these arrows up and let the user label the curb ramps in the order they want rather than enforcing this weird right-to-left order that we do now (which confuses users). 
![image](https://cloud.githubusercontent.com/assets/1621749/24000324/4aa1c48a-0a31-11e7-9cb8-028495e2e841.png)

This would need updating the script execution flow. The current execution is serial - one step after another. I'll add an issue.

>See, I've already labeled the curb ramp but now the tutorial interface is telling me to label it again. This should not happen. It's confusing!
>![image](https://cloud.githubusercontent.com/assets/1621749/24000340/58bf2bca-0a31-11e7-8a2e-0e62e13b90c9.png)

Yes, this would have happened if you labeled the left curb ramp first while the script wanted you to finish the right one first. Would have to update the script to work for either curb ramps.

> 7. This arrow should be in a slightly different position imo (moved slightly upwards on dirt path):
>![image](https://cloud.githubusercontent.com/assets/1621749/24000369/73d1a8c0-0a31-11e7-89ae-1c9a10ec175b.png)

Easy fix. Will update this.

8. @manaswis, we've discussed this one but this part of the tutorial now completely does *not* make sense since the GSV imagery is new and the blurriness/washed out does not actually exist. So, we need to come up with a better solution to onboard walking behavior.

![image](https://cloud.githubusercontent.com/assets/1621749/24000443/a155461c-0a31-11e7-9278-f200fdd55e34.png)

Yes, this needs to be updated. We need to brainstorm a better way to learn walking. (Existing issue #228)

9. Finally, and we've discussed this as well, we need to better onboard the fact that labels disappear in the GSV interface after you take a step so that users should focus on top-down map for previously placed labels. Could also show user that the labels are still there if they step back in the labeling location. @manaswis, I want you to think about and propose a good way to handle this.

Once again, brainstorming needed. I will work on this, and also create an issue.

**Comment by jonfroehlich** [comment]
Thanks. I read over your responses and I don't see any action items for me other than he brainstorming. I agree w your comments. 

Re: brainstorming. Best that you come up w a proposed fix and mockup (or two) and I provide feedback (Best approach I think until I'm done with paternity leave).

**Comment by manaswis** [comment]
As discussed, addressed the minor changes and modified the walking instructions for it to be good enough for release:

Resolved the arrow position for the "no sidewalk".
<img width="733" alt="screen shot 2017-03-18 at 10 31 16 am" src="https://cloud.githubusercontent.com/assets/2873216/24072985/3692b508-0bc6-11e7-998f-26f4c39f1df7.png">

>we've discussed this one but this part of the tutorial now completely does not make sense since the GSV imagery is new and the blurriness/washed out does not actually exist. So, we need to come up with a better solution to onboard walking behavior.

Updated the walking instructions to remove the "washed out" part of the message.
<img width="727" alt="screen shot 2017-03-18 at 10 31 31 am" src="https://cloud.githubusercontent.com/assets/2873216/24072986/369546b0-0bc6-11e7-86e3-8ab3a4d806e8.png">
<img width="742" alt="screen shot 2017-03-18 at 10 31 42 am" src="https://cloud.githubusercontent.com/assets/2873216/24072987/36954fde-0bc6-11e7-8e8b-564804b8588d.png">

**Comment by jonfroehlich** [comment]
Thanks for this. The walking part still seems weird to me even as a temporary fix. I would take away the arrow on the curb ramp for the walking part. It's confusing. Just focus user on walking. Then after they take the step, have them label. 

Also, if they double click that circle, are they guaranteed to take a step

**Comment by manaswis** [comment]
Yes, I also considered this. I will do that. I am traveling a bit today. So I will update it when I reach my destination.

Yes, they are guaranteed to take a step.

**Comment by manaswis** [comment]
Updated the [existing comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/531#issuecomment-287193451) with the newly created/old issue numbers. Each of the issues can now be tracked in their respective issue threads.
