### ISSUE TITLE
Cursor Stuck As Crosshair Rather Than Hand

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#549]
For some weird reason, my cursor got stuck as a crosshair rather than hand:
![image](https://cloud.githubusercontent.com/assets/1621749/24248811/49a6b466-0fa7-11e7-9edd-c5104f6ee18d.png)

It still appears to correctly change when I mouseover things, however:
![image](https://cloud.githubusercontent.com/assets/1621749/24248827/5fb248ce-0fa7-11e7-988f-b4653864fdd7.png)

![image](https://cloud.githubusercontent.com/assets/1621749/24248833/656ca552-0fa7-11e7-8000-a040bd8f2ddb.png)

**Comment by jonfroehlich** [comment]
I am encountering this problem on my Mac as well.

**Comment by manaswis** [comment]
I have encountered this when issue #550 happens. @jetrax12 has submitted a PR on #550. Hopefully this will be resolved.

**Comment by sagec108** [comment]
I found an instance of a crosshair instead of a cursor. I noted that while there were no console errors, the css cursor for the view layer was:

![image](https://user-images.githubusercontent.com/20068009/27559824-f5a9bb7c-5a8f-11e7-8705-b629f11c4818.png)

I'll see if I can change this sometime after relaunch.

**Comment by manaswis** [comment]
Closed via PR #793
