### ISSUE TITLE
Feature Request: Map Keyboard to More Label Types

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#59]
Can we map keyboard keys for "Can't See Sidewalk" and "No Sidewalk" like we do for "Curb Ramp" and other labels types.

Relatedly, it looks like we are not using 'right-click' for anything. Maybe right-click could drop the last used label type at the mouse cursor?

**Comment by nguyenist** [comment]
Right clicks are tricky because they're hidden-- this would have to be taught in the walkthrough or emphasized / reminded throughout. I am just one data point, but based on my experience labeling, perhaps a simpler user experience might be if you didn't have to click `curb ramp` every time you want to label `curb ramp` in google street view. For example, they should be able to label, move forward, label, move forward *without* having to also click a button each time in between. If they want to change labels, they can just switch it at the top.

**Comment by jonfroehlich** [comment]
Yah, I usually do label switching via the keyboard--which I agree is an expert user feature but still something I think we should onboard because it really increases user efficiency.

**Comment by kotarohara** [comment]
I'll finish it. I've already mapped No Sidewalk to "N". I'lll think about "Can't see sidewalk" (currently "C" is taken for "Curb Ramp").

**Comment by kotarohara** [comment]
Mapped "Can't see the sidewalk" to "b" for "blocked view".
