### ISSUE TITLE
Little person on mini map disappears 

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#612]
Seen below. I was just going about my auditing business, and at some point the little person on the mini map disappeared. Nothing out of the ordinary seemed to happen and I haven't been able to reproduce it. But I am just noting that it has happened. Has anyone else seen this happening?

![no_little_person](https://cloud.githubusercontent.com/assets/6518824/26508536/1bf81308-4223-11e7-935e-24df0d340822.png)

**Comment by misaugstad** [comment]
being addressed in #335

**Comment by jonfroehlich** [comment]
Indeed. This is the most common problem reported in Sidewalk (besides, perhaps, labels disappearing in the GSV view after taking a step--which is by design since we can't accurately place labels in 3D from different viewpoints).

However, I do appreciate you auditing and using the system. The entire Sidewalk team needs to consistently use the system to ensure that things don't break (paging @manaswis @maddalihanumateja @sagec108).
