### ISSUE TITLE
Shift-Z zooms-in when label menu open

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#623]
When the label/context menu is open (as in picture below), Shift-Z zooms *in* instead of out. When the menu is not open, it works as expected.

Was able to reproduce this on both Firefox and Chrome.

![sidewalk-label_menu](https://cloud.githubusercontent.com/assets/6518824/26609880/fe9fc204-4571-11e7-842e-277b2cadae0b.png)

**Comment by jonfroehlich** [comment]
Assigning this to @sagec108 since he is on a roll in fixing small IxD issues.

**Comment by sagec108** [comment]
To add to this, I noted in #614 that Edge has similar zoom out issues (zooming in when button says to zoom out, etc).

**Comment by sagec108** [comment]
I'm changing it so that if the user uses shortcut keys to zoom while the context menu is displayed, the context menu will be hidden first before zooming. The existing code did not intend for the user to zoom while the context menu is open, as manually clicking on the zoom buttons will close the context menu anyways. This caused the bug that @misaugstad found.
