### ISSUE TITLE
Disable zooming using keyboard shortcuts + and - : Breaks the tool

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#678]
Google Maps default for zooming, keys **+** (plus signs) and **-** (dash or minus signs) is still activated. If using that, then multiple things happen:

1. Zooming looks broken
![image](https://user-images.githubusercontent.com/2873216/27163254-33e80b72-5154-11e7-8bec-218c72ec612b.png)

After zooming when the context menu is open:
![image](https://user-images.githubusercontent.com/2873216/27163261-3c5aaf8a-5154-11e7-930b-d3e26a1306d9.png)

Although, its true for normal zooming as well. Fix: Auto close context menu before zooming.

2. Panning breaks after using +/- for zooming
![image](https://user-images.githubusercontent.com/2873216/27163153-7d66d716-5153-11e7-8b14-d1997c25b462.png)

**Comment by jonfroehlich** [comment]
> 1. Zooming looks broken

It's not clear to me how zooming is broken in the screenshot that you supplied.

**Comment by manaswis** [comment]
The context menu is detached from the label when zoomed in.

**Comment by jonfroehlich** [comment]
Ah, I thought that was the second part of your comment. I see now that it follows under the 1 block.

**Comment by misaugstad** [comment]
Upon further testing, I am finding that the issue is that by pressing "-", you can zoom our further than you are allowed to by hitting shift-z. So to reproduce...

Place a label (at any zoom level)
![sidewalk-pm2](https://user-images.githubusercontent.com/6518824/28094364-24322732-666a-11e7-9a91-43e99c8bce98.png)

Hold "-" to zoom out as far as it will let you
![sidewalk-pm3](https://user-images.githubusercontent.com/6518824/28094367-2657f8f2-666a-11e7-91fc-694fd2b1a237.png)

Try to pan
![sidewalk-pm4](https://user-images.githubusercontent.com/6518824/28094371-2a011362-666a-11e7-9beb-6b26bec86c6c.png)

And as I mentioned in #864, the keys also start zooming when the user is typing in the context menu for a label (adding a comment to it).

**Comment by jonfroehlich** [comment]
Yikes, this just happened to me on Turk.

![image](https://user-images.githubusercontent.com/1621749/30038181-ccbbc2dc-9176-11e7-8fac-5f96c3845bd8.png)

**Comment by jonfroehlich** [comment]
@johannkm or @sarahsmo, can you look into this? The bug should be very easy to replicate (and thus test a fix) and the bug has major consequences: it completely breaks using the tool.

**Comment by johannkm** [comment]
The root of the problem is the +/- zooming because:
- It duplicates the main zoom tool, but behaves slightly differently
- #999 It zooms even while the user is typing something in a dialogue box
- #678 It zooms out too far, breaking the tool (this issue)

However, @sbower213 investigated this and [didn't find a solution](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/999#issuecomment-323155880). Assuming that we can't remove the +/- zooming, we need to eliminate its effects. I'll look into the API for a way to cap how far GSV can zoom out.

**Comment by jonfroehlich** [comment]
Thanks @johannkm. There has to be a solution! 

There may also be a related problem with hitting the 'z' key to zoom-in, which used to *always* work but now intermittently stops working (so some change this summer broke it). I suspect it stops working because the tool thinks that we are already all the way zoomed in because (which we're not). I can get it to work by clicking on the zoom-out button (even though I'm all the way zoomed out). See: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/922

**Comment by johannkm** [comment]
The JavaScript API doesn't have the options we need.

`google.maps.MapOptions` lets you disable `keyboardShortcuts` and set `minZoom` so that the map doesn't go out too far, but these only impact the overhead map and not the GSV. These options aren't present in `google.maps.StreetViewPanoramaOptions`.

With some reverse engineering, we may be able to remove the event handler from the key event. Before that, lets see if we get an answer from [Stack Overflow](https://stackoverflow.com/questions/46161185/google-street-view-javascript-api-disable-keyboard-zooming).

**Comment by jonfroehlich** [comment]
Awesome that you posted to Stack Overflow--I really like to see this proactiveness from my students.

Could you also post to the Google Maps dev forums? And link to that post here as well too.

**Comment by aileenzeng** [comment]
This is an issue that I ran into while working on the validation interface. The API actually has a `StreetViewPanoramaOption` that disables +/- zooming!

Adding this line to our panorama should fix the issue: `svl.panorama.set('scrollwheel', false);`

I'll test it out and send a PR if it works!

**Comment by misaugstad** [comment]
closing via #1388
