### ISSUE TITLE
Redesign Project Sidewalk Down Page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#682]
Should at least include our logo and not have such horrible text wrapping.

![image](https://user-images.githubusercontent.com/1621749/27193918-a30ecca0-51ce-11e7-84a0-1b7fae32a65e.png)

**Comment by misaugstad** [comment]
@itsyeonjoon could you design a simple webpage that still looks nice that we can use if we ever need to take the site down for maintenance again? The text should be pretty vague for now, just saying that we're down for maintenance. But the styling should be set up so that we can fill in the text in the future with a more specific reason without needing to fiddle with the CSS a bunch to get it to look okay. Also definitely include our logo :)
