### ISSUE TITLE
Should We Be Concerned About Running Up Against API Usage Limits?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#686]
We can get 25,000 map loads/24 hour period using the free API. Is there a realistic scenario where we could be pushing on that limit during relaunch? Has anyone done any back-of-the-envelope calculation on this (e.g., how many API calls per mission on average, how many users/day do we expect)?

https://developers.google.com/maps/documentation/streetview/usage-limits

**Comment by maddalihanumateja** [comment]
A pano request counts as a single map load. We seem to be requesting pano s for every 3ft. So 25000 requests amount to 75000ft which is roughly 14.2 miles. I don't know what distance the average user audits in a day. But assuming it is around a mile, it looks looks we will exceed the limit if more than 14 people use sidewalk in a day.

**Comment by jonfroehlich** [comment]
@misaugstad should be able to tell us what an average user does--but I'm guessing the 'average' user likely only finishes one or two missions and stops (so, completes between 1,000 ft and ~3500 ft of road)...

**Comment by manaswis** [comment]
### Map Loads
This is some information from their site on [map-loads](https://developers.google.com/maps/faq#usage_mapload):

![image](https://user-images.githubusercontent.com/2873216/27243750-5b44aa46-52b1-11e7-8ae4-702e6388b1fd.png)

Important point to note here is 
>A web page or application displays a Google Street View Image API panorama using the Google Maps JavaScript API. If a Street View panorama replaces a map in the same div element, the panorama is not charged.

Since we do load our panos in the same div, our map-load is 1/user i.e. each time the user loads our audit interface. So if we don't exceed 25000 users/day (assuming one load per person), we should be fine.

### Tracking Usage
The usage can be tracked using Google API Console Dashboard. I had created this API key (and replaced the other old one) beginning of Spring semester, so I could track the usage. Some stats for the past month:

![image](https://user-images.githubusercontent.com/2873216/27243844-e05936fc-52b1-11e7-8baf-3bc85c1b2ac9.png)

Last 30 days usage:
![image](https://user-images.githubusercontent.com/2873216/27243943-4c0e295c-52b2-11e7-89ec-bff31ddf5cca.png)

In both of these, high counts are for the days we were doing consistent development (like yesterday, I had to reload the page each time I was making any change for onboarding). So counts/map loads will also be high during such high intensity development weeks.

**Comment by jonfroehlich** [comment]
This is great @manaswis. Thanks for the analysis and more info on API usage. Closing this issue as I am now confident it will not be a problem.
