### ISSUE TITLE
Weird routes

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#718]
Logging some weird routes encountered. Not bugs.

Street Id: 25248

![image](https://user-images.githubusercontent.com/2873216/27349202-81103ffe-55c4-11e7-9401-70dc448bfabc.png)

![image](https://user-images.githubusercontent.com/2873216/27349229-8d74f744-55c4-11e7-83ff-e84136ace2e4.png)

After taking a step:
![image](https://user-images.githubusercontent.com/2873216/27349274-aaf1adc6-55c4-11e7-8bdd-05f6a4f95108.png)

**Comment by jonfroehlich** [comment]
I think I have a similar thread about this somewhere...

**Comment by manaswis** [comment]
Street id: 7461

![image](https://user-images.githubusercontent.com/2873216/27351452-6cd57bce-55cb-11e7-8465-49699a31930a.png)

![image](https://user-images.githubusercontent.com/2873216/27351439-60af725a-55cb-11e7-8d3d-65671e3c651f.png)

![image](https://user-images.githubusercontent.com/2873216/27351381-24460536-55cb-11e7-839e-7c6c94ad101d.png)

**Comment by manaswis** [comment]
@jonfroehlich Yes, I remember. You had the one with interesting panoramas.

**Comment by jonfroehlich** [comment]
And I also had an Issue for crazy routes that I could not follow.

**Comment by jonfroehlich** [comment]
Update. Our users are now complaining about this:

![image](https://user-images.githubusercontent.com/1621749/27511655-fc373774-58f7-11e7-8a27-d955af50ef30.png)

Can someone investigate this more closely and see, for example, what neighborhood and routes this anonymous user was auditing?

**Comment by maddalihanumateja** [comment]
I tried to use the admin playback tool for this task. 
My browser just keeps becoming unresponsive.
Maybe someone else should try looking at this.

**Comment by manaswis** [comment]
This is the street the user was auditing. Direct link where you can try it out - http://sidewalk-dev.umiacs.umd.edu/audit/street/26025

Here is the screenshot:

![image](https://user-images.githubusercontent.com/2873216/27513441-cf272bb8-5933-11e7-823c-2c5d330fb620.png)

If you double click on the screen anywhere, you enter the tunnels, which is why it got confusing to follow the routes. Plus the route is not on the street but over the tunnels.

**Comment by jonfroehlich** [comment]
Thanks Manaswi. This is the same problem I was having in downtown D.C. by the federal buildings. Maybe we should have an ugrad fully audit these neighborhoods and document problems.

**Comment by jonfroehlich** [comment]
Can @chishankar or @sbower213 take this on? Start screen recording your missions as you walk around the Waterfront DC neighborhood so that we have good evidence of what's happening.

Note: I also had this issue for Region 251 "Monumental Core, DC' where I would alternate between above ground and below ground (in a tunnel) as I was walking through the region.

**Comment by jonfroehlich** [comment]
How come no one has taken this on yet? Are there higher priorities? (There very well could be but this one seems big to me because I feel like at least two major neighborhoods are not currently usable in PS because of this weird routing problem).

**Comment by r-holland** [comment]
@misaugstad just assigned me to screen record some speed runs, so I'll start to take this on

**Comment by r-holland** [comment]
Here's the link for a 10-minute speed run around Waterfront neighborhood:
https://www.youtube.com/watch?v=ht7SRGUc7rI&feature=youtu.be

There were stretches where it was fine, and no problems occurred. Unfortunately, for the most part this neighborhood had some big problems. I suggest watching the video, or at least part of it, to get an idea of what I'm touching on, but I'll list some major ones below.

Frequent Issues:
1. I had to double click a ton. Many times the arrows did not point in the direction of the tutorial, and while I was easily able to navigate with double-click, this will likely be a problem for users who are not aware of and/or comfortable with the double-click functionality. Ex: 00:43, 4:06, 7:45
2. The red line took me on some weird routes. More than once the route crossed over itself, or led me in a circle around the same intersection, following very small connecting streets. Ex: 00:57-1:27, 5:45
3. Often, on the mini map in the bottom right, the red line was not even positioned on top of the street, but instead floated off to the side, making it unclear where I was supposed to go. Ex: 00:39, 5:45

Infrequent Issues:

1. Twice, I had to jump because I could not navigate the route. One of these instances, I was stuck in a tunnel and could move around, but not along the route. The other instance, I was stuck in some square with a fountain, and had no ability to move whatsoever. Jump worked both times, but this may be frustrating for users. Ex: 3:00-3:32, 4:15-4:44
2. The "You have reached the end of this route...click here to move to a new location" dialogue box sometimes appeared while there was still a bit of red line left that I hadn't covered. In these situations, should users keep stepping forward...or click to move location? Ex: 00:31

Very Infrequent Issues:

1. Once, my little yellow avatar walking around the bottom left mini-map just disappeared on me for a few seconds. This didn't affect any functionality, and I still could follow the route, but it was weird. Ex: 5:15-5:43
2. Once, the red line route wanted me to follow a side street, and I scanned around 360 degrees but didn't see it. Then, I realized when the photo was taken, the street was being blocked off for construction. I double clicked on the fence that was blocking the road and was able to get through. However, this probably would not be intuitive for many users. Ex: 8:48-8:58

Hopefully my speed run helps visualize some of these concerns. There are definitely more examples of these 7 issues than just the time stamps I labeled as examples.

First thing tomorrow morning, I'll conduct another speed run, this time of Monumental Core.

**Comment by r-holland** [comment]
Here's the link for an 8-minute speed run around Monumental Core neighborhood:
https://www.youtube.com/watch?v=iu0V5vjPPm8&feature=youtu.be

Unfortunately, this area too has a number of problems, mostly the same as in my previous report. Refer to the above comment if any of my issue descriptions here are unclear. Again, I suggest watching the video, it gives a very good visualization of these concerns. 

Frequent Issues:

1. There is still a ton of double clicking necessary to follow the route. Ex: 2:33, 3:03, 3:32, 6:23, 8:33
2. There are still some weird routes that take you in circles or backwards on the same street. Ex: 7:41, 8:00-8:16
3. There are still some times where the red line on the mini map is positioned to the side of the street rather than directly over top of the street. Ex: 0:54, 8:44
4. This time, the same issue of the little yellow avatar on the mini map disappearing happened again, but much more frequently. And this time, I had to make turns and it was very confusing without the guy showing me which direction I'm facing relative to the red line. Ex: 1:36-2:42, 3:26-6:01, 8:55-9:12

Infrequent Issues:

1. One time, the arrows/double-click wouldn't let me go in the direction of the line. I had to jump. Ex: 4:48-5:43
2. This may be "infrequent," but this last issue is very severe. At one point in the mission, it dropped me in a tunnel. I jumped and it dropped me in a garden. I jumped and it dropped me in front of a monument, off the street. I jumped and it dropped me inside some museum. Finally, on my fifth jump it put me on a street. Considering I was dropped in a location I couldn't move from **four straight times**, I feel this would probably anger a user a lot. Ex: 6:40-7:41

Any other neighborhoods I should speed run?

**Comment by misaugstad** [comment]
Quick note, re: "little yellow avatar on the mini map disappearing", see issues #335 #62 #612. It is a known problem with the GMaps API.

**Comment by r-holland** [comment]
Noted. I guess that issue can be ignored in my report.

**Comment by misaugstad** [comment]
Yep. Another thing in trying to narrow down the scope: as for the large amount of double clicking... Well we can't really help that :) But also after looking through your videos, there were quite a few instances where you probably would have found an arrow pointing in the correct direction if you searched around a little more. At those large intersections, there are usually quite a few panos that exist just for the intersection itself, so you may click an arrow three times, move 1ft each time, and on the third time you move, an arrow pops up that allows you to take a turn.

Obviously users don't always know that, but I think that if a user doesn't remember that they can double click, they will probably do a lot more clicking around with the arrows and would find their way through most times.


Re: "dialogue box sometimes appeared while there was still a bit of red line left that I hadn't covered. In these situations, should users keep stepping forward...or click to move location?".

I think that they are supposed to be finishing the route, but (I think) the message is popped up a little early to deal with a not-too-uncommon problem of having a street ending at a dead-end, but there is no pano far enough along the street for one to ever reach the end of the dead-end. So users were stuck at a dead-end, unable to finish the audit task. #491 #487

**Comment by misaugstad** [comment]
Now regarding the most important issue, and the point of this whole thing! The issue where you had to jump four times in a row. I do think that you would have gotten out of some of those with some more double clicking, but that is still really bad, and it would confuse a lot of people to be placed in a museum or a garden, and especially in the tunnel.

One idea to deal with this... We can pop up a message if users try to go to this region saying something along the lines of
"this neighborhood is known to be hard to navigate in, so if you are new to our tool, maybe you could come back to this neighborhood after getting some practice in an easier one!"

For auto-assigning neighborhoods to users, we could also only auto-assign these neighborhoods to "experienced" users.

I imagine that, upon expanding to more cities, we will come across the same sorts of issues in specific neighborhoods. Traffic in tunnels, roads, and bridges on top of one another, popular landmarks having GSV images that get people stuck, etc.

**Comment by r-holland** [comment]
Just a few more example images of "weird paths" from my exploring. I don't believe these first ones are very severe. In my opinion, while these would probably be annoying, it's still pretty clear where the route wants you to go.

Here, the routes took me down a street, then turned me around to walk back on the same exact street.
![image](https://user-images.githubusercontent.com/19720010/27648559-ee95da14-5bfc-11e7-916e-6f41d6d2cc13.png)
![image](https://user-images.githubusercontent.com/19720010/27648729-71965dee-5bfd-11e7-93bc-a8c970a504dc.png)
![image](https://user-images.githubusercontent.com/19720010/27649372-939edd42-5bff-11e7-8cca-19929c2dc9a9.png)

Here, the route takes me in a small triangle around an intersection, making me double back on my path.
![image](https://user-images.githubusercontent.com/19720010/27648672-476d4d7a-5bfd-11e7-92f6-0e0d1725b9d3.png)

These issues are more concerning, as they involve being situated in areas where movement is impossible and jumping (something not discussed much in tutorial) is necessary.

Here, I was dropped inside the Smithsonian Gift Store.
![image](https://user-images.githubusercontent.com/19720010/27648777-a1e89926-5bfd-11e7-85bf-a420fd42f4b1.png)

In both of these situations, after clicking around with the arrows a lot, I could find no way to naviagte to the desired street. Then, after double clicking on that street, it took me past the street to the area beyond, and I had no way to double click back.
![image](https://user-images.githubusercontent.com/19720010/27648929-28549f6e-5bfe-11e7-8724-3752ddc6b83b.png)
![image](https://user-images.githubusercontent.com/19720010/27649091-ba724a54-5bfe-11e7-8cb4-32bb698bc0f7.png)

**Comment by manaswis** [comment]
I found an issue that talks about why the routes generated are weird. Look at #129 
Kotaro mentions this:
> This is probably due to the OpenStreetMap data we use. I cannot programmatically fix it (need to fix the data in the database).

**Comment by manaswis** [comment]
Another instance:

![image](https://user-images.githubusercontent.com/2873216/29315396-1eb1b45c-8191-11e7-8e0c-9c67764b5514.png)
