### ISSUE TITLE
Potentially Have Reset Map Button for Choropleth to Reset Zoom and Pan Location

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#725]
Potentially Have Reset Map Button (or link) for Choropleth to Reset Zoom and Pan Location to default.

![image](https://user-images.githubusercontent.com/1621749/27385486-de7f15b0-5660-11e7-8a0d-10ca4397ba68.png)

**Comment by misaugstad** [comment]
I like this idea. As I was looking at options I came across [a zoom slider](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-zoomslider/) that looks nice.

Here is a screen grab from that page:
![zoombar-example](https://user-images.githubusercontent.com/6518824/27437769-51a3ff4e-5731-11e7-8f33-5ff1b04b1dd1.png)

I realize that the issue that we are trying to solve here is that the tiny +/- in the corner doesn't make it obvious enough to the user that they can zoom using it, and this is a problem since we disable scroll zoom on the landing page.

So I can add a custom button that says "reset zoom" on it or something, or I can put in the slider which is more obvious than the tiny +/-. Do we have a preference before having seen them both?

**Comment by manaswis** [comment]
Also, there is another point to consider -- After the user zooms, the zoom controls/reset zoom button should reposition so that its visible on the page regardless of the zoom level of the map. For example, currently, after zoom, the controls are not visible.

![image](https://user-images.githubusercontent.com/2873216/27437948-dae3c096-5731-11e7-8c00-8f385470bd4f.png)

**Comment by misaugstad** [comment]
That is very weird, that doesn't happen to me! I will check that out on a few different browsers too. So you are on the landing page when you do that, and did you zoom in with the zoom control or did you click on a neighborhood to zoom?

**Comment by manaswis** [comment]
So I did some more testing and this is what I found:

1. When the zooming controls are visible, and then you click one of the neighborhoods, 
 the controls automatically reposition.

![image](https://user-images.githubusercontent.com/2873216/27440947-25c081fa-573a-11e7-8426-99140e7808a6.png)

![image](https://user-images.githubusercontent.com/2873216/27440973-30ffe290-573a-11e7-89ad-f7cf0a07119d.png)

**Special case**: If you scroll down a bit enough to hide the zooming controls but the majority of the map is visible, and then you click one of the neighborhoods, the zooming controls stay hidden.

![image](https://user-images.githubusercontent.com/2873216/27440995-3b29c862-573a-11e7-8e21-d210feba1906.png) -- Continuation from the previous screenshot.

![image](https://user-images.githubusercontent.com/2873216/27441008-41de54d4-573a-11e7-9cd9-f35063f33c40.png) -- Clicked 16th Street Heights, the zooming controls stay hidden.


2. If you zoom in using the zooming controls, they hide once you are zoomed in. 

![image](https://user-images.githubusercontent.com/2873216/27440737-a7844ee8-5739-11e7-974f-b55a9a01aebe.png)

![image](https://user-images.githubusercontent.com/2873216/27440746-b057c2fc-5739-11e7-82b2-5456b941c564.png)

If you try again by scrolling up and making the zooming control visible on the screen, and then use it to further zoom-in, it still hides.

![image](https://user-images.githubusercontent.com/2873216/27440780-bd7cae8e-5739-11e7-81c4-988a955c0237.png)

![image](https://user-images.githubusercontent.com/2873216/27440796-c496ecca-5739-11e7-8a6f-1bf45bdf1285.png)

**Comment by misaugstad** [comment]
The zoom slider seems to work well and look good to me. It also helps with the issue Manaswi brought up because it is a lot longer so one is much less likely to lose track of it.

![zoom-slider](https://user-images.githubusercontent.com/6518824/27454680-c2ae5572-5768-11e7-866c-95edc4b9b66f.png)

**Comment by jonfroehlich** [comment]
I really think the legend needs to be more prominent. Can you at least increase size and font?

**Comment by misaugstad** [comment]
Yep, still on the to-do list, unfortunately!

**Comment by manaswis** [comment]
Merged via #746
