### ISSUE TITLE
Question Marks on Label Buttons

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#78]
I think it's important that users can easily view examples of what constitutes an accessibility problem for each label along with ratings. And, while we are moving in the right direction on this, we're not there yet. I find the current implementation with '?' overlays to be highly distracting. I think we need to find a better way of allowing users to quickly see examples.

![image](https://cloud.githubusercontent.com/assets/1621749/14624826/0b079a5a-05ac-11e6-9277-47a700c68af0.png)

As now, the '?' are given too much attention. Compared to the label buttons themselves, which are the number one interactive objects in our design, the '?' will be much less used and, thus, does not deserve its position in the interface or its salience.

**Comment by nguyenist** [comment]
Possible ways to reduce the attention to the `?`s:
- Use 1 accent color instead of 4, or make them not neon
- Use word `examples` in gray below the button, make it clickable to the example
- Move ? to top right instead of bottom left, it clashes with the text and makes the button seem busy

**Comment by nguyenist** [comment]
@kotarohara hey i'm having trouble with my dev environment. do you mind screenshotting the current interaction? what does the screen look like when you tap on the question mark vs tap on the button?

**Comment by kotarohara** [comment]
@nguyenist 

When you click the button, the interface looks like:

![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/15480570/48960358-20f4-11e6-9577-c9b8ccde0ee4.png)

The interface opens the window with examples when you click the "?":
![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/15480616/81c79c4a-20f4-11e6-9854-21e8fbf843dc.png)

**Comment by nguyenist** [comment]
the user flow/interaction that seems likely / intuitive: 
- user does tutorial
- after completing tutorial, user gets placed into a random area. s/he *sort of* remembers all of the steps of what to do but will get into the labeling groove by actually doing it multiple times on their own.
- user double taps to "move" down the street. thoughts: "i don't know what i'm going to see. so i'm not going to be in a mode all the time." -- "i don't want to have to choose from 4-5 different options before labeling. i want to tap and label very quickly so i can get points / help out the community / [insert whatever incentive they have for being on this site]

have been researching. here are some preliminary ideas that could be helpful. will sketch. 
- icons w/ text -- change to a single word
- list that is vertical with a question mark next to each item
- select category "curb ramp mode". then on the interface of streetview, it says "curb ramp mode" and a help button next to it that allows you to see more infromation.
- when you first select the item for the first time, the help menu comes up anyway so the user is forced to see it and can come back to it if they want. 
- one single button. when you click on street view image somewhere, you choose what that component is. 
- when you click on a point in street view, a menu pops up under your mouse with options. you keep your mouse click held down and move through the menu of options "curb ramp, missing curb ramp, obstacle, etc." and when you let go it makes the selection. the last selected option is the default. Say you chose Obstacles for the last component you found in streetview. You would see a menu that says"
"Redo last (Obstacles)"
---
Ramp
No Ramp
Obstacles
Other

**Comment by nguyenist** [comment]
![img_2115](https://cloud.githubusercontent.com/assets/4484141/15697253/8b856a08-2786-11e6-8da4-659d991c2029.JPG)
![img_2116](https://cloud.githubusercontent.com/assets/4484141/15697261/8e5c292e-2786-11e6-8e37-9511f52fb449.JPG)
![img_2117](https://cloud.githubusercontent.com/assets/4484141/15697263/90302af2-2786-11e6-8622-30bbc3a5fb41.JPG)
![img_2118](https://cloud.githubusercontent.com/assets/4484141/15697265/929ae4ee-2786-11e6-873f-f67399f2f477.JPG)

**Comment by kotarohara** [comment]
@nguyenist This is great. Reply inline:

> - User double taps to "move" down the street. thoughts: "i don't know what i'm going to see. so i'm not going to be in a mode all the time." -- "i don't want to have to choose from 4-5 different options before labeling. i want to tap and label very quickly so i can get points / help out the community / [insert whatever incentive they have for being on this site]"
> - One single button. it might be called "Label" when you click on street view image somewhere, you see a menu of items (ramp, no ramp, obstacle) and can choose what that component is. Allows user to move more quickly through versus memorizing button placement, then tapping the streetview area, etc.

Having label options at the top has a benefit of constantly reminding people what they have to find in Street View imagery, whereas context menu (which our very first interface had originally) hides what needs to be labeled from the users. So we should keep the options always visible to the users. Not sure what you proposed would allow people to move more quickly; why you think so?

> icons w/ text -- change to a single word where possible. (1) Ramp (2) No ramp (3) Obstacle (4) Surface (5) Other -- sidenote: how likely is "surface problem" going to be chosen as an option? 5 options is quite a lot for a user to have to choose every single time they label something. ideally-- reduce # of options for quicker labeling. can surface problem be in "other"?

Hmm, I agree I'd like to shorten as much as possible, but "Ramp" and "Surface" don't really make sense. Maybe "Obstacle" is fine. Surface problems happen time to time (e.g., tree root breaking sidewalk surface). I think we should keep it. 

> - list that is vertical with a question mark next to each item
> - select category "curb ramp mode". then on the interface of streetview, it says "curb ramp mode" and a help button next to it that allows you to see more infromation.
> - when you first select the item for the first time, the help menu comes up anyway so the user is forced to see it and can come back to it if they want.
> - when you click on a point in street view, a menu pops up under your mouse with options. you keep your mouse click held down and move through the menu of options "curb ramp, missing curb ramp, obstacle, etc." and when you let go it makes the selection. the last selected option is the default. Say you chose Obstacles for the last component you found in streetview. You would see a menu that says"

I like these 👍  Let me take a look at mock ups you drew and comment.

**Comment by kotarohara** [comment]
Actually I like the following ideas.

- select category "curb ramp mode". then on the interface of streetview, it says "curb ramp mode" and a help button next to it that allows you to see more infromation.
- when you first select the item for the first time, the help menu comes up anyway so the user is forced to see it and can come back to it if they want.

I like having "Explain This!" on the overlay message box when you click label type. It's kind of hidden from the user, but I guess that can be mitigated when we combine the second idea (i.e., show the examples when the user click label for the first time.)

Also, thank you for also brainstorming the design of what we show after clicking the help buttons :) Should we chat? Maybe tonight or tomorrow night.

**Comment by nguyenist** [comment]
Usability study 1: Observed user click through current dashboard
![image](https://cloud.githubusercontent.com/assets/4484141/16029317/e80681d4-31b5-11e6-8aec-abb1bf32a0b6.png)


**what do these buttons represent? (pointing to the top 5 at the top)**
I would click on one of those buttons then click on something on the street image

**what do each of the buttons mean?**
curb ramp = there is a curb ramp
missing curb ramp = no curb ramp. the crosswalk drops right down.
obstacle in path = might be a curb ramp but cant use it bc obstacle in path
surface problem = cracked or too bumpy or something
other = something that's not those 4

**what do you imagine would happen if you clicked "?"**
it would bring up a tooltip that explains what it was. a text based one that explains what this button means."

**what would be in the tool tip?**
"example images. it was part of the tutorial so it foreshadowed what i thought i might see."

action: actually clicked on it: 
confused because text is quality 1: good // rating 4: very hard to pass. what is quality versus rating mean? words seem to not be consistent.

**could you explain what the numbers mean?**
a 1 = the best top quality.
a 4 = the worst. not sure what the scale is. 
1 = these are the qualities i would be looking for. the ramp dump right into the crosswalk.
4 = not usable i guess.
"wait it doesn't make sense. it seems like the rating should go the other way because it's not rankings. its rating. a 5 is good and a 1 is bad."

**clicked on missing curb ramp "?"**
- why is it severity? quality? rating? why is it different for everything?
- to me it would be a 2-3. a 3 would be better than 2 but the 1 would be the worst. not passable would be 0. the numbers need to be flipped because to me, a 5 is the best. like 5 stars.

**clicked on obstacle in path "?"**
- i thought we were just rating the end of a sidewalk and here i realize we are now rating the entire sidewalk. 
- again here, the 1 to 5 should be the other way around. 
- this makes sense, completely passable would be a 5. completely impassible would be a 1.

**clicked on surface problem "?"**
- i don't understand why cobblestone would be a 2-4 and vegetation in that photo would be a 5. vegetation is worse than cobblestone? why? this logic doesn't make sense.
- severity 2-4... what does this mean? i need an example of a 1, 2, 3, 4, and 5. because you give me an example of a 2 and a 5. for example-- it's kind of worse than a 5... but not quite as bad as that 2? is it a 3 or 4? feels too ambiguous and i wouldn't know how to rank this

**Comment by kotarohara** [comment]
@nguyenist 

This is awesome! Can you do the same thing with 2 more people? It would be awesome if you can combines the takeaways for user 1, 2, and 3 and come up with a high priority task.

Did they have any comments on the mocks you sketched? I wonder how they felt about the design of "?".

**Comment by nguyenist** [comment]
@kotarohara @jonfroehlich Thanks for the feedback. Yes, definitely planning on doing a few more :) Will update the transcribed interview as I go along / grab folks to get more thoughts.

We worked a little backwards and it is important to first observe how people currently use the dashboard. Then note the pain points / problems around those buttons before deciding the best way to fix them.

My proposed method:
1. Observe a few people using the current solution (for this case, specifically the "?" buttons on the dashboard)
2. Note the top takeaways / problems from those interactions (no biased questions, mainly observing)
3. Prototype / design potential fixes to those problems (2-5)
4. Observe people using the new (2-5) prototypes / designs
5. Narrow down to the best designs that would allow user to achieve desired effect (in this case, the desired effect is having people learn how to properly rate items: curb ramp, no curb ramp, surface problems, etc., possibly using some sort of help trigger) 
6. Iterate designs to incorporate feedback.
7. Repeat steps 4-6 if needed.
8. Present solution to Kotaro / Jon while documenting the process in the meantime

Obviously because of time constraints, we don't have forever to go through these steps in micro-detail, but I can go through what I can to learn as much as possible with the resources we have. Any user research and perspective is helpful / better than none and the product will be more user friendly for it :) Would love any thoughts as we go along. 

Yay team!

**Comment by nguyenist** [comment]
Usability study 2: Observed user click through current dashboard to understand what information they gathered from the current buttons + "?" buttons.

**what do these buttons represent? (pointing to the top 5 at the top)**
- so here's what i see: streetview. pins. sidewalks. understand particular sidewalks
- collectively, labels are supposed to place then on the map
- place on map

**the user's natural interactions regarding the button // without being asked**
- user initially clicked and dragged the button onto the streetview
- user then clicked into the map
- realized how to click the button and then drop the tool after about 30 seconds
- after user placed the green label, they tried to drag the label but couldn't. found the hover + delete option and then deleted it and replaced the green label onto the streetview map.

**what does each of the buttons mean to you?**
- curb ramp: for a wheelchair accessible ramp
- missing curb ramp: area that someone can't reach
- obstacle in path: not sure. fire hydrant. not a clear path. 

---in transit will update notes in a few----

**Comment by nguyenist** [comment]
Usability Study 3:

**Comment by nguyenist** [comment]
Overall takeaways by priority:
1
2
3

Will add here later.

**Comment by kotarohara** [comment]
@nguyenist Are you going to summarize the takeaways? It would be great if you could separate (a) the design of the "?" marks and (b) other things you've found out (e.g., it seems like you've got good feedback on how to design the actual help window).

**Comment by nguyenist** [comment]
Yes I will. Haven't forgotten. More soon.

On Tuesday, June 21, 2016, Kotaro Hara <notifications@github.com> wrote:

> @nguyenist <https://github.com/nguyenist> Are you going to summarize the
> takeaways? It would be great if you could separate (a) the design of the
> "?" marks and (b) other things you've found out (e.g., it seems like you've
> got good feedback on how to design the actual help window).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/78#issuecomment-227539669>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AERsLb2gOuooCui-PkTWvYvJ-GARbjVOks5qODX1gaJpZM4IKRn5>
> .
>


-- 
Sent via mobile device

**Comment by nguyenist** [comment]
@kotarohara 

**Takeaways for ? marks:**
1. Number one takeaway: Design "?s" to stand out. Right now, people don't seem to know you can click on them until I point them out. Notes for me-- consider using words like "read more" or "learn more" -- think about ways to do this for all buttons w/o looking redundant.

**Takeaways for other things on help page:**
1. Change ratings logic. 1 = worst. 5 = best.
2. Lower the task length. Need feedback sooner to reduce shock of being so far from done (relates to #66)
3. Clearly explain ratings once you actually click on the "?" -- make language consistent (severity, quality rating), give reasons for why something should be a 1, 2, 3, 4, 5. For example) Think about how to rate Surfaces. Smooth (5) vs bumpy (1)? 
4. Redesign the "help" screen to include the ratings bar so people can easily see the correlation when they have to rate.

**Comment by nguyenist** [comment]
Option A: Horizontal buttons
![image](https://cloud.githubusercontent.com/assets/4484141/16367594/2a25fd64-3bf3-11e6-8f58-dc88f1b84c81.png)

Option B: "Explain this!"
![image](https://cloud.githubusercontent.com/assets/4484141/16367603/45e26628-3bf3-11e6-8230-f35bd59391ac.png)

**Comment by kotarohara** [comment]
@nguyenist 

> Takeaways for ? marks:
> 1. Number one takeaway: Design "?s" to stand out. Right now, people don't seem to know you can click on them until I point them out. Notes for me-- consider using words like "read more" or "learn more" -- think about ways to do this for all buttons w/o looking redundant.

Great! But I don't think we will go though a massive interface redesign, so Option A would not happen. I like both B and C. For C, probably we don't need parenthesis. Also for C, are you envisioning a single help window that opens up after clicking "click here to ..."? Do we have enough space to explan all the accessibility feature types? 

Are you going to see which one (B or C) people prefer?

> Takeaways for other things on help page:
> 1. Change ratings logic. 1 = worst. 5 = best.
> 2. Lower the task length. Need feedback sooner to reduce shock of being so far from done (relates to #66)
> 3. Clearly explain ratings once you actually click on the "?" -- make language consistent (severity, quality rating), give reasons for why something should be a 1, 2, 3, 4, 5. For example) Think about how to rate Surfaces. Smooth (5) vs bumpy (1)? 
> 4. Redesign the "help" screen to include the ratings bar so people can easily see the correlation when they have to rate.

I feel like (1) keeps coming up all the time (not only the last few month but since long time ago). We'll decide this week. (2) Ok. Sounds good. I'll make them shorter. (3 & 4) I'll get descriptions and try to get pictures. Once that's ready, I'll probably ask you to design the help window.

**Comment by nguyenist** [comment]
@kotaro sounds great.

Re ? (1) Yes I think it's possible to design a single page. There is a ton of text and if we can condense it down to a simple page concept that will resonate w users that would be ideal. Based on tests they will start rating based on what is in their head vs reading a ? help page 5 times which may skew results otherwise. 

Re other (2) no need to gather all photos just yet. Want to see how much info is necessary for someone to understand how to do rankings for each. Would be great to get a better understanding for what counts as 1, 3, 5 for each category to start.

**Comment by nguyenist** [comment]
Feedback based on 3 usability studies: 

User 1 takeaways: 
- Did not see "Explain this" partly because my design didn't have an overlay
- Saw the "Click here... etc." but only after a long time. 

User 2 takeaways: 
- Tried to drag and drop multiple times and realized you needed to tap the button + drop
- Noticed the "Explain this!" and didn't notice the "Click here..." in Version C

User 3 takeaways: 
- "Explain Sidewalk problems" instead of "Explain this!"
- Doesn't like "click to learn how" -- would prefer "Learn how" 
- This seems like it is for people in wheelchairs but I have children. What about kids in strollers? Is this for moms too? (Note about branding)

**Comment by kotarohara** [comment]
# Scale
I gave thoughts on this. We are not going to flip the scale. 1 means accessible and 5 means inaccessible. This scale will be consistent across all the features. Meaning of scale 1, 3, and 5 are:
(1) **Passable:** Not an accessibility problem. Wheelchair users can navigate without a problem.
(3) **Could be a problem:** The problem could pose an accessibility problem for some people with mobility impairments.
(5) **Not passable:** The problem is a major obstruction for people to use the sidewalk.

## Curb ramp
* (1) A well-maintained, large curb ramp that everyone can pass.
* (3) Narrow curb ramps and curb ramps without enough clearing space could pose accessibility problems for people who are using big electric wheelchairs.
* (5) A curb ramp that is not usable because of, for instance, major cracks and water accumulation.

## Missin Curb Ramp
* (1) N/A
* (3) Even there isn't a curb ramp at the end of a crosswalk, the problem could be less severe when there are curb ramps or driveways nearby to help people get on/off the sidewalk.
* (5) There are no ways for wheelchair users to get on/off the sidewalk.

## Obstacle
* (1) N/A
* (3) An obstacle makes a path narrow and could obstruct the way for some people who use large electric wheelchairs.
* (5) A major obstacle that makes sidewalk not traversable for wheelchair users.

## Surface Problem
* (1) A slightly bumpy surface that makes rolling the sidewalk uncomfortable (but passable).
* (3) A sidewalk surface that could pose a problem for some people; e.g., sandy surface, cobblestone pavement with shallow ridge.
* (5) Poorly paved surface that cannot be traversed by wheelchair users, or cobblestone pavement with deep ridge.

**Comment by kotarohara** [comment]
\cc @nguyenist 

> Feedback based on 3 usability studies:
This is awesome, but I was a bit confused by 'Would like to go with the overlay with "Explain [insert button titles: sidewalk problems]"' Could you explain this a bit more or show a design mock?

**Comment by nguyenist** [comment]
@kotarohara 

Screenshot / Option B. Instead of "Explain this" it would say "Explain Sidewalk Problems" / "Explain Curb Ramp" / "Explain Obstacle in Path" etc.

**Comment by nguyenist** [comment]
@kotarohara Cool! Can people define any of the categories by using just this high level explanation? Expecting users to know / learn 5 separate categories with slightly different definitions might be asking a lot. I like being able to embed the concept 1 = good, 5 = bad throughout the categories.

A few questions:

Missing Curb Ramp
- When would someone mark "Missing Curb Ramp: N/A"? If N/A why even allow this to be an option?
- When would someone mark "Missing Curb Ramp: (5) There are no ways for wheelchair users to get on/off the sidewalk." -- wouldn't that be every single part of a sidewalk that doesn't have a ramp? This is something someone asked me during the usability study.

Obstacle
- When would someone mark "Obstacle: N/A"? Isn't that every part of a street where something is not obstructed? -- this is another question an interviewee asked. If N/A why allow this to be an option?

Surface Problem
- (1) A slightly bumpy surface that makes rolling the sidewalk uncomfortable (but passable).
Does not match your other definition:
- (1) Passable: Not an accessibility problem. Wheelchair users can navigate without a problem.

**Comment by kotarohara** [comment]
@nguyenist 

Yeah, what do you think? I'll welcome your opinion! I would put 1-5 scale issue aside for now though :) First, it's an optional information people can provide, so I wouldn't worry to much about it. And regarding "If N/A why allow this as an option," (a) you'll never know if it's obsolete or not, so collect as much data as possible; (b) we are just trying to provide as much instruction as possible, there isn't even a guarantee people will follow our instruction so why don't we just do our best and not bother any more? (c) Once we have data, we can conclude this. We don't even know if this rating is reliable (What is the "reliable" rating anyway?)

It's great that we settled on the Design B. As you move on to building it, you'll probably need my help navigating the code base. So I think it's a good idea for us to sit together and code for 2-3 hours this weekend and knock it out of our way. It would be great if you can come to College Park, but if not I can come to DC. Either way, can you (i) refresh your memory and set up your dev environment, and (ii) polish the design of B and make sure we can focus on coding when we meet?

**Comment by nguyenist** [comment]
Would totally try to meet you but I'm out of town until Tuesday. Happy to
chat with you via Skype and parallel work on this. We can chat more details
so I make sure I'm understanding everything as you'd like.

Does that work? How about Friday?

On Thursday, June 30, 2016, Kotaro Hara <notifications@github.com> wrote:

> @nguyenist <https://github.com/nguyenist>
>
> Yeah, what do you think? I'll welcome your opinion! I would put 1-5 scale
> issue aside for now though :) First, it's an optional information people
> can provide, so I wouldn't worry to much about it. And regarding "If N/A
> why allow this as an option," (a) you'll never know if it's obsolete or
> not, so collect as much data as possible; (b) we are just trying to provide
> as much instruction as possible, there isn't even a guarantee people will
> follow our instruction so why don't we just do our best and not bother any
> more? (c) Once we have data, we can conclude this. We don't even know if
> this rating is reliable (What is the "reliable" rating anyway?)
>
> It's great that we settled on the Design B. As you move on to building it,
> you'll probably need my help navigating the code base. So I think it's a
> good idea for us to sit together and code for 2-3 hours this weekend and
> knock it out of our way. It would be great if you can come to College Park,
> but if not I can come to DC. Either way, can you (i) refresh your memory
> and set up your dev environment, and (ii) polish the design of B and make
> sure we can focus on coding when we meet?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/78#issuecomment-229571422>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AERsLf9qBddksx4Co0HF13viRY3AAofZks5qQ2JXgaJpZM4IKRn5>
> .
>


-- 
Sent via mobile device

**Comment by kotarohara** [comment]
You mean tomorrow, right? Sure! I'll be working all day, so call me whenever you want :) So my understanding is you'll spend time tomorrow and finish the design and implementation of the question buttons tomorrow?

**Comment by nguyenist** [comment]
Just texted you. Will keep you posted after I get back in town.

On Thursday, June 30, 2016, Kotaro Hara <notifications@github.com> wrote:

> You mean tomorrow, right? Sure! I'll be working all day, so call me
> whenever you want :) So my understanding is you'll spend time tomorrow and
> finish the design and implementation of the question buttons tomorrow?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectSidewalk/SidewalkWebpage/issues/78#issuecomment-229822312>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AERsLUh9zogtCz4jiLErrbmS9ldnNG8gks5qRFpggaJpZM4IKRn5>
> .
>


-- 
Sent via mobile device

**Comment by kotarohara** [comment]
@nguyenist Do you have updates?

**Comment by kotarohara** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/612263/17897359/eb09ba42-6921-11e6-95e6-0ab0a433b481.png)

**Comment by jonfroehlich** [comment]
Great, can I test it out? When can you deploy this to production?
