### ISSUE TITLE
New Rating Scale Design Idea

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#80]
![image](https://cloud.githubusercontent.com/assets/1621749/14625020/8033df36-05ad-11e6-89df-b6fe1069e590.png)

![image](https://cloud.githubusercontent.com/assets/1621749/14625022/8991a536-05ad-11e6-9388-3e0b94ae72ab.png)

We have two issues with the current rating scale: first, while labeling a positive attribute 'Curb Ramp' compared to a negative attribute like 'Surface Problems' or 'Curb Ramp Missing' is a different sort of characterization (valence is flipped), we use the same rating scale with the same options. Is this a good thing or bad thing? I find myself getting confused about it. Second, it's not immediately clear from quickly looking at the scale if far left is good and far right is bad or vice versa.

Perhaps the solution to both of these things, is to update the rating scale design to include visuals like this:
![image](https://cloud.githubusercontent.com/assets/1621749/14625016/75dc4370-05ad-11e6-8f81-7dfedb3037ad.png)

or this:
![image](https://cloud.githubusercontent.com/assets/1621749/14625026/946cb180-05ad-11e6-8f58-5bd6640da400.png)

Now, these are not perfect because they show a happy face at far left and, really, in our case we would almost want to start with a straight face and get more unhappy (except for the 'Curb Ramp' label).

Thoughts?

**Comment by nguyenist** [comment]
Interesting / related: http://www.measuringu.com/blog/left-side-bias.php
Takeaway of that article = Survey Respondents Prefer The Left Side Of A Rating Scale

Smiley ratings made me think of Runkeeper / Nike Running app. After you finish a run, you choose a smiley to rate how you felt after the run. It feels natural and intuitive to use smiley faces for that context because the user is actively feeling some sort of emotion. Do I feel awful / did I feel sluggish? Definite sad face. Run was mediocre. Meh, middle / straight lip face.

In this context, the rating is less emotional, more objective-- is the road passable? If so, by what degree? Perhaps we could use: 
* green check mark on left, red "x" on right
* wheelchair left in green circle icon, wheelchair on right red circle icon
* <a href="https://www.geocaching.com/bookmarks/view.aspx?guid=93decfe9-9753-4213-80d8-ae3e4e88a154">Geocache</a> and "<a href="http://www.sagetraveling.com/Rating-System-Explanation/>"sagetraveling"</a> uses stars</a>

Depending on what you guys decide, I'm happy to design the icons if you'd like to stay consistent with the aesthetic of the rest of the site.

**Comment by kotarohara** [comment]
Related to #15

**Comment by kotarohara** [comment]
Ongoing discussion on #78 . It should be moved here.

**Comment by kotarohara** [comment]
Updated the design of the context menu.

![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/17826406/8a9bc9ba-663e-11e6-8f6a-37d718bcff26.png)

**Comment by jonfroehlich** [comment]
This is great @kotarohara! Nicely done. 

I imagine that the 'Description' blank automatically changes the 'e.g.,' part depending on the label type?

![image](https://cloud.githubusercontent.com/assets/1621749/17855630/b004a9d2-6847-11e6-9338-d448fe469a79.png)

**Comment by jonfroehlich** [comment]
Also, @kotarohara, when you hit enter, does the dialog box close (e.g., automatically 'click' the OK button on enter keypress)? If not, can we do that?

**Comment by kotarohara** [comment]
Re: Description. Yes, e.g., changes depending on the label type. It's been like that for a while, actually :)

Re: Enter. Yeah, it's possible.

**Comment by jonfroehlich** [comment]
@kotarohara 

Re: Description. Great!

Re: Enter. Can you do that then? Your answer was ambiguous. :)
