### ISSUE TITLE
Have new users avoid "advanced" neighborhoods

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#804]
Issue #718 had two parts to it, the first being users dropped into photospheres, which was being resolved via #789. The other part has to do with there being tunnels underneath roads, where it is difficult or impossible to follow the route that is actually assigned to you. What we want to do is to get new users to avoid these neighorhoods. Experienced (longtime) users will be less likely to give up and feel frustrated or confused when encountering these things, and should be more likely to know to use the jump button when necessary.

Our plan for a solution is to:
1. Change the message on the popups for the landing page choropleth and user dashboard maps to indicate that these neighborhoods should only be done if they are an experienced user
2. Non-experienced users should *not* be auto-assigned these neighborhoods.
3. When a user does decide to go into one of these neighborhoods (or if they are auto-assigned it as an experienced user), then a message should pop up that tells them that there are some routes that may be difficult or impossible to follow in this neighborhood, and we should definitely point out the jump button at that point.
4. Thinking ahead a bit... If we do the above modifications, I suspect that as we get close to 100% coverage of DC, we will get to the point where everything is audited except for these couple neighborhoods. The thing is that we are going to be steering a ton of people away from the neighborhoods, without pushing anyone else towards them, and these are *huge* neighborhoods. Therefore, I think it would be a good idea to push experienced users towards these neighborhoods. So in the same way that we don't auto-assign non-experienced users to these neighborhoods, maybe we automatically assign experienced users to these neighborhoods specifically. This point hasn't been discussed yet, and could also be implemented later if we decide to do it.

**Comment by manaswis** [comment]
I see three issues here and each should be an issue in itself so that we can have discussions in their respective threads:

1. Updating message on the pop-ups for selecting neighborhoods from the maps/choropleth.
2. Identifying experienced from inexperienced users and not auto-assigning inexperienced users with advanced neighborhoods 
3. Showing a message informing users that they are in advanced neighborhoods and highlight the use of jump button. This message need not be a pop-up, could be a message on a translucent background that is the size of the audit canvas. The design needs brainstorming.

@misaugstad what do you think? If you agree, could you create these issue threads?

I think @misaugstad  and @sbower213 should work together on this. @sbower213 can take care of the UI update and @misaugstad can setup the Scala end of things.

------------


_for discussion_
>  If we do the above modifications, I suspect that as we get close to 100% coverage of DC, we will get to the point where everything is audited except for these couple neighborhoods. The thing is that we are going to be steering a ton of people away from the neighborhoods, without pushing anyone else towards them, and these are huge neighborhoods. Therefore, I think it would be a good idea to push experienced users towards these neighborhoods. So in the same way that we don't auto-assign non-experienced users to these neighborhoods, maybe we automatically assign experienced users to these neighborhoods specifically. This point hasn't been discussed yet, and could also be implemented later if we decide to do it.

The main point to discuss from the above point is:
> we automatically assign experienced users to these neighborhoods specifically

I agree with this. @jonfroehlich Thoughts on this point?

**Comment by misaugstad** [comment]
@jonfroehlich @manaswis 

>we automatically assign experienced users to these neighborhoods specifically

Some ways this might work:
- When doing assignment for experienced users, give them a higher probability of ending up in one of these neighborhoods
- Whenever they finish a neighborhood, automatically assign them one of these neighborhoods (we will of course give them an option to not do it, and will then give them an easier one).
- When they finish a neighborhood, ask if they want the challenge of a harder neighborhood, and then assign accordingly.

**Comment by manaswis** [comment]
Created an new issue #857 for the last point of discussion. Other issues have been addressed in the respective issue threads. Closing this one.
