### ISSUE TITLE
Exploratory analysis needed for characterizing missing panoramas in panoscraper output

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#828]
Related to #539. From the pano scraper run on 7/4/2017 it was found that 1933 out of the 22268 panorama ids returned blank images. The reason for these missing pano ids is unclear at this point. The following approaches may give us some insight about potential factors and the actual extent of the issue.

- [ ] Visualizing the spatial distribution of the dropped panoramas over DC neighborhoods: Missing panos might be concentrated in a particular type of neighborhood.
- [ ] Visualizing the temporal distribution of the labels associated with dropped : Comparing the stats for prior to and after Anthony's last run of the scrapper. Are we missing panos for more recent audits too or is it just the older ones?

**Comment by misaugstad** [comment]
I don't think that we need this analysis at this point. Here are some reasons that images can't be scraped:
1. They are community-contributed images, so we can't get them from Google's servers.
2. The images have been removed: this typically happens when a new drive through of an area happens; they remove the old images and replace them with new ones.

As long as we scrape frequently, this shouldn't be an issue. And we just did an overhaul of the scraper that should improve stability :)
