### ISSUE TITLE
Just Placed Label But Not Showing Up On Top-Down Map

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#84]
I just placed some labels but they are not showing up on the top-down map. See screenshot.

![image](https://cloud.githubusercontent.com/assets/1621749/14661896/60252312-067f-11e6-98e4-c83c7779d147.png)

**Comment by kotarohara** [comment]
This happens when there is no point cloud data for the location. I don't think there are many locations where Google lacks point cloud data + I can't do anything about this.

One case I'm scared of, which hasn't happenned as far as I know, is Google stops us from accessing the point cloud data as the users access their API too often. Not sure if this will be a problem though, but could be problematic if we get many users.

**Comment by jonfroehlich** [comment]
I see. Hmm. OK, yes, nothing we can do about it. Can we log when this occurs, however, so at least we have some idea of its frequency?

**Comment by jonfroehlich** [comment]
Kotaro and I discussed this. In the cases where we don't have point cloud data, we will just place labels at the angle the avatar is looking + some fixed distance (maybe 20 meters or so; Kotaro will investigate and determine constant). Note: this is only for visualizing in the top-down map.

**Comment by kotarohara** [comment]
I should have implemented this.

**Comment by jonfroehlich** [comment]
Fixed this you mean?

**Comment by kotarohara** [comment]
Yes.

**Comment by jonfroehlich** [comment]
Great, thanks!
