### ISSUE TITLE
What Are the Implications for Forcing Ratings?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#891]
We have talked about the severity ratings dialog quite a bit in design meetings. For example, should we just have two ratings or even three (rather than five point Likert scale). Another question lingering in my mind is whether we should *force* people to rate in order to close this dialog box or should we continue to make it optional...

I personally think that there is a lot of potential value in the severity ratings but from our initial analyses of data, not everyone has been using this feature.

**Comment by misaugstad** [comment]
What if we forced them to rate, but gave a "I have no idea" option? I would be worried that people would overuse this option instead of giving their best assessment, but it could also give us valuable information about what users find ambiguous.

**Comment by misaugstad** [comment]
I still think this is a really good idea, given we include the "I have no idea option"! I think we should do this before deploying to future cities. Shouldn't be hard to implement.

**Comment by misaugstad** [comment]
I believe that instead of forcing ratings, we have opted for something a bit less extreme: we are showing a red "?" when a label has no severity rating to encourage users to rate severity (issue #778 PR #1248). This is the plan for the upcoming deployment, so I am removing the NextCity label; we will see if the feature @aileenzeng wrote increases the use of severity ratings! :)
