### ISSUE TITLE
Results Choropleth: Discuss Raw Counts vs. Count/Mile for Pop-up

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#899]
I think raw counts is likely easier to digest (and doesn't result in decimals) but is inconsistent with how we color the regions...

**Comment by sbower213** [comment]
Counts/Mile is a uniform way to assess all of the neighborhoods in a comparative manner, which would be useful if we were trying to rank neighborhoods against each other. However, since we already do that with the color on the choropleth, and since you can only look at the stats of one neighborhood at a time, I'm leaning towards raw counts. Plus, I think it's cooler to see that there are X issues that have ben found in a neighborhood than seeing if a neighborhood has a higher density of issues.

**Comment by misaugstad** [comment]
I personally prefer consistency, but I don't know how the average user would feel about it (i.e., how many people would really notice?). I don't think that labels/mile is hard to digest at all, but I do agree with @sbower213 that it is kind of cool to see raw counts. Basically I have no opinion, sorry!

**Comment by jonfroehlich** [comment]
Let's just stick w raw counts for now then an close this issue.
