### ISSUE TITLE
Remove Skip Button from Onboarding?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#97]
![image](https://cloud.githubusercontent.com/assets/1621749/15723647/68ef0342-2811-11e6-8d52-c8fa81cb9e7b.png)

I think we may want to remove the skip button from onboarding. In what legitimate cases would we expect users to click the 'skip' button? Only if they've taken the tutorial before, right? Well, if this is the case, shouldn't they have a login?

So, perhaps instead of the 'Skip' button, we should have a 'Sign In' button. So, the text could be like:

We’ll begin with a short, interactive tutorial to get you started. If you’ve taken the tutorial before, click “Sign In.” Thanks for your help in improving the accessibility of the cities.

**Comment by kotarohara** [comment]
We need a skip button. We don't want anonymous users who have taken the tutorial to retake it. We don't have a reliable way to identify those who have taken the tutorial and we cannot assume people have log in accounts.

On the related note, I was talking about the tutorial with Andrea today and we think a way to come back and take the tutorial is important (because anonymous users might just skip and registered users might go through quickly without paying much attention for the first time). I will put a small & subtle button somewhere in the interface that navigates users to retake the tutorial.

**Comment by kotarohara** [comment]
Opened an issue #106

**Comment by kotarohara** [comment]
I'm closing this.

**Comment by jonfroehlich** [comment]
I guess I don't really agree. I worry that the salience of the skip button--and its sheer existence--may indicate to folks that they don't need to take the tutorial.

Also, are you operating under the assumption that most people will be contributing anonymously rather than via logged in accounts?

Finally, some users may find it confusing to have this come up when they have, indeed, already taken the tutorial but the problem is that they have just not signed in. So another thing to think about is potentially adding a 'Login' or similar button to the bottom.

But again, I'm not sure I've ever seen this 'skip' paradigm used before and, to be honest, I don't like it.

**Comment by kotarohara** [comment]
> I guess I don't really agree. I worry that the salience of the skip button--and its sheer existence--may indicate to folks that they don't need to take the tutorial.
Hmmm, maybe we can make the button subtler? Maybe instead of a button, a text. But we need skip.

> Also, are you operating under the assumption that most people will be contributing anonymously rather than via logged in accounts?
I'm not making any assumption. We won't know if people will be registered or anonymous.

> Finally, some users may find it confusing to have this come up when they have, indeed, already taken the tutorial but the problem is that they have just not signed in. So another thing to think about is potentially adding a 'Login' or similar button to the bottom.
Adding a way to sign in... Hmmm, you may be right that we may want to add a way to sign in/sign up here. But given that we ask them to sign up while they are conducting audit, I don't know how important it is to ask them here + I feel like we are asking users to sign up too often if we do that. 

> But again, I'm not sure I've ever seen this 'skip' paradigm used before and, to be honest, I don't like it.
:)

**Comment by jonfroehlich** [comment]
I think switching to text for skip could be the right call and then the other button could be a Login button.

We would need to sketch this out quickly to see how it works.... but basically, it's:

- Take Tutorial! This button is pressed to take the tutorial
- Login. Would need some text around this that states "Already taken the tutorial? Have an account? Login now"
- Skip. This is just in text and states that if they've already taken the tutorial but want to remain anonymous contributors, can click on the skip text link.

Also, in terms of assumptions about your users, my point was--you are making very definitive user interface decisions here and I was wondering how you are making these decisions. To me, it seems like you are optimizing for the 'anonymous' user case--which is fine--but I think you should make those assumptions explicit in your design process so that we can weigh the tradeoffs appropriately. I guess I was assuming that more users would create logins for themselves. Either way, I think the answer is that we have to deploy and learn from our users (and our successes/mistakes).
